### ISSUE TITLE
Cookies are lost when replication is restarted

### ISSUE THREAD

**Issue by andyjohns** [couchbase/couchbase-lite-ios#1008]
Our system uses session cookies, cookies without a date, so these issues could all be related to that:

1. When setting up replication, cookies are not automatically used from NSHTTPCookieStorage.sharedHTTPCookieStorage. They need to be manually copied into the replicators using CBLReplication setCookieNamed.... 

2. When replication is stopped, then restarted, the cookies added using setCookieNamed are lost, and need to be re-added. I would expect once cookies are set, they would be continued to be set for the life of the CBLReplication object.

3. Finally, the CBLReplication setCookieNamed... function does not have the __nullable flag on the expirationDate parameter. This means when using Swift we cannot pass nil into this parameter, and thus cannot easily use dateless session cookies. I was able to work around this with a simple category:

    @interface CBLReplication (nullabledatesetcookie)
          - (void) setCookieNamed: (NSString* _Nonnull)name
                 withValue: (NSString* _Nonnull)value
                  path: (NSString* _Nonnull)path
                 expirationDate: (NSDate* __nullable)expirationDate
                 secure: (BOOL)secure;
     @end

but it would be better if CBL supported this without the need.

Thanks

**Comment by snej** [comment]
On Dec 18, 2015, at 8:51 AM, andyjohns <notifications@github.com<mailto:notifications@github.com>> wrote:


Our system uses session cookies, cookies without a date, so these issues could all be related to that:

  1.  When setting up replication, cookies are not automatically used from NSHTTPCookieStorage.sharedHTTPCookieStorage. They need to be manually copied into the replicators using CBLReplication setCookieNamed….

This is intentional. We needed to support independent logins for each replicator, because some apps needed the ability to log into the same server under different credentials at the same time. This meant using our own internal cookie store rather than the shared Foundation one.

  1.  When replication is stopped, then restarted, the cookies added using setCookieNamed are lost, and need to be re-added. I would expect once cookies are set, they would be continued to be set for the life of the CBLReplication object.

That sounds like a bug; could you file an issue please? I’m not the cookie expert (@pasin is), but I suspect this has to do with the cookies not having a date. The replicator will save the cookies persistently, but it’s probably not doing so for dateless ones, and it sounds like they then get lost when the internal replicator object finishes its work.

  1.  Finally, the CBLReplication setCookieNamed... function does not have the __nullable flag on the expirationDate parameter.

Oops; I’ll fix that<https://github.com/couchbase/couchbase-lite-ios/pull/1009>  There were a couple of those parameters that were overlooked when I dumped the big bag of ‘nullable’s into the API earlier this year.

—Jens

**Comment by andyjohns** [comment]
Awesome, thanks for the info @snej

**Comment by pasin** [comment]
@snej is correct that the cookie without expiration date (session based cookie) will not be saved persistently. Currently the life of the cookie storage depends on the life of the internal replicator object. 

When the replicator stopped, the internal replicator object will be released and will be recreated when the replicator restarts so the session based cookies are deleted.

**Comment by snej** [comment]
Should session (dateless) cookies be kept around for the lifespan of the app process?

**Comment by pasin** [comment]
Close this issue as we move the cookie storage to the database level (https://github.com/couchbase/couchbase-lite-ios/commit/517fb6bd59d2c5e2e0726f74573d17f1c43435df).
