### ISSUE TITLE
Possible memory leak during pull replication

### ISSUE THREAD

**Issue by jordanpwood** [couchbase/couchbase-lite-ios#1016]
I have a remote database with about 20,000 small documents.  When I pull the entire database to my device for the first time, the memory used by the app steadily increases and is not released when the pull is done.  The leaks instrument shows that Couchbase and NSURL-related objects are being leaked.  In my app, the memory usage grows to over 500 MB.  

I have made an extremely simple sample app which has a similar memory use profile, although it only grows to about 130 MB when pulling that database.  I sent the sample app to Jens.

**Comment by EthanRTF** [comment]
What version of Couchbase Lite are you using? We had a similar issue when using 1.1.1, but it was resolved when we tried 1.2

**Comment by snej** [comment]
I took a look at the sample app with the Leaks instrument. This is sort of embarrassing, but: There are some utility classes CBL uses that weren't ARC compatible, so they're compiled with the `-fno-objc-arc` flag. At some point I converted those classes to use ARC, and I updated the Mac OS target to take out the compiler flag, but somehow I didn't update the iOS target. (Or maybe I did, but maybe there was some merge issue with the pbxproj file that wiped out the change.) The upshot is that in 1.1.1 those utilities aren't using ARC but no longer have any `-release` calls, so they leak. Crap!

(This bug doesn't appear in the 1.2 project file.)

**Comment by snej** [comment]
CBL 1.1 has the non-ARC version of those utilities, so it doesn't have the leaks. So somehow this got introduced in 1.1.1.

**Comment by snej** [comment]
I removed the `-fno-objc-arc` flags on those files in the iOS target, then rebuilt the leak sample app with the updated framework, and Instruments shows no leaks and heap usage holding steady at about 25MB during the entire replication.

I've created a new branch `release/1.1.1-leakfix` with this fix; you can build it yourself and use it. It's otherwise identical to 1.1.1. (Or you can update to `release/1.2`, which is pretty close to being finished.)

**Comment by karlbecker** [comment]
Thanks very much for this, @snej !

@jordanpwood and I want to make sure we're on a stable version because we're getting ready to release quite soon, so we'd like to wait on 1.2 until it's all done.  

Is there anyway you could make release/1.1.1-leakfix an official release in your cocoapods?  The way [the podspec is setup](https://github.com/CocoaPods/Specs/blob/master/Specs/couchbase-lite-ios/1.1.1/couchbase-lite-ios.podspec.json#L12) with a zip file (and, maybe, because the podspec file is not in the root directory of the repo), we can't do one of the usual ways of using a branch from a cocoapod, like this:
```
pod 'couchbase-lite-ios', :git => 'https://github.com/thirdiron/couchbase-lite-ios.git', :branch => 'release/1.1.1-leakfix'

pod 'couchbase-lite-ios', :git => 'https://github.com/thirdiron/couchbase-lite-ios.git', :commit => 'b1d44ce52e'
```

So... any idea how we can best use the library now with Cocoapods?  A formal release of this in Cocoapods does seem like it would be useful for more people than just us.

Thanks!

**Comment by snej** [comment]
No, sorry. Our CocoaPods don't support building from source, only downloading official builds. If you need to build an arbitrary branch from source, you'll have to do it yourself.

**Comment by karlbecker** [comment]
Roger that - could we maybe make this an official release though?  1.1.1.1 or 1.1.2 or something, since it's a pretty critical memory leak?

It would definitely be helpful, and hopefully merging to master, updating the podspec, and generating that zip isn't too tough!  If I can help, let me know.

**Comment by snej** [comment]
No, there's a lot of other work involved in an official release — it has to go through full QA, our build system has to create a Jenkins bot to build it, we have to stage it on our servers, etc. We're not going to do this when we have another release (that doesn't have the bug) coming up in a few weeks.

**Comment by karlbecker** [comment]
Okay - it's a bummer, but understand that it takes awhile.  Is there a description how to precisely make the .zip file again so we can use it with this major memory leak fixed?
Thanks!

**Comment by snej** [comment]
https://github.com/couchbase/couchbase-lite-ios/wiki/Building-Couchbase-Lite

**Comment by karlbecker** [comment]
Thanks much!

**Comment by davidquon** [comment]
@karlbecker - In cases like this we've made our own patched zip file and hosted it ourselves then pointed our `Podfile` to our URL.  This minimizes the changes to the project and you can easily go back to using the official released pod when it's ready.
