### ISSUE TITLE
Testing: Test full-text search in multiple languages

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1023]
FTS has code that's highly language-dependent, for tokenizing (breaking text into words) and stemming (removing suffixes like "-ing" or "-s".) This code lives in the `sqlite3-unicodesn` submodule. We use it for both SQLite and ForestDB.

The current unit tests only check FTS with English text. If the user's language is non-English, different tokenizers/stemmers will be used; we need to test that they'll work.

For example, non-English FTS was broken for quite a while (I'm not sure how long) because of some missing #defines to enable stemmers; see #983. We only noticed when a developer pointed it out.

**Comment by snej** [comment]
If we add support for Japanese in the future, this becomes even more important because Japanese tokenization is very difficult and will probably require integrating 3rd party libraries like MeCab. (The same is true of some other Asian languages like Thai, and I believe Chinese.)

**Comment by brendand** [comment]
I think the main issue with Asian languages (and probably others too) is words are not always bounded by whitespace. And currently FTS in SQLite is unable to do substring searches. I'm guessing that since you use similar stemmers in ForestDB that it also suffers the same problem? Or does ForestDB support the equivalent of a "like %ppl%@" which would return words like "Apple" and "application", etc. In the production version of my app I revert back to that kind of query when I detect an Asian language. But in my new Couchbase version, I'm going to have to figure out some other way to provide support for Asian languages. I can't come out with a new and improved app with less International support than my current version.

**Comment by jayahariv** [comment]
Closing 1.x issue!
