### ISSUE TITLE
Add tvOS release package

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-ios#1024]
See https://github.com/couchbase/couchbase-lite-ios/issues/918

**Comment by snej** [comment]
Dependent on #1042 — I forgot I hadn't merged the tvOS build support in the Xcode project into release/1.1 or master.

**Comment by zgramana** [comment]
Did you meant `release/1.2` above?

**Comment by snej** [comment]
Yeah.

Some build notes for Michael, since I ended up using a different/better approach than what I did for the 1.1.1-appletv branch:

* There aren't any new targets for tvOS. Instead, the iOS targets can now build tvOS too. You just need to use the `-destination` flag to xcodebuild to specify which platform to build for.
* Build output will be in `Release-iOS-universal` as usual, or `Release-tvOS-universal` for tvOS.
* There's a chance the capitalization is different in those directory names, since I ended up changing a lot of the configuration behind them ... if you get file-not-found errors on the build bot, take a look at the case.

**Comment by michaelkwok** [comment]
I will update the build script for this.  Couple questions before I make the changes.
1.  With this change, I take it we don't need to do any copying of libCBLForestDBStorage.a since it's no longer generating Release-CBLForestDBStorage-ios-universal 
2.  Do we still need to create 2 packages for iOS vs tvOS for release?

**Comment by snej** [comment]
`libCBLForestDBStorage.a` is in Release-iOS-universal.

Yes, we probably want a separate package/zip for tvOS.

**Comment by michaelkwok** [comment]
Great, thanks!

**Comment by michaelkwok** [comment]
Actually, what I meant to say was that "libCBLForestDBStorage.a is in Release-iOS-universal" now, we probably don't need to copy into "Release-iOS-universal/Extras" like we did before this change.  Let me know if I still need to copy or move it under Extras?

**Comment by snej** [comment]
In the zip archive it should be at top-level, next to the .framework, not in the Extras folder. Thanks!

**Comment by michaelkwok** [comment]
I have added tvOS to release/1.2.0 and master branch.
