### ISSUE TITLE
Bug on to-many relationships with Core Data context

### ISSUE THREAD

**Issue by cflorion** [couchbase/couchbase-lite-ios#1061]
Since we started working with Couchbase-lite-ios + CBLIncrementalStore, we've had the same problem: To-many relationships are sometimes not up-to-date in the core data contexts. We decided to add a sample app in Couchbase-lite-ios project in order to isolate this problem.

You can test demo app with https://github.com/couchbase/couchbase-lite-ios/pull/1060

You tap quickly several times on the Add button (we do batches of 10 taps), and after a few tries, the count of players on the right won't be in sync on a team.

**Comment by mastohhh** [comment]
This is related to https://github.com/couchbase/couchbase-lite-ios/issues/903

**Comment by pasin** [comment]
Thanks for the test app. I will checkout the app and look at the issue ASAP.

**Comment by mastohhh** [comment]
We tried to investigate today and we saw that the problem comes from the context stack. 

All documents are good. On the server too. We think the problem appears when the pull replication gets 2 batches of documents to close each other. 

One with a team and some players and the other with the rest of the players. And sometimes maybe, the rest of the players could be integrated before the team. That could cause this issue. 

Is it possible for 2 pull replications to be executed simultaneously? Or are they integrated in a queue?

**Comment by snej** [comment]
There are no ordering guarantees in a replication. The documents pulled from the server could be inserted into the local database in any order. In general the puller is processing docs in the order in which they were last changed on the server, but there are multiple sockets downloading documents in parallel, so you can't predict the order in which they'll be received.

**Comment by mastohhh** [comment]
The problem comes from the `_relationshipCache` used in this method :

``` objc
- (NSArray*) queryToManyRelation: (NSRelationshipDescription*)relation
                    forParentKey: (NSString*)parentKey
                        prefetch: (BOOL)prefetch
                        outError: (NSError**)outError;
```

It appears when the insertions are in 2 separate batches. For example, we create a new team with 3 players on a device. The other device gets one batch with the team and one player, and the second batch with the 2 new players. Then, the `team.players` relationship only contains the first player.

This part of the code is the problem : 

```
                SInt64 oldLastSequenceIndexed = view.lastSequenceIndexed;
                [view updateIndex];
                if (view.lastSequenceIndexed == oldLastSequenceIndexed)
                    return [result allObjects];
```

Maybe the `updateIndex` has already be done before and now this always returns `YES`

I don't know what are these indexes and what `updateIndex`does ?

**Comment by pasin** [comment]
That is the code for optimizing the performance. @mastohhh Does it help the issue if you take that piece of code out?

**Comment by mastohhh** [comment]
Yes, when we comment that piece of code, this works again.

**Comment by pasin** [comment]
I reverted that code in 1.2.0 release branch. Thanks!
