### ISSUE TITLE
External property on kCBLDatabaseChangeNotification when CBL is remote

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-ios#1100]
Steps to reproduce:

1. Device A starts the Listener to enable CBL to become a remote in a replication
2. Start a push replication from another db to the CBL Listener (the target)
3. The changes being pushed and posted in the `kCBLDatabaseChangeNotification` handler always have a `source` URL that's null and `external` is false

When the replication is CBL <-> Sync Gateway, the `external` field has the expected value but when CBL becomes the remote it's always false on the database event.

**Comment by snej** [comment]
Turns out this is already hooked up, via the `CBLRouter.source` property which gets set by `CBLHTTPConnection httpResponseForMethod:URI:`. But it only gets set if the connection is authenticated as a user. This must be because I'm setting the value of `source` to a fake URL that looks like `user:username`.

**Comment by snej** [comment]
I could use `user:` (with no username) for the anonymous case.

For bonus points I could also append the socket's peer IP address, like `user:username@66.66.66.66`.

**Comment by borrrden** [comment]
I think there is still one path that will not show up correctly.  If you put an attachment through the REST API, it will create a new revision of a document with isExternal set to NO because it takes the putRevision path instead of the forceInsert path:

https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_Router+Handlers.m#L1083
https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_Router+Handlers.m#L1039
https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLDatabase+Attachments.m#L491
https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLDatabase+Insertion.m#L207

https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_SQLiteStorage.m#L1725
AND
https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_ForestDBStorage.mm#L1090

**Comment by borrrden** [comment]
Also if a bulk docs request comes in with new_edits = true

https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_Router+Handlers.m#L285
https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_Router+Handlers.m#L867

Note that the source is passed in but never used in either case
