### ISSUE TITLE
Add Git commit hash to version string for unofficial builds

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-ios#1102]
Currently when building from source, I'm seeing this in the logs:

```
14:05:06.403| ### Couchbase Lite 1.2 (unofficial) ###
```

Would it be possible to add the git commit hash like we do on Sync Gateway?

**Comment by snej** [comment]
It's possible. It would require a shell script in the Xcode target that gets the commit and shoves it into a header. The tricky part is to avoid touching the header's mod date if the commit hasn't changed, otherwise it'll cause source files to rebuild every time. This is slightly beyond my shell-scripting fu.
