### ISSUE TITLE
Logging overhaul

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-ios#1107]

**Comment by snej** [comment]
Basically done, just not yet merged.

**Comment by snej** [comment]
_From the commit message:_

Replaced Logging.{h,m} with brand-new MYLogging.

* Log domains are checked. You have to declare a domain using
  DefineLogDomain or UsingLogDomain before logging to it, or you get a
  compile error.
* **Several domains were renamed to remove "CBL" prefixes** -- so
  CBLDatabase is now Database, CBL_Router is now Router, etc.
* Domains have a normal level, a Verbose level, and a Debug level.
  Use e.g. LogVerbose(Sync, ...) instead of LogTo(SyncVerbose, ...).
  You can still use -LogSyncVerbose YES to set verbose level.
* Warn() now logs the function name and line number of the caller.
* When logging's enabled, skipping over a LogTo to a disabled domain is
  faster.
* Generated code will be (very slightly) smaller.
