### ISSUE TITLE
ChangeTracker POST request are incompatible with CouchDB

### ISSUE THREAD

**Issue by robertjpayne** [couchbase/couchbase-lite-ios#1139]
* Version:   1.2 Release Branch
* Client OS: iOS 9.2
* Server:    CouchDB 1.6

The ChangeTracker contains a `_usePOST` ivar which by default is set to `YES`. When this is set to `YES` the changes URL is built as simply `_changes` and all of the request parameters are pushed into a JSON body for the post request.

This is however invalid as CouchDB still expects the majority of parameters to come through the URL query params not the post body.

You can reproduce this by targeting any CouchDB database and running:

```
POST /_changes
Content-Type: application/json

{"limit": 5}
```

You will notice this does not actually limit the result set at all. Where as if you run:

```
POST /_changes?limit=5
```

It will correctly capture the parameters. As far as I can tell the only valid parameter to have in the POST body is doc_ids and all others should remain in the query params of the URL

**Comment by robertjpayne** [comment]
I should say the result of this issue is that against CouchDB 1.6 the replication never ends, it continues to go forever.

**Comment by snej** [comment]
"Incorrect" is the wrong wording. Sync Gateway has supported POST to `_changes` since 2013. I'm pretty sure that predates CouchDB. I [publicly documented it](https://github.com/couchbase/sync_gateway/wiki/POST-to-_changes) in Feb 2014; in that doc it says we weren't aware of any other implementations at the time.

I don't know if the CouchDB people knew about my spec but didn't follow it, or if they just had the same idea but implemented it differently. Their [API docs](http://docs.couchdb.org/en/latest/api/database/changes.html) on it are too vague to be useful. The implementation seems weird; why would you keep most of the properties in the limited-size URL and just put one of them in the body?

Anyway, blame aside, there's an incompatibility. Right now Sync Gateway and CouchDB won't accept the same POST request, so one or the other will have to change to recognize the other's format.

**Comment by snej** [comment]
I've filed an issue against SG. My suggestion there is to parse parameters from both the URL and the request body, to handle clients using both styles of request.

In CBL, similarly, we can put the parameters in both locations (except the filter params.) I think that'd be quite easy to implement.

**Comment by robertjpayne** [comment]
@snej Ah yea this makes a lot more sense. Is there any reason the `filter` params cannot also be sent in both?

CouchDB is definitely more likely the fault here, it's very strange they don't take all the params from a POST request.

**Comment by snej** [comment]
>Is there any reason the filter params cannot also be sent in both?

Well, the whole reason for using a POST is to make more room for those filter parameters, because they can get arbitrarily large, too large to reasonably fit in a URL. (There's no explicit maximum length for URLs, but various client libraries, proxies, etc. will barf if they get URLs beyond a certain length, like a few kbytes.)

**Comment by snej** [comment]
OK, I have a fix. Tested it with a local CouchDB 1.6.1; CBL can pull a 5000-document db from it with no problems. @robertjpayne, it'd be great if you could try this fix with your own app & server. (You should be able to cherry-pick it onto the `release/1.2.1` branch, to avoid destabilizing your app with all the other stuff on the dev branch.)

**Comment by martypenner** [comment]
Can confirm I experienced the same issue, and this resolved it.

**Comment by snej** [comment]
Thanks!

**Comment by snej** [comment]
Merged to dev branch; closing.

**Comment by blairio** [comment]
AFAICT  this fix has not been released yet. Is there an interim workaround for this issue when using the latest CBL (1.2.0) and CouchDB 1.6.1?

Thanks.

**Comment by snej** [comment]
I can cherry-pick the fix to a release branch. I believe it's too late to add it to 1.2.1, but I can start a new branch if necessary. I'll try to get to this by EOD.

**Comment by snej** [comment]
OK, it's pushed to a new `release/1.2.2` branch as commit 80901c33. (Don't take this as confirmation of a 1.2.2 release; I just needed to start a new branch because 1.2.1 is frozen already.)

**Comment by blairio** [comment]
Thanks for this @snej 
I am assuming that I need to build this myself and I can't install couchbase lite as a pod anymore?
ie. 
`pod "couchbase-lite-ios", :git => "https://github.com/couchbase/couchbase-lite-ios.git", :branch => "release/1.2.2"`
will not work.

**Comment by snej** [comment]
I don't know that much about CocoaPods — @pasin is our local expert — but last I heard, our podspec just downloads a binary build from couchbase.com, instead of compiling locally. So that wouldn't work. Carthage, on the other hand, directly checks out a branch and builds it, so that would probably work.

**Comment by pasin** [comment]
@snej is correct about couchbase-lite-ios CocoaPods andCarthage.

**Comment by protogrid** [comment]
Am I right in assuming that this issue is resolved with commit 80901c3, except for filter params?

**Comment by hinesmr** [comment]
I'm having exactly this problem on Android (not iOS) using couchdb 1.6. I have stored some filter parameters via `pull.setFilterParams(params);`, but they don't show up in the URL. 

Was the android version of couchbase lite never patched? I'm not seeing anything relevant in the ChangeTracker code.

**Comment by snej** [comment]
>Is there a branch/commit which sends all "CBL.filterParams" in the URL query instead of using the POST body?

I'm confused. The reason for using POST is so there's unlimited room for filter parameters like docIDs. Putting the filter params in the URL would negate that.

**Comment by snej** [comment]
>Was the android version of couchbase lite never patched?

I'm not sure. You should ask on the forum or mailing list, or file an issue against couchbase-lite-java-core.

**Comment by hinesmr** [comment]
@snej ^^^^ You need to read the rest of the issue above. This has already been discussed.

**Comment by hinesmr** [comment]
@snej I did send a mail to the list ---- but no response so far. I'm willing to open an issue or even submit a patch if someone would actually accept the patch.

I want to make sure it won't get shot down before I even submit it.

**Comment by snej** [comment]
>You need to read the rest of the issue above. This has already been discussed.

I am familiar with the issue, thanks. Putting the filter parameters in the URL would defeat the purpose of using POST, since it's those parameters that can become too large to fit in the URL. (The original post mentions `doc_ids`, but this isn't really a hardcoded parameter, just the specific one used by the `_doc_ids` filter.)

**Comment by snej** [comment]
Could someone get some definitive info about how CouchDB interprets `POST /db/_changes`? They're incompatible with our implementation (which predates theirs), the documentation on their site is too vague to be useful, and I've gone around this issue twice already trying to be compatible.

**Comment by rajasaur** [comment]
We are experiencing the same problem(FilterParams being ignored on CouchDB) on upgrading to CBLite-Android (1.3.x from 1.1.1) and see that CouchDB is not picking up those changes.  

@tleyden @hideki : Any chance we can allow for usePOST=false (as currently the only code that can do that is from the unit tests), which will allow the filterParams to go through as GET?

I understand that the main purpose is to avoid long GET urls (for e.g. our case may have a very long filterParams) but unfortunately, if the server isnt budging, then I think the client needs to be adjusted accordingly

**Comment by snej** [comment]
The problem now isn't that CouchDB isn't budging, it's that they haven't documented how it behaves. If someone who knows Erlang wants to dive into the source code and reverse-engineer their exact behavior, I'll implement our client code compatibly. But I don't want to just blindly guess again.

**Comment by skyred** [comment]
There is a fix in https://github.com/couchbase/couchbase-lite-android/issues/942#issuecomment-295846973 , and I suggested a way moving forward in https://github.com/couchbase/couchbase-lite-android/issues/942#issuecomment-464362168
