### ISSUE TITLE
Need API to add attachments with -putExistingRevisionWithProperties:... method

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1195]
The new-for-1.3 method `-[CBLDocument putExistingRevisionWithProperties: revisionHistory: fromURL: error]` doesn't have a good way to add attachments. Currently they have to be inline, i.e. with every attachment having a `body` property whose value is a base64 string.

A couple of ideas:

* Allow the `body` property value to be NSData or CBLAttachment
* Add an `attachments:` parameter that's an NSDictionary mapping attachment names to NSData or CBLAttachment. This would be nice in that you wouldn't have to mess with the revision body to splice the bodies into it.

**Comment by snej** [comment]
The problem was pointed out on [this thread](https://groups.google.com/d/msgid/mobile-couchbase/ab79de07-607a-4633-bd14-573def2c1318%40googlegroups.com?utm_medium=email&utm_source=footer).

**Comment by brendand** [comment]
Just another idea.

What about recognizing the _attachments property in the document properties passed in and also have a contentFolderURL parameter where you can pass in the URL to a folder that has all of the attachments? Then internally you can determine the .blob file names from the attachments digests and append that to the contentFolderURL in order to set the attachment on the current revision?

Although I'm not sure if this API is supposed to be for externally (non-CBLDocument) generated properties or properties generated from a CBLDocument. If external, then maybe just an NSArray of NSDictionary with the name, contentURL, and mime type.

Just thinking out loud.

**Comment by snej** [comment]
I'd like to make this work with revisions & attachments received from anywhere (e.g. maybe some alternative replicator), not just from another CBL database, so I don't want any dependencies on the specific file naming in CBL.

**Comment by brendand** [comment]
Excellent. That's great to hear. A much better solution.

So I would think just a dictionary keyed on attachment name, with sub-dictionaries containing the content URL or content NSData and mime type? I don't know how the idea of passing in CBLAttachments would work. I don't think you can directly create CBLAttachment objects can you? They're created by calling the setAttachment: methods on CBLModel and CBLNewRevision I believe.

It'll be great to have this expanded API.

**Comment by snej** [comment]
The document JSON/NSDictionary would still contain the `_attachments` property with the metadata. The extra parameter would just be an NSDictionary whose keys are filenames and values NSData. (It could also allow NSURL values, pointing to files containing the data.)

You're right about the difficulty of creating CBLAttachments. And those contain metadata too, so they'd be redundant with the `_attachments` property.

**Comment by brendand** [comment]
For sure. Right now I'm removing the _attachments property from the JSON before I create my document, then I'm looping through them, creating revisions, and adding them back. But we've discussed that already on the Google group. But it would be great to just leave them in there and let the API deal with it. But as you've mentioned, the API shouldn't assume how the files on disk are named, since right now they're SHA-1 encoded. I'm manually decoding them right now and then finding them in the right place on disk.

**Comment by snej** [comment]
I have an implementation in a PR. Could you try it out, to see if it works and has the functionality you need?

**Comment by brendand** [comment]
I'm not sure if I should have commented here or on the PR, so I put them on the PR.

**Comment by brendand** [comment]
I have a related question to this new method that's not directly relevant to the PR, so I'm commenting here instead. 

If I import these documents, then delete them, then re-import them, they seem to not show up in my app. I'm assuming that's because once marked as deleted, if you re-import the same documents, they stay marked as being deleted?

Do I need to purge the database of all deleted documents before I can re-import them?

Or perhaps when I'm creating the CBLDocument as `[database documentWithID:docId]` then maybe I can mark them as not being deleted anymore?

**Comment by snej** [comment]
Merged to dev branch; closing.

**Comment by snej** [comment]
>If I import these documents, then delete them, then re-import them, they seem to not show up in my app.

That's because you're just restoring the revision prior to the delete. But the deletion is still there and happens later (it's a child of the prior revision) so it's the current revision. So you used to have rev tree A-B-C, made a copy of C, deleted the doc to arrive at tree A-B-C-D, and then re-imported C, which is basically a no-op.

You'd have to purge the document before re-importing it. Then the deletion no longer exists.

**Comment by brendand** [comment]
Perfect!

All I had to do was:

```
			if (newDoc.isDeleted) {
				[newDoc purgeDocument:&error];
			}
```

And now it works.

Thanks!
