### ISSUE TITLE
Replication rejects attachments generated by PouchDB with revpos:0

### ISSUE THREAD

**Issue by shadzik** [couchbase/couchbase-lite-ios#1200]
```
16:31:20.223‖ WARNING: CBLRestPuller[https://server:443/user-62356431623932312d323233652d343935612d623834622d663439666462373234356336]: Revision {section_image-7d5198c2-5ddf-5405-9835-e980b634535c #2-8145a6217ced16862b43577c204d2ac8} has invalid attachment metadata: {
    "image.png" =     {
        "content_type" = "image/png";
        digest = "md5-Hke94Wxx368Us7xYprTmIw==";
        follows = 1;
        length = 101033;
        revpos = 0;
    };
}
```

The issue seems to be revpos not having a proper value, value is 0 and should be 2 in this case.
But anyway i would expect this doc to be synced.

--------
* Version:  1.2.0
* Client OS: iOS 9.3
* Server:  Apache CouchDB 1.5.0

**Comment by jo** [comment]
I can confirm that the abovementioned doc has been successfully replicated using CouchDB 1.6.1 replicator.

**Comment by jo** [comment]
**Some additional info**

The warning is triggered here: https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLRestPuller.m#L711-L714

We don't know how the doc with the bogus revpos has been created yet.

**Comment by jo** [comment]
Why is `revpos === 0` [considered invalid](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_Attachment.m#L173-L174)?

**Comment by snej** [comment]
`revpos` indicates the generation number (numeric prefix in the revID) at which the attachment was last altered. Generation numbers start at 1 when a new doc is created, so a `revpos` of 0 refers to an invalid generation number.

(I believe the sanity check will accept an attachment with _no_ `revpos`, but an explicit value of 0 as in this case indicates something is wrong.)

**Comment by jo** [comment]
While I totally agree that revpos 0 does not make any sense at all this behaviour breaks replication with a CouchDB, which has docs with attachments generated by PouchDB.
What would be the impact if CBL would consider revpos 0 as valid like it does with missing revpos?

**Comment by snej** [comment]
We can figure out a workaround — treating `revpos:0` as equivalent to a missing `revpos` seems reasonable. 

But I'm curious why this is only happening now, when Couchbase Lite has been interoperating with CouchDB since 2011. It sounds like it's PouchDB that generates the revisions with `revpos:0`, and CouchDB is just the intermediary? And it looks like the PouchDB commits referenced above fix the issue?

**Comment by jo** [comment]
Hi @snej, thanks for the discussion!

Yes, the `revpos: 0` entries are indeed caused by PouchDB, or at least this happens during standard CouchDB replication of documents created by PouchDB. PouchDB itself ignores `revpos` atm and I am indeed working on [a pull request to bring `revpos` support to PouchDB](https://github.com/pouchdb/pouchdb/pull/5037).

In https://github.com/pouchdb/pouchdb/issues/3930 there is also a discussion about this topic btw.

But even if PouchDB will support `revpos` in the future there will be still documents in place which are created using current or older PouchDB versions. I think its a good idea to not break replication of those docs. And CouchDB itself is also a bit more relaxed in this case and is able to replicate such docs.

**Comment by jo** [comment]
Thanks a lot!
