### ISSUE TITLE
CBLModel: add many-to-many support, for inverse relations

### ISSUE THREAD

**Issue by dangthaison91** [couchbase/couchbase-lite-ios#1206]
Hi,

I'm finding the way to find inverse a to-many relation. Just read #606 and also Wiki about Inverse Relation but seem that it doesn't fits my situation.

I have Customer and CustomerGroup class. Customer class have a array of CustomerGroup. How can i get all Customer that belong to CustomerGroup.

```
class Customer: BaseCBLObject {
    @NSManaged
    var groups: [CustomerGroup]

    class func groupsItemClass() -> AnyClass {
        return CustomerGroup.self
    }
}
```

```
class CustomerGroup: BaseCBLObject {
    @NSManaged
    var allCustomers: [Customer]

    class func allCustomersItemForClass() -> AnyClass {
        return Customer.self
    }

    class func allCustomersInverseRelation() -> String {
        return "groups"
    }
}
```

Currently if i have CustomerGroups instance `group` then get all customer by call `group.allCustomers` or explicit call `group.findInverseRelation:fromClass` it will return empty array.

Thanks

---
- Version:   1.2
- Client OS: 9.x
- Server:    4.0

**Comment by snej** [comment]
Hi! Please ask your question on the [Couchbase web forum](https://forums.couchbase.com/c/mobile) or the [Couchbase Mobile mailing list](https://groups.google.com/forum/#!forum/mobile-couchbase). We use Github issues only for bug reports and feature suggestions. Thanks.

**Comment by dangthaison91** [comment]
Sorry, i was reply a question to this groups:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/mobile-couchbase/inverse/mobile-couchbase/QTurL1nVxLs/iHmkJiy8k2EJ

**Comment by snej** [comment]
You’ve got a bidirectional many-to-many relation. That’s not supported yet.

Specifically, the inverse-relation code in CBLModel assumes the other class (the one with the forwards relation) has a singular property (a string) that points to the destination class, not a to-many property (an array).

It wouldn’t be terribly difficult to add support for this; it just hasn’t been done.  I’ll reopen the issue you opened on Github, since it turns out to be a feature request not just a question :)

**Comment by snej** [comment]
It might just require changing the map function of the auto-generated view, so that it can handle an array value of the forward-relation property. I haven't gone back to look at the code yet, but I'm assuming it ignores the property value if it's not a string. Instead if it's an array it should just iterate over it, emitting a key/value for every string. 

You could try making this change yourself, in CBLModel.m, then submitting a PR.

**Comment by jayahariv** [comment]
Closing 1.x issue!
