### ISSUE TITLE
'App Transport Security policy requires the use of a secure connection' when replicating between LiteServ Mac OSX and sync_gateway

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1264]
--------
* Version:   N/A
* Client OS: Mac OSX 1.3.0-14 LiteServ
* Server:    sync_gateway 1.2.1-4

```
11:04:25.776‖ CBLRemoteJSONRequest[POST http://192.168.33.10:4985/db/_revs_diff]: Got error NSURLError[-1022, "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.", <http://192.168.33.10:4985/db/_revs_diff>]<--CFCFNetworkError[-1022]
11:04:25.776‖ Sync: CBLRestPusher[http://192.168.33.10:4985/db] Progress: set error = NSURLError[-1022, "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.", <http://192.168.33.10:4985/db/_revs_diff>]<--CFCFNetworkError[-1022]
```

I am hitting the above errors when setting up a push replication from LiteServ Mac OSX and sync_gateway. Perhaps a missing info.plist setting http://stackoverflow.com/questions/32631184/the-resource-could-not-be-loaded-because-the-app-transport-security-policy-requi ?

**Comment by snej** [comment]
I think the ATS policy has changed because 1.2 was building against an older Mac OS SDK, so the OS wasn't enforcing the new policies.

The Info.plist for LiteServ is configured to allow arbitrary outgoing connections to localhost:
![ats](https://cloud.githubusercontent.com/assets/43241/15615588/2943f160-23f4-11e6-8443-8b1e606ceeb2.jpg)
If you want to extend that to other servers, you'd need to edit the Info.plist in the app bundle. (If you're using the LiteServ tool, I don't think you can modify the Info.plist because it's embedded in the binary file.)

**Comment by snej** [comment]
I think I'm going to close this as Behaves Correctly because we do want to abide by ATS requirements by default. Devs who want to use LiteServ to pull from remote servers can edit the plist. (For security reasons Apple deliberately provides no mechanism to change these security settings at runtime.)
