### ISSUE TITLE
CBLUITableDelegate updateFromQuery

### ISSUE THREAD

**Issue by azouts** [couchbase/couchbase-lite-ios#1284]
Couchbase lite should call UIKit on main thread. tableView.reloadData for example in CBLUITableDelegate.

I had to implement it in order for it to work correctly.

    func couchTableSource(source: CBLUITableSource, updateFromQuery query: CBLLiveQuery, previousRows: [CBLQueryRow]) {
        dispatch_async(dispatch_get_main_queue()) { 
            self.tableView.reloadData()
        }
    } 
--------
* Version:   1.2.1
* Client OS: iOS

**Comment by snej** [comment]
CBLUITableSource should only be used on the main thread (because the table view will call it directly.) That means it needs to be used with CBL objects running on the main thread.

It sounds like your CBL objects are running on a background thread/queue. In that case you'll need to se up another CBLManager on the main thread, and create the query for the table source from it.
