### ISSUE TITLE
LiteServ: Add option to open/create encrypted databases

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1287]
--------
* Version:   N/A
* Client OS: Mac OSX 1.3.0
* Server:    N/A

`[--storage <engine>]     Set default storage engine: 'SQLite' or 'ForestDB'`

Is is possible to add SQLCipher and ForestDB + Encryption?

**Comment by Chavenay** [comment]
Improved database encryption - AES-256 on-disk encryption with your 
choice of provided storage library: SQLCipher or ForestDB

**Comment by snej** [comment]
We can add a flag to define the password, but it would need to be database-specific, something like `--db-password <dbname>=<password>`, which could be repeated multiple times for different databases.

However, putting passwords in command-line args is discouraged for security reasons because the command line is exposed by tools like `ps`, written to the shell's history buffer, etc. But on the other hand if we have LiteServ prompt for the password (as curl does), it makes it harder to run programmatically. What do you think?

**Comment by sethrosetter** [comment]
How concerned are we with security? Maybe we could fork LiteServ and have a testing focused build. That way, perhaps we do care as much about security if we are only using it to run tests. I think the interactive approach would definitely be difficult going forward with automation.

**Comment by snej** [comment]
We can put a big warning in the usage info that using the password flag is insecure. I just felt compelled to bring it up, as a part-time tinfoil-hat security guy.

Another possibility is to have the flag give a path to a config file that lists database passwords by name. Something like `--passwords ~/liteserv_passwd.json`. Then you just have to make sure that the permissions of that file are locked down, if you care.

**Comment by sethrosetter** [comment]
I like the config file approach a lot.

**Comment by borrrden** [comment]
Guys, this options is already on LiteServ ?

https://github.com/couchbase/couchbase-lite-ios/blob/dev/Listener/LiteServ.m#L181
