### ISSUE TITLE
Support setting revs_limit via REST in LiteServ

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1291]
--------
* Version:   N/A
* Client OS: 1.3.0-X
* Server:    N/A

**Comment by snej** [comment]
Implemented on dev branch. Instead of a REST API I added a new flag for LiteServ: `--revs_limit 1000` will set the default maxRevTreeDepth for databases to 1000. This affects all databases that have not explicitly had their `maxRevTreeDepth` property altered in the native API.

To help verify this, when you do `GET /db` in the REST API, the response includes a new property `revs_limit` that shows the current value for that database.
