### ISSUE TITLE
Support building from source with CocoaPods (not just downloading binaries)

### ISSUE THREAD

**Issue by skela** [couchbase/couchbase-lite-ios#1310]
An entry like this:
pod 'couchbase-lite-ios', :git => 'git@github.com:couchbase/couchbase-lite-ios.git'
In my Podfile gets the following error message when I try to run `pod update`

[!] Unable to find a specification for 'couchbase-lite-ios'.

---
- Client OS: OSX 10.11.5
- Cocoa pods version 1.0.1

**Comment by pasin** [comment]
@skela At this moment, we only have cocoapod linked to the released binary. Alternatively you can use [build](https://github.com/couchbase/couchbase-lite-ios/wiki/Building-Couchbase-Lite) the binary yourself or use [Carthage]( https://github.com/Carthage/Carthage).

**Comment by skela** [comment]
Yes I know people sometimes do that, but there's no harm in also allowing people to link with the github repo itself for maximum flexibility.

**Comment by skela** [comment]
I'm closing this, Carthage is far superior to CocoaPods anyway.

**Comment by zygoat** [comment]
Excuse me? That sounds like a personal opinion, rather than a sound technical or policy explanation. It does not help address the problem.

**Comment by skela** [comment]
Well I raised it, and it’s had not movement since like forever. Did you need cocoa pods then?

**Comment by skela** [comment]
I'll reopen it if you want, I don't mind, it just looks like they've abandoned providing this via CocoaPods anyway. :)

**Comment by zygoat** [comment]
Pardon me; I misread the thread, and was too harsh in my reply. Somehow I thought you were a Couchbase dev closing the thread, and not the person who started it! My apologies.

I started following this issue some time ago when it was raised, because indeed I use CBL via CocoaPods at my day job, and have been hoping that it would become properly available as source via CocoaPods. (In fact, we've stayed pinned at 1.2.x for some time now because of this, which is obviously not ideal.)

My understanding is that CBL 2.0 is supposed to address part of my problem by distributing as a dynamic library rather than a static one, but nonetheless, a dynamic lib source build via CocoaPods would be ideal.

**Comment by skela** [comment]
No worries, I'll reopen it, I don't think it hurts to have both. But keep in mind you can have both CocoaPods and Carthage stuff in the same workspace :) That's what I do and with Carthage, in addition it creates a framework for you from source that way too.

**Comment by pasin** [comment]
The reason that the issue has no progress is that compiling CBL source (by specifying the source code files to Cocoapods) is not practical for CBL due to dependency complication.

We may do something similar to what we are doing with 2.0 is to generate the framework files during the Cocoapods prepare_command phase. We have a plan to move away from building a static library for iOS. When we start to do that, it probably a good time to make the change.

**Comment by johnw123** [comment]
If you’re looking for <a href="https://www.etech7.com/managed-it-services-in-nyc">Managed IT Services in NYC</a>, Etech7 is the right place for you. I’m a dummy in IT sphere, so all the time I need a good company to solve my IT problems. Finally I’ve found Etech7 and  when I need <a href="https://www.etech7.com/it-consulting">IT Consulting</a>, I’ll definitely call them.

**Comment by pasin** [comment]
I'm closing this as we don't plan to do this for 1.x.
