### ISSUE TITLE
Need to close all other db handles before rekeying

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1343]
If we change the encryption key of a database while there are any other handles open on it (i.e. other CBLDatabase instances), those handles will be confused because the file's been encrypted without their knowledge. It looks like this can lead to file corruption (see #1233), and it will definitely cause errors any time the other handles try to read or write.

For 1.3 I've added a check that causes rekeying to fail if more than one handle is open. That's not a good fix, though (it's awkward for developers.)

What we need to do is tell all the other CBLDatabases to close their handles, then do the rekeying, then reopen all the handles.

**Comment by brendand** [comment]
Is there a possible better fix for this Jens? I'm having a devil of a time trying to make it work right now.

I'm closing my backgroundManager, encrypting with my main CBLManager, telling the background database to close, then encrypting. But my database files are coming out malformed. To me it still looks like the WAL file is not encrypted since there's plain text in there.

Here's the code I'm using to encrypt:

```
	[self.databaseDocument.backgroundCouchManager close];
	[self.databaseDocument.couchManager backgroundTellDatabaseNamed:self.databaseDocument.documentID to:^(CBLDatabase * _Nonnull database) {
		BOOL success = [database close:&error];

			dispatch_async(dispatch_get_main_queue(), ^{
				
				BOOL didEncrypt = [weakSelf.databaseDocument.couchDatabase changeEncryptionKey:[weakSelf.databaseDocument masterKeyFromKeychain] error:&error];

... and so on.
});

```

The moment I call changeEncryption key, I get the following error in the log:

```
2016-08-05 14:36:31.879 Tap Forms[438:196139] CBLBlobStore: encrypting /private/var/mobile/Containers/Data/Application/1CF37399-0A4D-4254-A9D9-6025635B40F9/Documents/Test.tapforms/db-c650e3f6a3a74f4381da867475b9ad87.cblite2/attachments
2016-08-05 14:36:31.879 Tap Forms[438:196139]     No blobs to copy; done.
2016-08-05 14:36:31.927 Tap Forms[438:196139] WARNING: CBL_SQLiteStorage: database is unreadable (err 26) {at -[CBL_SQLiteStorage decryptWithKey:error:]:265}
2016-08-05 14:36:31.928 Tap Forms[438:196139] WARNING: MYAction: Error cleaning up step #3: Error Domain=CBLHTTP Code=401 "unauthorized" UserInfo={NSLocalizedFailureReason=unauthorized, NSLocalizedDescription=unauthorized} {at -[MYAction cleanUp:]:
```

Then when I close the document and try to open it again with the correct encryption key, I get the following error:

```
2016-08-05 14:48:04.631 Tap Forms[438:196139] WARNING: CBL_SQLiteStorage: database is unreadable (err 26) {at -[CBL_SQLiteStorage decryptWithKey:error:]:265}
```

Even though I am providing the correct key.

When I look at the .wal file, it has some plain text in it, but the database file is encrypted. If I delete the .wal file, I can open the database with the right key.

Something is holding on to that .wal file and not encrypting it.

I remember switching from WAL to DELETE mode in the database and that fixed it for me. But I saw you mention that WAL is required now and that you got a 2.5x boost in performance with it.

**Comment by brendand** [comment]
Would there be any problems with sync or anything like that if I switch to using DELETE for the logging support? I just did that to fix my encryption problems. Now the encryption works, but your comment in your code says that WAL is required for concurrency to function.

Also, when I call changeEncryption the first time, I get the following error:

```
2016-08-05 16:28:39.500 Tap Forms[469:213620] Error calling sqlite3_step (1: database schema has changed) SQLITE_ERROR
2016-08-05 16:28:39.500 Tap Forms[469:213620] DB Query: SELECT sqlcipher_export('rekeyed_db')
2016-08-05 16:28:44.799 Tap Forms[469:213620] Error encrypting: Error Domain=SQLite Code=1 "database schema has changed" UserInfo={NSLocalizedDescription=database schema has changed}
```

Yet the second time I call it it works. Strange.

I released my Tap Forms update and this issue is causing a lot of problems with my customers. I thought I had it working before, but they managed to find a way to break it.

**Comment by brendand** [comment]
Jens, do you have any recommendations on how I can get past this problem? My users are ending up with corrupted databases. I tried switching to the DELETE log mode, but if the user had WAL mode before with an encrypted database, it also ends up corrupting their database. So that was a real bad move.

**Comment by brendand** [comment]
Ok, I think I've figured out a way to make it work reliably now. The hack to close the background database was giving me nightmares :)

So what I've come up with for my app at least is the:

```
[self.databaseDocument stopCloudantSync];
[self.databaseDocument.peerManager stopAllPeerSyncing];			
[self.databaseDocument.backgroundCouchManager close];
[self.databaseDocument.couchManager close];
[self.databaseDocument openDatabase];
NSError *error = nil;
BOOL didEncrypt = [weakSelf.databaseDocument.couchDatabase changeEncryptionKey:newKey error:&error];
```

So essentially I stop syncing, then close the couchbase managers, both my background one and my main thread one (`couchManager`) then I open the database again and then encrypt it. What this does is it causes the background database connection that the couchManager uses for syncing to be closed. I no longer get the schema changed error and it is no longer corrupting my database after I encrypt.

This also means that I can continue to use WAL mode logging. Now to test on OS X to make sure it still works there. These tests were with iOS.

**Comment by brendand** [comment]
ARGH! Nope. It turns out what I was thinking was all working was because I was working with databases that had already been created with DELETE logging and not WAL logging. When I created a brand new database and it defaulted to WAL logging, I can not encrypt the database file. It ends up corrupting it. Now I don't know what to do. I'm stuck.

**Comment by brendand** [comment]
My tests were primarily on iOS, but it's also happening on OS X too. Is there anything that I can do? @snej ?

**Comment by brendand** [comment]
So I'm digging into the CBL code some more and what it's doing is it's generating a unique temporary path to a file using `CBLCreateUUID()`. That's a single file. When this code is executed:

```
 if (newKey)
                sql = $sprintf(@"ATTACH DATABASE ? AS rekeyed_db KEY \"x'%@'\"", newKey.hexData);
            else
                sql = @"PRAGMA main.wal_checkpoint(TRUNCATE); ATTACH DATABASE ? AS rekeyed_db KEY ''";
            return [self checkUpdate: [_fmdb executeUpdate: sql, tempPath] error: outError];
```

a single encrypted file is created. Then it's moved to the `_fmdb.databasePath` which is the path to the db.sqlite3 file.

For example in my app here's the from and to paths:

```
move from

tempPath: /var/folders/gy/pdjjqyr88xg9gn001s6sl56h0000gn/T/com.tapzapp.tapforms-mac/--B3ygPUHqs7oXoOfcHTU7j

dbPath: /Users/brendan/Library/Containers/com.tapzapp.tapforms-mac/Data/Documents/temp.tapforms/db-3988c51120a042079b310c3c2e16218f.cblite2/db.sqlite3
```

But that .cblite2 folder has the .wal and .shm files still from the previous database.

Now when CBL re-opens the database, there's corruption and an error is thrown and the user's database is toast.

That's what I'm seeing right now.

**Comment by brendand** [comment]
What's a bit strange to me by stepping through the code in sequence, the move is happening before sql statement is being executed, even though the code to move appears after the code to rekey in the source.

**Comment by brendand** [comment]
So I've found if I modify CBL_SQLiteStorage class with the following code, I can get it to work:

```
[action addPerform:^BOOL(NSError **outError) {
	NSString *sql = @"PRAGMA main.wal_checkpoint(TRUNCATE);";

	return [self checkUpdate: [_fmdb executeUpdate: sql, tempPath] error: outError];
} backOutOrCleanUp:^BOOL(NSError **outError) {
	return dbWasClosed;
}];
```

I put this just before this code:

```
// Create & attach a temporary database encrypted with the new key:
        [action addPerform:^BOOL(NSError **outError) {
            NSString* sql;
            if (newKey)
                sql = $sprintf(@"ATTACH DATABASE ? AS rekeyed_db KEY \"x'%@'\"", newKey.hexData);
            else
                sql = @"ATTACH DATABASE ? AS rekeyed_db KEY ''";
            return [self checkUpdate: [_fmdb executeUpdate: sql, tempPath] error: outError];
        } backOutOrCleanUp:^BOOL(NSError **outError) {
            return dbWasClosed ||
                        [self checkUpdate: [_fmdb executeUpdate: @"DETACH DATABASE rekeyed_db"]
                                    error: outError];
        }];

```

However, after the database is closed and then opened in the cleanup code, I'm getting errors about not being able to index my views and such. So I'm still trying to figure out all that.

**Comment by pasin** [comment]
I remembered attempting to close all of the background databases to have the WAL file merged into the the main database file but my attempt didn't success. IIRC, closing the manager did the trick. What if closing the manager first, reopen the database, and rekey without starting replication and live query?
