### ISSUE TITLE
Flaw in permissions logic

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1372]
In the situation where a user attempts to modify a document via the REST api, that they do not have permission to modify. The modification is rejected by the sync-function, but the user isn't notified of the failure in any way.

Consider a chat room, where _owners_ can change the name of the chat room. So imagine _owner_ Bob attempts to make a name change, first checking that they he is an _owner_ (which he is). Bob submits the name change, while at the same time Jim removes Bob from the list of _owners_. If Jim's change makes it to the server first then Bob's change fails a `requireUser()` check in the on the _owners_ field and gets rejected by the sync-funcation. In this situation both clients did their job correctly but the error still happens. And now Bob has an inconsistent document, and it will be inconsistent indefinitely, with no indication at all that there is a problem. He has a different view of the world to everyone else now.

See:  https://forums.couchbase.com/t/question-about-conflicts/7211/14

**Comment by snej** [comment]
We do need better feedback about docs being rejected by the server, but I don't think the problem's as bad as you're presenting it.

Bob will see a conflict in that document after he receives Jim's change from the server. When merging the conflict he'll see that he's incorporating a change that removes him as an owner, which invalidates the other branch (the change he made locally.) Presumably he'd give up his change.

**Comment by npomfret** [comment]
I believe he won't see a conflict until the document gets edited, no?

**Comment by snej** [comment]
The conflict will be in the local database as soon as the pull replicator catches up, i.e. hopefully within a few seconds. At that point the app can detect it by monitoring database-change notifications, or by running an all-docs query using the conflicts-only mode.

**Comment by npomfret** [comment]
We've discussed this - I thought we came to an agreement?  Anyway, I've just tried it by forcing my sync function to reject all updates. I can see in the client's logs that the update was refused during sync. My client now has a copy of the edited document that the sync function refused, there's no evidence of a conflict (using `.../_all_docs?only_conflicts=true&conflicts=true&include_docs=true`).  The server has revision 1 and the client has revision 2.  

I suspect if someone else were to edit the document that you'd be right and a conflict  would appear, but only then.

**Comment by snej** [comment]
In general you're correct — if a client pushes a doc that's invalid according to the sync fn, it'll be rejected without notice. The general response to that is that this is an app error: your client validation should match the sync function so you don't create invalid documents.

The example you gave above is problematic in that the revision the client creates _is_ valid by the server's rules, but it becomes invalid because of a different change that gets pushed to the server first. So the client cannot avoid its revision being rejected. However, this also creates a conflict on the client because the Bob's client will pull the other revision from Jim's client that did get accepted by the server — now it has both Bob's change and Jim's change and has to merge them, at which point it can figure out that Bob's change is no longer possible.

**Comment by npomfret** [comment]
Agreed, in my example thats the case. 

If the permission change wasn't as a result of 2 people editing the same document, would that result in this problem?

**Comment by snej** [comment]
Looking back at the forum thread, I ended up musing about adding API to CBLReplication to inform the app about docs that failed to be pushed, i.e. were rejected by the sync function. That's probably the concrete step to be taken here. Since it's a cross platform change, I'll add it to our (internal) API issue list.

**Comment by snej** [comment]
Tracking it as https://github.com/couchbaselabs/couchbase-lite-api/issues/163
