### ISSUE TITLE
Support for background fetch in iOS 7

### ISSUE THREAD

**Issue by lightandshadow68** [couchbase/couchbase-lite-ios#138]
I'd love to see CBL support the new background fetch feature in iOS7

**Comment by pasin** [comment]
@jamiltz posted a blog that uses CBLReplication to fetch data in the background fetch.
http://blog.couchbase.com/ios-background-fetch-to-sync-hacker-news-stories

**Comment by pasin** [comment]
Currently CBLReplicator (one-shot) can be used in the iOS background fetch without problems.
@zgramana what would be a scope of this feature?

**Comment by snej** [comment]
It looks as though this is something an app developer would need to add, since the hook has to go in the app delegate class. [This snippet from James' app](https://github.com/jamiltz/HackerNewsSync-BackgroundFetch/blob/master/HackerNewsSync%2BBackgroundFetch/HackerNewsSync%2BBackgroundFetch/AppDelegate.m#L32-L53) is a good example. So maybe this just goes into the iOS documentation, instead of being a change to CBL itself?

Somewhat more complex is background fetch that's triggered by a push notification. Do we have any samples/docs showing how to send iOS push notifications from SG?

**Comment by zgramana** [comment]
@pasin the big challenge is when NSFileProtectionComplete is set. That will kill any chance (currently) of doing a background fetch successfully, since the cblite files will be encrypted and unusable.

There is at least one way for us to support at pull replications of this kind. First, we'd have to store the SG URL and the last sequence id in NSUserDefaults when the app is suspending (there's a short grace window before we're locked out of the database). When the background fetch delegate fires,  we make a direct NSURLRequest to SG with since=[from user defaults]&include_docs=true, and store the results in a new file, which is permitted. When the user unlocks the phone and the app resumes, we can then process the pre-fetched changes feed JSON.

As far as push notification integration with SG, @tleyden used the F/OSS Uniqush service via a changes worker to do that: https://github.com/tleyden/officeradar-appserver. This part is even easier now with webhooks.

**Comment by pasin** [comment]
@zgramana, I think we would need to discuss more about the solutions, and your comment above is a good starting point for discussion.

1. A couple of few things that are not included in the changes feeds but are required for replication so we may need to prefetch them also:
- Revision history
- Attachments

2. Mapping between last sequence and the remote URL might not be enough. For example, if an application having two pull replication to the same URL but different channels would have two last sequences mapped to the same URL. Currently a last sequence id is mapped to a remote checkpoint id which is calculated from the database local UUID, remote URL, and some other sync parameters.

**Comment by skela** [comment]
Is there a way to achieve this in the current lite versions of couchbase-lite? Or any guides to that effect?
Basically hoping to get it to pull and push stuff. @ntodd 's looks cool, but I dont recognise the classes there.

**Comment by snej** [comment]
The example ntodd posted just uses the regular iOS background-task API to perform replication inside the app. It's not using background networking.

In general, we can't do replication with background networking because it's much more than just a single HTTP operation. The protocol is pretty interactive and uses a series of requests/responses, so it can't run very long without the app having to run to interpret server responses.

One area where we could make use of background networking is to download individual large attachments, so if you're pulling a 300MB video the app doesn't have to stay active the whole time. But the app does have to be running to kick off each attachment download.

**Comment by skela** [comment]
Thanks @snej . I was specifically referring to [PASync syncClient], didn't really know what thats all about. But just to clarify, I'm just talking about uploading document changes / download document changes, not actually downloading or dealing with attachments. I'm finding that often my users make a change to something, then they immediately go to the Home screen, and my app never syncs the changes, as it looks like the replicators go to sleep immediately.  Is there away to get the replicators to kick in again in the - (void)application:(UIApplication *)application performFetchWithCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler
{ call ?

**Comment by ntodd** [comment]
@skela PASyncClient is just a custom class I wrote to encapsulate syncing functionality in my app.  You could start and manage syncs however makes sense for you.

**Comment by skela** [comment]
Right, I'm basically interested in trying something like that, so just trying to figure out what yer doing inside those classes/functions. Are your replicators continous ? And do you start them up in the syncWithUpdate method, and then kill them after 30 seconds?

**Comment by snej** [comment]
> users make a change to something, then they immediately go to the Home screen, and my app never syncs the changes, as it looks like the replicators go to sleep immediately. 

If the replicator is active when the app goes into the background, it will start an iOS background-task to let the app get CPU time until it completes. It sounds like this isn't working for your app. Please file a new issue and we'll investigate it.

**Comment by skela** [comment]
@snej, so you are saying that the couchbase library already uses the background-task stuff? And that if its not working, this is an issue? (I was under the assumption that all background syncing via couchbase-lite was impossible).

**Comment by snej** [comment]
Yes, that’s what I’m saying.

However, CBL will not _initiate_ syncing in the background. It only keeps the process running long enough to finish a currently-active replication.

**Comment by skela** [comment]
@snej, thanks again for the clarification.

**Comment by lightandshadow68** [comment]
Finally got back round to this while implementing badging. Used a solution similar to ntodd, in which the app delegate method calls triggers a background sync on the user's sync session object. This spins up a one-shot pull replication just for the background fetch, which operates in addition to the continuous push and pull replications that are paused when the app went into the background.

**Comment by srinadh-k** [comment]
is it working in CBL latest version? can you please provide documentation related to this?

**Comment by pasin** [comment]
@srinadh-k There is no specific API for this feature. The replicator takes care of setting up a iOS background task automatically when the app was brought into background. When the replicator is done or the background got expired, the single shot replicator will stop and the continuous replicator will go into suspended mode. The continuous replicator will resume itself after the app is brought up foregrounded.

**Comment by pasin** [comment]
Regarding this issue, I don't think we will implement any features further on top of what we currently support. I'm closing this issue.
