### ISSUE TITLE
Encryption is a no-op with the system libsqlite3 on macOS 12 

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1406]
macOS 12 (10.12 beta 6) ships with a libsqlite3 that claims to support encryption, but `PRAGMA KEY` is a no-op. This causes CBL to believe that it can encrypt databases, but actually no encryption is being used, leaving the database readable :(

This problem will **not** affect apps already using encryption, since they're calling the bundled SQLCipher library, not the system libsqlite3. It will also not affect new apps that correctly enable encryption by linking with libsqlcipher. However, a developer might miss those setup instructions and just try setting a password for a database and find that it appears to work...

**Comment by snej** [comment]
My hypothesis is that macOS has bundled the official encrypted SQLite, which is odd because that's a commercial product. That library requires a special pragma to be issued before `PRAGMA key` can be used; but the special pragma includes a customer-specific license key that we of course don't know.

Jim suggests calling `PRAGMA kdf_iter` after `PRAGMA key`, as a way to distinguish the encrypted SQLite from SQLCipher — the pragma will return a number when called on SQLCipher.

**Comment by brendand** [comment]
I have this problem on iOS 10 also. It happens when I compile my app with Xcode 8. I have Couchbase Lite as a framework compiled with Xcode 7 that I include in my embedded frameworks. When I compile my app with Xcode 7 everything works perfectly. However, when I compile with Xcode 8, encryption no longer works. It basically seems like it's not implemented.

**Comment by brendand** [comment]
I tried compiling with Xcode 8 the 1.3 GM version (which I've enhanced to fix my encryption problems with WAL files as described in this issue: https://github.com/couchbase/couchbase-lite-ios/issues/1343 ), but it won't compile in Xcode 8 due to the Swift upgrade issues. I was hoping that you would be able to fix or incorporate my "fix" as described in 1343 before I moved to the dev branch.

**Comment by snej** [comment]
>When I compile my app with Xcode 7 everything works perfectly. However, when I compile with Xcode 8, encryption no longer works.

But that implies your app links with SQLCipher, not the system's libsqlite3. In which case changes to the system library shouldn't affect it.

**Comment by snej** [comment]
> it won't compile in Xcode 8 due to the Swift upgrade issues.

It's only the unit tests that don't compile; that's the only Swift code in the project. I used some conditional compilation to make them work in commit d3bc31f; maybe that's not in 1.3?

**Comment by brendand** [comment]
Yes, I don't know why it doesn't work when I compile my app in Xcode 8 while still using the Xcode 7 compiled CBL frameworks. It makes no sense. Maybe the next Xcode 8 beta will fix it hopefully.

**Comment by pasin** [comment]
@snej should the fix go into 1.3.1 to be ready for macOS 12?

**Comment by snej** [comment]
I think it should. What's the current process for that? Do we need to have a meeting to decide?

Another question is whether this issue already exists on iOS 10. I ran the unit tests with an earlier beta but not with the last few.

**Comment by pasin** [comment]
I will collect the new issues for 1.3.1 and review them with @waynecarter.
