### ISSUE TITLE
Couch iOS library is FIPS compliant?

### ISSUE THREAD

**Issue by msanilkumar2020** [couchbase/couchbase-lite-ios#1418]
Hi,

We are using Couch CBLite iOS for development.
Is this library FIPS compliant?

As per apple documentation, from iOS 7 onwards they are FIPS compliant.
https://support.apple.com/en-in/HT202739

Can you please confirm this?

Thanks,
Anil Kumar

**Comment by snej** [comment]
By default, encryption is done by [SQLCipher](https://www.zetetic.net/sqlcipher/), a fork of SQLite with encryption support. SQLCipher claims FIPS compliance for their paid enterprise edition but apparently not the open source code. According to [this mailing list thread](https://groups.google.com/forum/#!topic/sqlcipher/H3Y3Ew88T30) the FIPS compliance has to do with how the crypto primitives are implemented; on Apple operating systems we call into the system CommonCrypto library which as you've pointed out is FIPS compliant.

If you choose ForestDB storage instead of SQLite, the encryption is done by our own ForestDB library. This library itself has not been FIPS certified, although, as with SQLCipher, the actual crypto is done using Apple's complliant AES256 implementation.

FYI, we request that developers ask questions on the [Couchbase web forum](https://forums.couchbase.com/c/mobile) or the [Couchbase Mobile mailing list](https://groups.google.com/forum/#!forum/mobile-couchbase). We use Github issues only for bug reports and feature suggestions. Thanks.

**Comment by pasin** [comment]
I think this issue can be closed now.

**Comment by msanilkumar2020** [comment]
Hi Snej,

I am referring to transport layer not the storage layer.

Same issue reported for Android
https://github.com/couchbase/couchbase-lite-java-core/issues/1278

How to make Couch iOS transport layer FIPS complaint?

Thanks,
Anil Kumar
