### ISSUE TITLE
CBL iOS views not indexing

### ISSUE THREAD

**Issue by a2345sooted** [couchbase/couchbase-lite-ios#1428]
I am witnessing some strange behavior with the local views on CBL for iOS and I am unable to create multiple views.

In my initDataService function, I have this:

```
...
self.database = try CBLManager.sharedInstance().databaseNamed(username);
self.createViewOne();
...
```

createViewOne function:

```
private func createViewOne() -> Bool {
    guard database != nil else { return false }

    let view1: CBLView = self.database.viewNamed("viewOne");
    view1.setMapBlock({(doc, emit) in
        print("inside my first view");
        if ("TYPE_A" == doc["type"] as! String) {
            emit(doc["date"] as! String, doc);
        }
    }, version: "1");

    return true;
}
```

This works just fine. However, if I add a second view, like this:

```
...
self.database = try CBLManager.sharedInstance().databaseNamed(username);
self.createViewOne();
self.createViewTwo();
...
```

and createViewTwo function looks like this:

```
private func createViewTwo() -> Bool {
    guard database != nil else { return false }

    let view2: CBLView = self.database.viewNamed("viewTwo");
    view2.setMapBlock({(doc, emit) in
        print("inside my second view");
        if ("TYPE_B" == doc["type"] as! String) {
            emit(doc["date"] as! String, doc);
        }
    }, version: "1");

    return true;
}
```

When I run the app on a simulator, the second view is never created. The print statement is never run, even though I've verified with Couchbase Lite Viewer that the docs have in fact synced with the phone, and also, the view one works fine.

Also, if I get rid of creating a second view, but change the name of the first view, so that createViewOne function looks like this:

```
private func createViewOne() -> Bool {
    guard database != nil else { return false }

    let view1: CBLView = self.database.viewNamed("viewOneB");  //added a 'B' to make view name different
    view1.setMapBlock({(doc, emit) in
        print("inside my first view");
        if ("TYPE_A" == doc["type"] as! String) {
            emit(doc["date"] as! String, doc);
        }
    }, version: "1");

    return true;
}
```

and I run it on the simulator, the app crashes with the following error:

```
2016-09-02 03:22:57.704 MyApp[99924:2908368] *** ASSERTION FAILED: _viewID > 0
2016-09-02 03:22:57.704 MyApp[99924:2908368] *** Assertion failure in -    [CBL_SQLiteViewStorage mapTableName](), /Users/jenkins/jenkins/workspace/couchbase-lite-ios-builds/couchbase-lite-ios/Source/CBL_SQLiteViewStorage.m:226
2016-09-02 03:22:57.708 MyApp[99924:2908368] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '_viewID > 0'
```

In between each test on the simulator, I am deleting the app from the device. I've tried resetting the content & settings on the simulator also.

I'll note that I am using a custom proxy between the CBL on the iOS device and the Sync Gateway. I'm also using v1.3 of iOS CBL.

This error is new as I've successfully created multiple views before upgrading to 1.3. 

This question originated as a question on the forums [here](https://forums.couchbase.com/t/cbl-ios-unable-to-create-multiple-views/9813).

**Comment by a2345sooted** [comment]
I've created a standalone program to show the issue here:

[](https://github.com/a2345sooted/3-times-a-charm)

Strangely, when running this, with a new project from scratch, there's no crash, it's just like the views never index the docs.  I can verify that the docs are on the device by using Couchbase Lite Viewer.

--------
* Version:   Sync Gateway 1.3.0-274
* Client OS: CBL Lite iOS 1.3
* Server:    4.1.0-5005 Community Edition (build-5005)

**Comment by rkrausen** [comment]
Same error in my app without using a custom proxy.

*** ASSERTION FAILED: _viewID > 0
*** Assertion failure in -[CBL_SQLiteViewStorage mapTableName](), /Users/jenkins/jenkins/workspace/couchbase-lite-ios-builds/couchbase-lite-ios/Source/CBL_SQLiteViewStorage.m:226
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '_viewID > 0'
*** First throw call stack:

Server: Version: 4.5.0-2601 Enterprise Edition (build-2601)
Client OS: CBL Lite iOS 1.3

**Comment by pasin** [comment]
@a2345sooted Thanks for the test app. I will try to run that soon.

**Comment by pasin** [comment]
> Same error in my app without using a custom proxy.

@rkrausen What do you mean by using custom proxy? Can you explain more?

**Comment by a2345sooted** [comment]
I mentioned using a custom proxy in my original post.  By that I meant that I have a server sitting between the iOS device using CBL and the Sync Gateway.  This server handles custom authentication and other stuff, then forwards the request, from the CBL iOS instance, on to the sync gateway.  Although I said I was using one, I've since dropped the proxy and connect directly to the sync gateway from the device in order to try to fix this issue.

**Comment by rkrausen** [comment]
@pasin I don't use a proxy but getting the same error.

**Comment by a2345sooted** [comment]
@rkrausen     any progress on this from your end?  I'm pretty stumped

**Comment by rkrausen** [comment]
@a2345sooted Sorry... No idea to fix it myself.... There must be something changed on Framework 1.3. But i figured out, that the error only appears on first adding the views to the database. If the device had a database by framework 1.2.1 everything is ok.
The only workaround (i think) at the moment is to get back to 1.2.1. Not a easy plan. All models must changed again to correct the optional issues.

**Comment by rkrausen** [comment]
WORKAROUND....

Today i got the time to analyze the problem in detail. In my app i can "solve" the problem now.
Problem is, that the time to register the views is to long. So the view can't be used at immediatly after first startup.

1.2.1 available after 0.131 seconds after opening database
1.3 available after 0.830 seconds after opening database

Till Framework 1.2.1 my model-count() function will return 0 if there are no objects. Now it can't proceed because the framework didn't found the view.

Here is my workaround (-> changed function) to get the app working:

`
static func count() -> Int {
        guard ( RKCBHelper.cbDB().existingViewNamed("usersView") != nil) else {
            RkMaHelper.rkLog(message: "usersView unknown", short: true)
            return 0
        }
        
        let query = RKCBHelper.cbDB().viewNamed("usersView").createQuery()
        
        do {
            let results = try query.run()
            return Int(results.count)
        } catch {
            RkMaHelper.rkLog(message: "Error in usersView query", short: true)
        }
        return 0
    }
`

cbDB() only returns the sharedInstance.database

**Comment by a2345sooted** [comment]
i tried waiting until the view exists (via existingViewName(..) function) in the sample app I posted in this question.  So far, it seems to be working.  Now I'm gonna try to incorporate this 'delay' in my much more complex app and hope everything is good.  I'll post an update as soon as I have one.  Nonetheless, great work @rkrausen .  I appreciate your follow up on here.  Helped me a lot.

**Comment by a2345sooted** [comment]
@rkrausen , just out of curiosity, are you using community or enterprise edition?

**Comment by rkrausen** [comment]
@a2345sooted i'm using the enterprise edition. I hope it was useful in your "real" apps.

**Comment by pasin** [comment]
@a2345sooted I have just downloaded and looked into your sample app. The reason that the second view doesn't get indexed because there is no query run on it. By default a view will get indexed (or updated) when the query is called. Once you start to query the second view, you should be able to see the second view index get updated.


BTW, There are 3 index update mode that you can set on the query as below:
```
/** Determines whether or when the view index is updated. By default, the index will be updated
    if necessary before the query runs -- this guarantees up-to-date results but can cause a
    delay. The "Never" mode skips updating the index, so it's faster but can return out of date
    results. The "After" mode is a compromise that may return out of date results but if so will
    start asynchronously updating the index after the query so future results are accurate. */
@property CBLIndexUpdateMode indexUpdateMode;
```

One more thing, the following line in your sample code is not correct. 
```
self._pull.addObserver(self, forKeyPath: "rows", options: [.Old, .New], context: nil);
```
If you would like to observe replication change, you will need to observe kCBLReplicationChange notification with NSNotificationCenter.

**Comment by pasin** [comment]
For the  ASSERTION FAILED: _viewID > 0 failure, it normally happens when the query happens before the view is created with the map function set (it shouldn't crash anyway). The view creation and setting the map function is synchronous process so there shouldn't be any delay unless there is another thread trying to query the view at the same time.

@rkrausen does your application make sure that the map function is set to the view before running the query?

**Comment by pasin** [comment]
I'm closing the issue as it seems to be no real issue and as there is no response.

**Comment by Rups1990** [comment]
@pasin we are also facing the exception after upgrading to couchbase lite 1.3.1,especially after deleting the database and creating again.After long time of analysis, understood that issue is due to CBL_Shared property of CBLManager retains some old reference. More details below,

1.Before deleting the database,created four different views using different instances of databases.
`    CBLManager *cblManager = [[CBLManager sharedInstance]copy];
     CBLDatabase *couchDB = [cblManager databaseNamed:databaseName error:&error];
`
2. After deleting the database,checked the CBL_Shared property of the database's manager, it was nil.
3. Created new database.Check the shared property of the newly created database's manager, it showed the same four views as a value, for key "mapversiontable".

Also understood from the source code that, when a new view is created, it expects the viewID value as  "-1", since it holds the old reference, returns the value which is greater than "0" and the app is crashing because of that

**Comment by Rups1990** [comment]
Please help us in fixing this issue

**Comment by pasin** [comment]
@Rups1990 Thanks for more information. I will reopen the issue and check the scenario that you provided.

**Comment by RubhaK** [comment]
@pasin Thanks.Please find the additional details in the below forum link,

https://forums.couchbase.com/t/why-my-newly-created-database-holds-reference-to-the-views-created-with-previous-deleted-database/11416

**Comment by snej** [comment]
This is the same issue you also asked about on the forum. If you're going to create threads in two places, please link them to each other (I didn't know this issue existed.)

My answer from the forum is that you should not close the manager before deleting the database, since closing the manager closes all databases, and deleting a closed database is technically illegal, but in reality probably just a no-op.

**Comment by snej** [comment]
I answered this on the forum — you shouldn't close the manager before deleting the database. Closing the manager closes all databases, and deleting a closed database (or doing anything else with it) is technically illegal.

**Comment by snej** [comment]
If you fix that and the problem persists, please reopen. If you encounter a different problem, please open a new issue instead.
