### ISSUE TITLE
Update FTS wiki

### ISSUE THREAD

**Issue by lucatorella** [couchbase/couchbase-lite-ios#1465]
Few months ago there was a wiki page where it was stated that prefix search is not supported when using ForestDB.

Now the only limitation I can find is about boolean operators (https://github.com/couchbase/couchbase-lite-ios/wiki/Full-Text-Search#no-boolean-operations-with-forestdb)

Since, as far as I know, this is still a limitation, it should be added again to the wiki page.

**Comment by lucatorella** [comment]
thanks @snej, that sounds great! Is that coming in 1.5 or it's not yet scheduled?

**Comment by snej** [comment]
Not scheduled. More likely in 2.0 than 1.5 … but 2.0 is [in heavy development already](https://github.com/couchbase/couchbase-lite-core), so that's not _too_ far off...

In the meantime, you can sort of fake this approach by creating a separate SQLite database and copying just the text you want indexed into documents in it, then creating a FTS view on it. You can use the same docIDs, to make it easy to correlate between the two.
