### ISSUE TITLE
No way to disable Auto Compact feature in CBLDatabase

### ISSUE THREAD

**Issue by adelwin** [couchbase/couchbase-lite-ios#1488]
It seems like there's no way to disable auto compaction feature since the property is not accessible from the implementation code.
This poses a problem for me since I just upgraded my app from version 1.0.1 to 1.3
1.1 does not have auto compact feature, and the revision tree will grow and grow.
Once upgraded to 1.3, auto compact kicks in and the first time there's an update operation it will compact the revision tree, causing the manager object to freeze.
Creating a copy of the manager to run the auto compaction in the background doesn't help also when the revision tree is sufficiently long. On one of my test case, I have 1 with 10k revision tree. And this causes the manager to freeze for about 7-9 seconds.

I may be missing something, 
Because I think having an option to disable auto compaction seems pretty logical right ?
Anyone have any suggestion ?

--------
* Version:   1.3 (Enterprise)
* Client OS: IOS 8+
* Server:    N/A

**Comment by adelwin** [comment]
typo on my older version of CBL

**Comment by snej** [comment]
I think you mean "pruning" — removing the oldest revisions in a document's tree. (Compaction does more than that, and is only automatic in ForestDB-based databases, not SQLite.)

Have you tried calling -compact on the database right after opening? That will take some time but it's probably faster than having each document individually pruned, and after that everything will be fast.

Turning off pruning isn't the right thing to do. All it does is postpone the problem, because your docs are going to keep accumulating more revisions and bloating the database more.

If you do the compaction on the first launch, you can tell the user you're upgrading their database and it may take some time. (This happens with other apps, like Mail and iPhoto/Photos...)
