### ISSUE TITLE
Bulk-fetching hammers servers that are slow to reply

### ISSUE THREAD

**Issue by avishnyak** [couchbase/couchbase-lite-ios#1500]
I have noticed the following behavior during first-time replication:

CBL fetches the list of changes and queues 12 bulk-fetch requests of 100 documents each.  If those replies take over 1 second to respond (on my test machine), the rest of the documents to be fetched queue up into the 13th bulk-fetch sending a request for THOUSANDS of documents at once to an already busy sync server.

I have isolated the problem down to this line: https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLRestPuller.m#L391

Instead of throwing ALL of the queued revs into the request there should be some sane max limit there as well (e.g. 100).

Here is a snippet from the logger showing the issue:

```
... snip 12 previous requests for 100 items ...
16:28:24.057‖ Sync: CBLRestPuller[http://*****]: postProgressChanged (191/8549, active=1 (batch=77, net=39), lastSeq=455029, online=1, error=(null))
16:28:24.058‖ Sync: CBLRestPuller[http://*****] bulk-fetching 7300 remote revisions...
16:28:24.095‖ Sync: CBLBulkDownloader[(null)]: POST _bulk_get?revs=true&attachments=true  [{"id":"container_365180505a914b52b480be26c12b39cf_AuditLog","rev":"1-55E21DAA6DE150AF1DD924AC2029D587"},
... snip...
```

--------
* Version:   1.3
* Client OS: Couchbase Lite on any version of iOS
* Server:    Custom

**Comment by snej** [comment]
> sending a request for THOUSANDS of documents at once to an already busy sync server.

This should actually be _less_ work on the server than getting tens of requests for 100 docs each; it's the same number of database calls, docs to process and bytes to respond with, but doesn't have the overhead of all the extra HTTP requests.

But that assumes that SG will stream the response instead of assembling it in memory as one giant array and then serializing it when it's done — if it does the latter, it's going to be bad for memory usage and latency. @adamcfraser, @ajres, do you know whether the `_bulk_get` handler is optimized for this or not?

**Comment by snej** [comment]
Sorry, just realized that the 2nd paragraph above is wrong. CBL requests the `_bulk_get` response as MIME multipart, not JSON. That means it should be streamed out by SG.

@avishnyak, can you describe what actual problem you observe as a result of the existing behavior?

**Comment by avishnyak** [comment]
@snej For some internal reasons we couldn't use SG as our server.  The large request causes a huge memory allocation in our stack which is very hard to minimize.  Also, it just seems strange to have 10 small requests and one large request.  If the large one is that much more efficient, then the 10 small ones are a waste.  I believe it's better to have 12 queued smaller requests with 6 running concurrently (even with the HTTP overhead) than 1 large request.

If this works fine for the SG folks, I'm perfectly fine with leaving it as is.  It would be nice to have a flag or something that would enforce the more consistent behavior (i.e. max bulk revision docs actually doing what it says).

**Comment by avishnyak** [comment]
@snej This may also become a performance issue for #1411

**Comment by avishnyak** [comment]
@snej Couchbase Lite for .NET seems to have the correct behavior (max 100 items per request).

https://github.com/couchbase/couchbase-lite-net/blob/8d1949a9916983c29c194df8ae0b6eb4ee86cc73/src/Couchbase.Lite.Shared/Replication/Puller.cs#L265

**Comment by snej** [comment]
OK, I've made the change. I didn't merge your PR because I wanted to rename the constant so it no longer refers to all_docs, but my patch is otherwise identical.

Note however that this doesn't limit the size of a response; documents can be arbitrarily large (especially since they include attachments) so whatever problem your middleware has with large responses could still be triggered by a bulk_get of some huge documents.
