### ISSUE TITLE
Backgrounding potentially freezes app

### ISSUE THREAD

**Issue by basememara** [couchbase/couchbase-lite-ios#1510]
There is a backgrounding/foregrounding process that is intentionally run on the main thread. The source code comments says this is done to avoid race conditions: https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLRestReplicator%2BBackgrounding.m#L54

However, this is dangerous because if there is anything wrong with the replication process or it is simply strained, the app freezes up when going to and from background since it is stuck on `waiting for database`.

--------
* Version:   1.3.1
* Client OS: iOS 10

**Comment by snej** [comment]
The code was changed recently so that link no longer points to the right line; [here's a link](https://github.com/couchbase/couchbase-lite-ios/blob/df1d271565e1563dc2f0f767094678134db48179/Source/CBLRestReplicator%2BBackgrounding.m#L72) to the revision you're referring to.

The -appForegrounding method handles an NSNotification posted by the UIApplication, so it runs on the main thread. There's nothing we can do about that. For some complicated reasons, this handler needs to wait for the replicator thread to run -setSuspended before it returns.

I don't see where there's a deadlock here. Are you saying the replicator thread can be blocked waiting for something to finish on the UI thread? That should never happen. Do you have a stack dump of an actual deadlock from this?

**Comment by pasin** [comment]
I'm closing the issue now. We can reopen it the issue if there is more info. Thanks.
