### ISSUE TITLE
CBLManager spiking memory

### ISSUE THREAD

**Issue by SalmanZafar1105** [couchbase/couchbase-lite-ios#1525]
Couchbase lite spikes memory, when run in background.

dispatch_async(couchbaseQueue!) {
            var database: CBLDatabase?
            let manager = CBLManager.sharedInstance().copy()
            do {
                database = try manager.databaseNamed("XYZ")
            } catch let error as NSError {
                NSLog("Error : \(error.localizedDescription)")
                return
            }
           ....
           ....
}

The above code is run multiple times throughout the running of application.

The app was using more than 400 MB, and then crash. Model - iPhone 5c, 5s, 6

Overcame this issue by reusing the CBLManager instance in background queues. But still memory increases (upto 200-250 MB), if app is used for more than 20-25 minutes. 
This results in application getting hanged, or sometimes even crash.

I have checked my code completely, and there is no memory leak anywhere else in the application, other than this one.

--------
* Version:  1.3.1
* Client OS: iOS 10.0.1, iOS 10.1.1
* Server:    1.3.0

**Comment by pasin** [comment]
Have you done any memory profiling to check what causes the memory leak?

**Comment by snej** [comment]
You should create one CBLManager instance for use on your `couchbaseQueue`, instead of creating a new one for every block you send to the queue. Creating a CBLManager is a fairly heavyweight operation, involving opening a new SQLite connection.

(That said, I don't know why the CBLManagers are being leaked. It shouldn't be necessary to explicitly call `close`, but there may be some accidental reference cycles.)
