### ISSUE TITLE
No enterprise build for 1.4-31

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1586]
http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/1.4/macosx/1.4-31/ does not include an enterprise package

**Comment by sethrosetter** [comment]
@pasin Also, no community package here - http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/1.4/macosx/1.4-30/

**Comment by pasin** [comment]
Sorry wrong commit linked.

**Comment by pasin** [comment]
@ceejatec We need your help on fixing this issue. The macosx doesn't contains both community and enterprise package. It seems to be randomly missing one of them.

**Comment by pasin** [comment]
There is an error when uploading the binary.

```
21:33:14 New build name is '1.4-31-macosx-enterprise'
21:33:14 Variable with name 'BUILD_DISPLAY_NAME' already exists, current value: '1.4-31-macosx-enterprise', new value: '1.4-31-macosx-enterprise'
21:33:14 Archiving artifacts
21:33:14 FTP: Connecting from host [Relaxs-Mac-iOS.local]
21:33:14 FTP: Connecting with configuration [CBNAS01] ...
21:33:15 FTP: Disconnecting configuration [CBNAS01] ...
21:33:15 FTP: Transferred 2 file(s)
21:33:15 SSH: Connecting from host [Relaxs-Mac-iOS.local]
21:33:15 SSH: Connecting with configuration [builds.hq] ...
21:33:21 SSH: Disconnecting configuration [builds.hq] ...
21:33:21 ERROR: Exception when publishing, exception message [Could not create or change to directory. Directory [1.4-31]]
21:33:21 Build step 'Send build artifacts over SSH' changed build result to UNSTABLE
21:33:21 [BFA] Scanning build for known causes...
```

**Comment by pasin** [comment]
Rerun the build fixed the issue. I'm closing the issue now.

**Comment by ceejatec** [comment]
FYI this is a race condition - both the community and enterprise builds run simultaneously, and both try to scp the results to builds.hq at the same time. Occasionally one of them will see there's no 1.4-xx build directory, try to create it, and fail because the other one beat them to it.

As a quick workaround I've tried enabling retries on the scp step in the job. I don't know if that will work - it may be that it will only retry when the connection fails, not when there's an error in the upload.

In the medium term I'd like to shift our jobs away from using that latestbuilds server at all - we need to consolidate on the NAS. Builds are already going to both; we need to ensure that all consumers are updated to the new location.
