### ISSUE TITLE
Use SFSafariViewController in OpenIDController extra utility

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-ios#1600]
Currently, the `OpenIDController+UIKit` utility class uses the `WKWebView` class to open the loginURL and the [webView:decidePolicyForNavigationAction:decisionHandler:](https://developer.apple.com/reference/webkit/wknavigationdelegate/1455641-webview?language=objc) method to close the web view once the redirectURL is reached. But some providers such as Google SignIn will no longer support embedded web views for this authentication flow.

<img src="https://cloud.githubusercontent.com/assets/2589337/22460819/9eaf3bc6-e79e-11e6-948a-660f4c38ed37.png" width="25%" />

The recommended approach seems to be to use `SFSafariViewController` introduced in iOS 9. But I'm not sure how to handle the redirect URL, there aren't any methods like `webView:decidePolicyForNavigationAction:decisionHandler:`. Using URL schemes instead might work. Some blog posts on the topic

- [http://strawberrycode.com/blog/sfsafariviewcontroller-and-oauth-the-instagram-example/](http://strawberrycode.com/blog/sfsafariviewcontroller-and-oauth-the-instagram-example/)
- [https://library.launchkit.io/how-ios-9-s-safari-view-controller-could-completely-change-your-app-s-onboarding-experience-2bcf2305137f#.4sqq8ipam](https://library.launchkit.io/how-ios-9-s-safari-view-controller-could-completely-change-your-app-s-onboarding-experience-2bcf2305137f#.4sqq8ipam)
- [https://stanfy.com/blog/login-user-automatically-sfsafariviewcontroller-ios-9/](https://stanfy.com/blog/login-user-automatically-sfsafariviewcontroller-ios-9/)

--------
* Version:   1.3.1-6
* Client OS: iOS 9.2
* Server:    N/A

**Comment by snej** [comment]
I'm surprised that Google would disallow this, since WKWebView runs in a separate process so it shouldn't have security issues. AFAIK the only difference in SFSafariViewController is that it shares cookies with Safari and has a more Safari-like UI.

I'll read those blog posts to find out more.

**Comment by snej** [comment]
Having read the posts: Using SFSafariViewController is an improvement because it has access to Safari cookies & saved passwords, so if you're already authenticated in Safari you won't have to authenticate again; and if you're not, the login form can autofill your credentials from the Keychain. Nice!

The drawback is that as you pointed out, you can't intercept the special response URL that the server redirects to. Instead, the app has to register that it handles such URLs, and the app delegate class's `-appliction:openURL:` method has to detect the URL and pass it on to the OpenIDController.

This isn't a lot of work, but it results in more wiring that the app developer has to set up. :(

**Comment by djpongh** [comment]
moved to: https://issues.couchbase.com/browse/CBL-281
