### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException [1.4]

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1655]
http://crashes.to/s/9f71ca0e1a6

**Comment by pasin** [comment]
This is a long chasing issue and is hard to reproduce. Related to https://github.com/couchbase/couchbase-lite-ios/issues/794.

**Comment by npomfret** [comment]
Here's another one http://crashes.to/s/9f71ca0e1a6.

**Comment by pasin** [comment]
@npomfret and @msanilkumar2020, if possible, could you please capture the log with Sync and SyncVerbose enable. The crash log itself couldn't trace back to the root cause or scenario.

I couldn't reproduce the issue myself however I reviewed the code and speculated one scenario that could cause the issue to happen. I'm not 100% sure if it is the same scenario that you are facing. I created a fix out of 1.4.0 branch. Could you please check the [feature/fix-1655](https://github.com/couchbase/couchbase-lite-ios/tree/feature/fix-165) branch out and try it out? Please let me know if that helps fixing the issue or not. Thanks.

**Comment by npomfret** [comment]
My errors are typically happening on client devices and I don't currently have a way to capture the couchbase logs.  (Is there a way?)

I'm also not in a position where I can deploy the app built locally from a couchbase branch, but if you make a build with this fix in I can deploy that and monitor the situation.

**Comment by pasin** [comment]
I submitted a PR for merging into the master branch so that it could get into the CI for build.

**Comment by npomfret** [comment]
Thank you!  Is there a build available yet?

**Comment by pasin** [comment]
It's still waiting for review. Once it's merged and built, I will let you know. Thank you.
