### ISSUE TITLE
Rev tree pruning inconsistent with SG

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-ios#1714]
See: https://github.com/couchbase/couchbase-lite-net/issues/831

**Comment by brendand** [comment]
I posted on the Couchbase Lite Google Group about an issue that I'm having with documents being deleted. I posted a screenshot there too. Jens Alfke suggested my issue might be related to a bug in revision tree pruning that has been fixed in the .Net implementation of Couchbase Lite 1.4.x, but not in the iOS version.

https://groups.google.com/forum/#!topic/mobile-couchbase/3L9w5M1gpGU

Is it possible to get this fixed in 1.4.x for iOS too?

Thanks,

Brendan

**Comment by pasin** [comment]
.NET and iOS code are pretty diverted in that area. The direct porting the fix won't work.

**Comment by brendand** [comment]
The .NET fix seemed to only update the SQL generated to prune the revisions.

They just added this to the delete command:

```
AND sequence NOT IN (SELECT parent FROM revs WHERE doc_id=? AND current=1)
```

So I just added that bit to the code here:

```
f (![_fmdb executeUpdate: @"DELETE FROM revs WHERE doc_id=? AND revid < ? AND current=0 AND sequence NOT IN (SELECT parent FROM revs WHERE doc_id=? AND current=1)", @(docNumericID), $sprintf(@"%u-", minGenToKeep), @(docNumericID)]) {
 ... other stuff...
}
```

Are you saying that won't solve the problem? Would it be dangerous to make that change in the iOS version?

**Comment by snej** [comment]
@pasin and I just looked at the pruning code, and it looks like it works correctly already. I haven't studied the C# code, but I think it's based on an earlier version of the pruning algorithm, and @borrrden 's fix there there doesn't apply to this codebase.

The significant code is in -[CBL_SQLiteStorage pruneDocument:numericID:generationsBelow:]. If the document history is linear, it just deletes all revisions below a minimum generation #. Otherwise it fetches the topology of the tree (every revisions sequence and parent sequence), finds the revisions that aren't near enough to a leaf, and deletes them. In no case does it leave a tombstone revision with no parent, which was the source of the bug. (Well, not unless you set maxRevTreeDepth to 1, which would be a bad idea.)

**Comment by borrrden** [comment]
FYI There are two fixes that went into the same place.  There was this, and then there was the fix to make sure that any node always has a parent because without a parent present bad things start happening.  This one was already in iOS and I ported it to .NET.  The other was something that I discovered that needs porting the other way.
