### ISSUE TITLE
REST API get while in the background

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1746]
* Version:   1.4
* Client OS: iOS 10

I'm unable to get the REST API to work reliably when the app is in the background.  

I have 3 scenarios in which i'd like it to work:

* The user saves a document and instantly backgrounds the app
* The app receives a push notification while in the background
* The app _wakes up_ in order to perform a background-fetch

As far as I can tell the REST api doesn't work when my app is running in the background.  I don't get any errors, but when I do a GET (for a specific document id for example) from `http://lite.couchbase./` the query either doesn't return (until the app is activated again) or it doesn't return any data.

Is there a way to _turn on_ the listener when the app is backgrounded?

**Comment by pasin** [comment]
If you turn on Router logging, does it show anything?

**Comment by jamiltz** [comment]
I thought that using the manager's `internalURL` instead of the actual embedded HTTP server worked in the background (i.e when leaving the app without quitting it).

It'd be helpful to have an app that can reproduce the issue. I'm guessing that you're already using a react native plugin to get notified when a background fetch task is started and from there to send requests to `http://lite.couchbase./`?

**Comment by pasin** [comment]
I have tested this issue by using silent push notification to send a HTTP request (e.g. http://127.0.0.1:8888/db) and I could reproduce the issue. 

However the reason that the request cannot be sent or the listener cannot be reached was because iOS suspended the app almost immediately after the first runloop event on the main thread was done execution. I was able to get the response from the listener if I started a background task before sending the HTTP request. After all, I think this is not an issue. It is an app's responsibility to start background task to be able to send HTTP requests.
