### ISSUE TITLE
Wrong return code for listener causes problems with puller and deleted items

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-ios#1750]
From https://github.com/couchbase/couchbase-lite-net/issues/850

Sync Gateway will return 200 with a small body when a deleted revision is requested by ID, but CBL will return 404 with "reason: deleted". This will cause a puller to skip this revision and never delete a document locally if it happens to get into a non-bulk pull request. The simple test case from a forum post seem to be start up instances, one with a listener running and the other with continuous push and pull, and then add a document to the listener side and subsequently delete it with enough delay in between to ensure that both end up requesting the document directly. This logic appears to affect Objective-C as well, but I have not checked Java.

**Comment by pasin** [comment]
It turned out that iOS doesn't have same issue as .NET and Android. 

@borrrden and @hideki could you please review again why the fix is needed for the platform as the code looks pretty similar in that area?

**Comment by borrrden** [comment]
There is an extra part in .NET which returns null for a delete revision from the SQLite store.  I'm not sure why, as iOS does not do this.  It looks like I did this in order to get the correct return code for the deleted document in the first place (https://github.com/couchbase/couchbase-lite-net/issues/806)
