### ISSUE TITLE
2.0: Need a property accessor to access the value as int64 (longLong)

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1768]

**Comment by eljefe6a** [comment]
Looking at it closer, there is an accessor for `NSInteger`, but not a `long` or `int`.

**Comment by pasin** [comment]
In Objective-C, I think the developer tends to use NSInteger which automatically select 32 bit or 64 bit depending on the platform. I'm trying to limit to what the developers commonly use. Do you see a need for int and long?

**Comment by eljefe6a** [comment]
I can't weigh in either way. I was more checking for parity between the Java and iOS sides.

**Comment by snej** [comment]
These are all convenience methods wrapped around `valueForKey:` and its equivalents.
It makes sense to have the basic int accessor return an `NSInteger` since this is the default integer type in Cocoa.

I'm conflicted about having an accessor for `int64_t` aka `long long` — that's only different from `NSInteger` in 32-bit apps, and Apple is about to kill those off in iOS 11. But on the other hand we do ship a 32-bit version of the library.
