### ISSUE TITLE
Problem installing CouchbaseLiteSwift 2.0DB016

### ISSUE THREAD

**Issue by Codeido** [couchbase/couchbase-lite-ios#1891]
Hi, 
I have some problem during the installation using Cocoapods.

I wrote this line on my podfile:
```
pod 'CouchbaseLiteSwift', :git => 'https://github.com/couchbase/couchbase-lite-ios.git', :tag => '2.0DB016', :submodules => true
```

but the installation is blocked here:
```
Pre-downloading: `CouchbaseLiteSwift` from `https://github.com/couchbase/couchbase-lite-ios.git`, tag `2.0DB016`, submodules `true`
```

Any suggestion?

--------
* Version:   2.0DB016
* Client OS: -
* Server:    -

**Comment by snej** [comment]
@pasin is our CocoaPods expert but he's out on leave for a few weeks.
Can you describe in more detail what you mean by "the installation is blocked"?
As a workaround, I suggest downloading the prebuilt binary from our server and adding the framework from that to your project.

**Comment by pasin** [comment]
The message could be stuck at the `Pre-downloading ...` for a long time (~20 mins) as CBL 2.0 CocoPods also build the framework after the project is clone from GitHub. 

Basically the App project will link with the built CBL framework instead of CBL source codes. This allows us to manage the complexity of the dependencies and to optimize the built binary. The framework could take some time to build as we need to build the FAT frameworks for 3 platforms (iOS, tvOS, and MacOS).  If CocoPods allows us to know what the App platform is during the pod preparation step in the future, we could optimize the wait time.

Anyhow, if you run the `pod install` with the `--verbose` option, you could see a bit more info about what's going on. I have just ran a quick test and I don't see any issues - it took about 20 mins to finish.

**Comment by pasin** [comment]
If the pod cannot be installed or there is any error, please feel free to reopen the issue. Any suggestion about CocoaPods is welcome as well. Thanks.

**Comment by Codeido** [comment]
Thanks for your response!
I want to use it in a Swift app, and I see a lot of improvements from the v.1.4. Do you suggest to try this version 2.0 in a production app?

**Comment by snej** [comment]
It depends on when you want to ship your app. If you plan to ship within the next, say, four to six months, then 2.0 might be too bleeding-edge, since its release date isn't until around the end of the year. But if you're earlier in development, yes, I strongly recommend 2.0 because it's a stronger foundation, much faster, and has greatly improved querying.

**Comment by snej** [comment]
…but to be fair I should point out two features 1.4 has that 2.0 won't due to schedule constraints:

* Geo-queries
* Model classes that automatically bind document properties to native properties (like NSManagedObject in Core Data)

It sucks that we couldn't get these reimplemented in 2.0, but we had to postpone some features not everyone uses in order to get a release out sooner. These features will follow — models definitely in 2.1, geo is likely but might be later depending on demand for it.

**Comment by Codeido** [comment]
Thank you very much @snej! Yes i want to go in production in < 1 month. I see that the queries has changed complety, and now are really great! 

💯 Thanks
-Paolo
