### ISSUE TITLE
Use the same _id of a deleted document

### ISSUE THREAD

**Issue by Codeido** [couchbase/couchbase-lite-ios#1892]
Hi,

I encountered a problem in my implementation of Couchbase lite 2.0.
On the first run, the DB is populated correctly, but when a try to repopulate the db, I have the documents inside, but every document is empty.

Every document, if already exist when I try to add a new element is deleted from the DB if already exist, and a new document with the same id is saved.

```
        if let doc = database?.getDocument("booking-\(booking!.id!)"){
            try? database?.delete(doc)
        }
        
        do {
            // Save the document to the database
            let doc = Document("booking-\(booking!.id!)", dictionary: booking!.toJSON())
            try database?.save(doc)
        } catch {
            log.error("Can't save booking in database")
            return
        }
```

Any suggestion? Is a correct approach?

--------
* Version:   2.0 Build 16
* Client OS: iOS 10.3
* Server:    -

**Comment by snej** [comment]
Sorry, I can't understand the description of the problem. I don't know what you're doing to populate the database, or what's involved in "repopulating".

I'm wondering why you're deleting all the documents. Deletion doesn't just get rid of a document completely the way it would in, say, SQLite. Deletions will be replicated, so deletion actually adds metadata to the document saying it's deleted.

```
            let doc = Document("booking-\(booking!.id!)", dictionary: booking!.toJSON())
            try database?.save(doc)
```
This will only work to create a new document, not to update an existing one. Couchbase Mobile uses Multi-Version Concurrency Control, so an update has to be based on an existing version (revision ID) of a document. If you create the Document object from scratch, instead of reading it from the database, it's not based on any existing version, so there will be a conflict error if there's already a document in the database.

Anyway, please show an _exact_ sequence of steps to reproduce your problem, if you still feel there is a bug.

**Comment by Codeido** [comment]
Thanks for this tips @snej! Then, if I want to overwrite completely a document that already exists, deleting all the extra fields that are not contained in the updated version, what I have to do? 
I tried first to delete the document and to resave it, but it's not working as expected.

**Comment by snej** [comment]
Just get the document from the database, set the properties to what you want (individually deleting any you don't want, or just calling setDictionary to replace it entirely), and save.

**Comment by Codeido** [comment]
Thanks! It's working now 💯 

-Paolo
