### ISSUE TITLE
Changing channel for a document, it still syncs to devices

### ISSUE THREAD

**Issue by skela** [couchbase/couchbase-lite-ios#1916]
We have a similar situation as mentioned here: https://forums.couchbase.com/t/behavior-on-doc-channel-change-existing-and-fresh-sync/14048/4
Basically we want to start "archiving" documents that are no longer needed, that we no longer want to sync to the mobile devices. This is because when there are more than 300k documents on the mobiles, all database operations become unusably slow. We do this by changing the channels for the docs we want to archive to an "archived" channel. The docs do not disappear from the various devices as we expected, nor do they seem to get ignored when we hookup a replicator to an empty database on the mobile. If we create new documents in the "archived" channel, they don't sync, so something weird is going on here.

How can I "archive" documents so they no longer sync to new devices and are removed from existing devices?

--------
* Version:   c8d007fd5cea76b881f888e793cd5c2f04355709
* Client OS: iOS 9 / 10 / 11

**Comment by pasin** [comment]
> The docs do not disappear from the various devices as we expected, nor do they seem to get ignored when we hookup a replicator to an empty database on the mobile.

This seems wrong. When you change the doc channel to the `archived` channel to a document, SGW should send a channel REMOVAL message (in changes feed) to the pull replicator so that it could mark the document as removed. So when the app queries the document, the document shouldn't be appeared in the result. 

Can you provide both client (with Sync, SyncVerbose, ChangeTracker, ChangeTrackerVerbose) and SGW log during the time that you change the document channel to the `archived` channel?

**Comment by skela** [comment]
I'll try and get some logs when I have time sure, but just in case its relevant, user is given the "archived" channel server side, but when I set up the replicator, I'm setting the desired pull replicator channels so that I'm on purpose omitting the "archived" channel. But yeah, its certainly being synced over still.

**Comment by pasin** [comment]
I forgot to ask that how do you change the doc channel to the 'archived' on the server side. Are you doing to via Sync Function?

**Comment by skela** [comment]
Sorry I did not specify here, but the channel change is done on the mobile side.

**Comment by pasin** [comment]
I talked to @tleyden about the approach, he said the approach that you are taking seems to be the right approach. There are a couple of things that you want to make sure:

1. When changing the channel of the document, (from Sync Function) you need to make sure that the user still has access to the old channel otherwise the REMOVAL message will not get sent to the replicator.

2. Need to make sure that the user doesn't have access to the `archived` channel.

PS: 
1. The client and SGW log are needed for debugging.
2. If you can abstract the logic into a very simple sample app with sync function, it could be very helpful for us to look at where the problem is.

**Comment by skela** [comment]
@pasin thx for yer information here.

1. The user does have access to the old channels
2. The user also has access to the archived channel, but when I set up the replicator pull channels, I don't include the archived channel in it. That way we ensure that the app is able to push to this channel, but that it doesn't get pulled back.

Do we have to change the channel via sync function? What about if we want to allow users to choose which documents to archive?

**Comment by pasin** [comment]
By doing it that way, it means that the user always has the access to the old channels; Any updates to the documents will still go to that channels, and there is no real removing docs from the old channels . If the pull replicator includes the old channels, you will always get the updates.

**Comment by pasin** [comment]
In general, I would do something like this:

Documents:
{
    "channels" : ["a"],
    "archived": true / false
    ....
}

Sync Function: 

function(doc, oldDoc) {
    if (doc["archived]) {
        channel("archived");
    } else {
        channel(doc["channels"]);
    }
}

**Comment by djpongh** [comment]
If Pasin's suggestions don't work, feel free to re-open.

**Comment by skela** [comment]
Sorry can you explain a bit more I don’t get it.

**Comment by pasin** [comment]
1. In order to allow SGW to send the REMOVAL message to the replicator when removing the documents from the channel or when switching the documents to another set of channels, the logic needs to be done via Sync function by using channel() function. When doing that, the user also needs to have access to the old channels otherwise SGW cannot send the REMOVAL message.

When the replicator received the REMOVAL message, it will mark _removed = true to the document on the mobile device. The removed documents will not be physically removed from the device but it will not show up in the query. There shouldn't be any more updates sent to the documents as well unless the document is added back to the old channel again.

2. From my sample above, I have an archived flag in the document that you can mark a certain document to get archived. When the document is marked as an archived doc, and the document is pushed to the SGW, the Sync function will switch the channel to the `archived` channel (by doing that SGW will also remove the document from the old channels (e.g. Channel 'a' from my sample).

**Comment by skela** [comment]
Excellent, thanks for the explanation pasin, we will give that a go asap.

But might be an idea to keep this issue open, because yes we can work around the issue by following pasin recommendation, if you don't the issue is still there.

Scenario is:
* 1 document (lets call it steve) created with channel 'sierra'.
* 1 document (lets call it alpha) created with channel 'archived'

Alpha document is never synced with the mobile devices, excellent.
Steve syncs to mobile devices, also excellent.

Now we remove the 'sierra' channel from the steve document on a mobile phone, and add the 'archived' channel.

The alpha document does not disappear from the current mobile, nor does it from anyone else's.
Also if we setup an empty database the document will sync across still.

This is counter intuitive and frankly a bit wrong, don't you think you should fix it?

**Comment by jamescooke** [comment]
Hi @pasin - thanks for the explanations. I'm working with @skela on the problem he's outlined above.

As you mention, one solution to making the change of channel would be to use the Sync Function on the SGW to watch for that archived flag and adjust the channels when that flag is found. That solution might be complicated for us to achieve in production because the system we're working on has a large number of channels and documents would be archived into specific channels depending on their current channel configuration.

Instead, I'm wondering if we could achieve the same effect by changing the channel of the documents when they are archived using the admin port - do you think that would work? We already have a web server connected to the SGW managing users and channels so we could extend that to something like a webhook or changes worker to archive documents when their flag is set.

**Comment by pasin** [comment]
> >That solution might be complicated for us to achieve in production because the system we're working on has a large number of channels and documents would be archived into specific channels depending on their current channel configuration.

Can you describe a little in more detail about the complexity? I'm not a SGW expert here but our SGW engineers might be able to help or provide suggestion.

> Instead, I'm wondering if we could achieve the same effect by changing the channel of the documents when they are archived using the admin port - do you think that would work?

I'm not aware of the Admin REST API for changing the document channels.

@adamcfraser or @tleyden beside using Sync Function to switch or change the document channels, are there any other ways?

**Comment by adamcfraser** [comment]
@pasin A document's channels can only change when the document is updated (channels are associated with a given revision of the document, and that's always done via the sync function).
