### ISSUE TITLE
2.0: Selecting a non existent key will return key: null

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-ios#1982]
CBL 2.0 DB 20

CBL query against travel-sample bucket:
```
    let searchQuery = Query
        .select(SelectResult.expression(Expression.meta().id),
                SelectResult.expression(Expression.property(name)),
                SelectResult.expression(Expression.property(type)))
        .from(DataSource.database(database))
        .where((Expression.property("country")).equalTo("France"))
```
one of the CBL results:
```
{'type': u'airport', 'id': u'airport_1257', 'name': <null>}
```
Equivalent N1QL query against travel-sample bucket:
```
select name, type, meta().id from `travel-sample` where country="France"
```
one of the n1ql results:
```
  {
    "id": "airport_1257",
    "type": "airport"
  }
```

### Expected
CBL should not return name: <null> for non existent fields. Its not posible to differentiate between non existent keys and `name: null` k,v pair

for a k,v pair with null like, `"faa": null`, n1ql does return null
```
{
    "faa": null,
    "id": "airport_1260",
    "type": "airport"
  },
```

**Comment by pasin** [comment]
The current implementation of CBL is always keeping the key based on what specified in the select statement. Also we cannot differentiate between null or missing value when getting the query result's values.

**Comment by pasin** [comment]
The same thing is also applied to the `containsValueForKey:` method.

**Comment by rajagp** [comment]
@pasin : Can you provide a summary of the APIs (if any) that we plan on enhancing with this new ability to distinguish between nil and missing.  For instance, We have the `isNullOrMissing()`. Will will now separate isNull() and isMissing() ?

**Comment by snej** [comment]
@rajagp: There isn't any new ability. We are just going to fix a bug wherein LiteCore's C4QueryEnumerator doesn't convey the difference between null and missing in a column value, which means that the CBL Query class always returns either one as a null value. In other words, the only APIs or behavior to be affected are on the QueryResult class.

**Comment by rajagp** [comment]
OK. Got it!
 I was wondering if the ability for LiteCore to propagate the difference between null and missing properties would be leveraged/extended to other APIs as well - like to distinguish between a getter on a non existent key versus a key with null value without the need for a specific `containsValueForKey` call or in case of isNullOrMissing as mentioned above.

**Comment by snej** [comment]
LiteCore doesn't have an API for document properties; it just gives CBL the Fleece data. The Fleece API has a clear distinction between `null` and missing/undefined. The need for `containsValueForKey` is something specific to the CBL API design; IIRC it's to support platforms like Java where there's no distinction between `null` and missing.

**Comment by rajagp** [comment]
> The need for containsValueForKey is something specific to the CBL API design; 

Yes. I understand that. Sorry if I was unclear. 
Hence my original question to @pasin  on  the existing CBL API - whether we will be updating any other API to distinguish between null and missing properties .  If we are not going to tweak any of the APIs , that's fine by me. 

>  IIRC it's to support platforms like Java where there's no distinction between null and missing.

hm..unless I am missing something, even on iOS, I am not able to distinguish between null and missing using existing getters 
In this snippet below, I get 0 for both cases 3 and 4 . There is no way to distinguish between the two cases unless I use something like `containsValueForKey`

```
// 1. 
[doc setValue: @100 forKey: @"nullkey"];
//2. 
[doc removeValueForKey:@"nullkey"];
// 3.
NSLog(@"%ld ----**",[doc integerForKey:@"nullkey"]);
// 4.
NSLog(@"%ld ----**",[doc integerForKey:@"nonexistentkey"]);

```

(**Separate issue:** Since I get 0. So I cannot distinguish between null, non existent or the case when value is actually 0. So its slightly  worse. Seems like we need to enhancement ..for 2.1 ?)

**Comment by pasin** [comment]
@rajagp We don't have a plan to update the API to distinguish between null and missing when getting the value from dictionary. We made the decision based on what we expect most of the users will do. We believe that most of the users will handle null and missing the same way. It is pretty much the same reason for having Expression.isNullOrMissing(). For dictionary, if users want to check whether the key exists or not, users can do by calling the contains(key) method.

**Comment by rajagp** [comment]
Fair enough . Just wondered if users would get confused now that they see the distinction being made in between null and missing in query results case but not in other cases. There should probably be consistency? 
-Anyone know What does server side Api do when you try to get value of a key that’s missing versus non Existent? 
- If I recall , N1QL query distinguishes between isNULL and isMissing ( anyone else confirm?) 
Since we updated this query result stuff to be aligned with what server does , shouldn’t we do the same for related stuff ?

I am fine to raise this as a separate enhancement ticket fir 2.1?

**Comment by pasin** [comment]
Interesting that JSONObject.isNull() means is null or missing.

**Comment by rajagp** [comment]
Interesting indeed. Maybe other SDK implementations vary? I will add an enhancement ticket for the isNullOrMissing for 2.1
