### ISSUE TITLE
Should CBLDocument conform to NSMutableCopying?

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#2015]
CBLDocument has a `-mutableCopyWithZone:` method, but isn't declared as conforming to NSMutableCopying. I'm not sure what actual difference it makes, but it seems like a good idea to declare this.

**Comment by rajagp** [comment]
Good Point/ Question. Not entirely sure. Probably better to be explicit because (AFAIK) NSObject does not conform to this protocol so not sure what it will do by default. 
 I noticed the following glitches ...along similar lines
1. We do not specify conformance to NSCopying either in many cases . 
For instance  
- [CBLDatabase](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/CBLDatabase.mm#L115)
- [CBLDictionary](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/CBLDictionary.mm#L62)
- CBLMutableDictionary
- CBLMutableArray
- CBLDatabaseCOnfiguration

there are a few more instances ...

2. A bunch of other classes have also not been marked as conformant  to NSMutableCopying
- List is similar to one listed in (1)

3. Curious ( maybe a separate issue): 

I noticed that the `mutableCopy` implementation of CBLDocument does not call the `mutableCopy:WithZone` (which we have overridden).

 ```
- (CBLMutableDocument*) toMutable {
    return [self mutableCopy];
}
```
Shouldn't it be this instead
```
- (CBLMutableDocument*) toMutable {
    return [self mutableCopyWithZone:nil];
}
```

There are probably few more instances of the above ...

**Comment by pasin** [comment]
@rajagp Not everything needs to conform to NSCopying and NSMutableCopying. Also calling mutableCopy will call to mutableCopyWithZone:. It could be a bit better to call mutableCopyWithZone: directly.

I think it is a good idea to make the following conforming to NSMutableCopying protocol:
* CBLDocument
* CBLDictionary
* CBLArray

We can make CBLDictionary, CBLArray, and CBLDocument conforming to NSCopying as well. However I don't know what it be should returned for CBLMutableDocument's -copyWithZone:.

**Comment by snej** [comment]
NSObject doesn't conform to NSCopying because not all types of objects are copyable (e.g. NSStream.) Subclasses that are copyable are supposed to add conformance to indicate that.

copyWithZone: and mutableCopyWithZone: shouldn't be called directly. The reason they exist is for backward compatibility; "zones" haven't existed since early versions of OPENSTEP.

**Comment by pasin** [comment]
I made the following changes:

* CBLDocument <NSMutableCopying >
* CBLDictionary <NSCopying, NSMutableCopying>
* CBLArray <NSCopying, NSMutableCopying>

**Comment by pasin** [comment]
I'm still not 100% sure if I should make CBLDictionary and CBLArray. It doesn't seem to be useful. The implementation now also returns self.

**Comment by rajagp** [comment]
@pasin 
- Why are we explicitly not declaring conformance to NSCopying for CBLDatabase and CBLDatabaseConfiguration ? Why even provide an implementation of this interface if we don't want anyone to use it>

- I don't believe that my issue (3) from my comment above is addressed . I will raise it as a separate issue since its not directly related to this topic

**Comment by pasin** [comment]
@rajagp it could be useful to add NSCopying support to CBLDatabase. The CBLDatabaseConfiguration (same as CBLDocument, CBLDictionary and CBLArray) is immutable now so it is not be useful to make it conforming NSCopying.

**Comment by snej** [comment]
>I'm still not 100% sure if I should make CBLDictionary and CBLArray. It doesn't seem to be useful as those two are readonly. 

It's useful because an instance of CBLDictionary may or may not be mutable, and to get a stable snapshot of it you can call `copy`. This idiom is frequently used with Foundation collections and strings when a class is assigning them to an instance variable, to make sure nothing can mutate the ivar.

>The implementation now also returns self.

That is the correct thing to do in an immutable base class. Again, this is part of the Cocoa design pattern. Please put NSCopying back in.

**Comment by pasin** [comment]
OK. I made CBLDictionary and CBLArray conform to NSCopying.

**Comment by rajagp** [comment]
@pasin , @snej  : Doesn't the above argument (of assigning to ivars) hold true for Document as well ? As in shouldn't we specify conformance to NSCopying even in these cases? 
(Still debating  if Database should have it although it's only immutable- probably OK to leave that out)
