### ISSUE TITLE
Pull replication not filtering to channel when doc is still accessible via other channels

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#2040]
This is from CBSE-4683.

**Background**

A user has an app which will perform replications filtered to certain channels. In particular, this will be used to pull down a subset of the user's channels on startup etc.

**Problem**

When trying to replicate only channel foo, CBL is also replicating documents that have been removed from foo. For example: if a document is in channels: ["foo", "bar"] at revision 3-abc and revision 4-def changes this to just ["bar"], revision 4-def will still be replicated to the device with content (not removed rev) if the user has access to channel bar even with a replication specifically filtered to foo only.

**Changes feed sample**

```
{
"changes": [
{ "rev": "4-def" }
],
"id": "my_doc",
"removed": [ "foo"],
"seq": 7
}
```

**Comment by pasin** [comment]
This is currently a limitation as the pull replicator needs to download the removed revision from the SGW to be able to insert it correctly on the rev tree. If the document is not accessible by the user anymore, the removed rev will be downloaded, however if the the document is still accessible via other channels, the non-removed rev will be downloaded regardless of channel filter settings.

From the discussion in the CBSE ticket, CBL may be able to do the following:
1. Not (bulk) get the documents that are marked as removed if they aren't already present in the database.
2. Make CBL replicator to be able to filter out the removed revisions based on the channel filtering set to the replicator. For example, replicator will not download removed revision if the removed channel matched a channel in the channel filtering.

**Comment by pasin** [comment]
I have captured a comment from @JFlath regarding the two options. See below:

> Thinking about it a bit more, I think we have to go with option 1.
>
> Option 2 would require us knowing about the channel at the CBL side, which AFAIK we don't have the ability to do (we don't get the actual channel in the _bulk_get response). I can think of potential ways around this, but I don't think they're practical. It also does not cut down on the bandwidth implications and introduces an edge case that option 1 neatly covers.
Given the case of a document where rev 1 is in chan_A, rev 2 is in chan_B; and the user has access to both channels:

Scenario | Expectation | Option 1 | Option 2 | Current
-- | -- | -- | -- | --
CBL has no revisions. Replication filtered to chan_A | Document is not replicated as it is not in chan_A | ✓ | ✓ | ✗
CBL has no revisions. Replication filtered to chan_B | Document is replicated as it is in chan_B | ✓ | ✓ | ✓
CBL has rev 1. Replication filtered to chan_A. | Document is replicated as we need to replicate the removal from chan_A | ✓ | ✗ | ✓
CBL has rev 1. Replication filtered to chan_B. | Document is replicated as we need to replicate the addition to chan_B | ✓ | ✓ | ✓

**Comment by pasin** [comment]
@snej @borrrden @hideki please see the issue. I would like to discuss this during the cross-platform meeting today.

**Comment by snej** [comment]
At first glance this sounds like something for SG to fix -- the purpose of its including a doc in the feed when it's been removed is so that it can generate a fake `_removed` rev. If it's not going to send the fake rev (because the doc is still accessible to the user) it shouldn't send a rev at all.

>From the discussion in the CBSE ticket, CBL may be able to do the following:

Your suggestions seem to rely on CBL getting a `_removed` rev, but according to the initial description, it's not. Am I missing something? _(Quite likely: I haven't thought much about this removed-from-channel stuff in a long time...)_

**Comment by pasin** [comment]
> Your suggestions seem to rely on CBL getting a _removed rev, but according to the initial description, it's not. Am I missing something? (Quite likely: I haven't thought much about this removed-from-channel stuff in a long time...)

Both of the suggestion above are pretty much about avoiding to try to get the _removed rev based on the information from the _changes feed regardless of what the _removed rev will actually be.

**Comment by pasin** [comment]
> At first glance this sounds like something for SG to fix -- the purpose of its including a doc in the feed when it's been removed is so that it can generate a fake _removed rev. If it's not going to send the fake rev (because the doc is still accessible to the user) it shouldn't send a rev at all.

Ping @adamcfraser on this.

**Comment by adamcfraser** [comment]
Currently SG considers 'removed' to mean 'removed from this replication'.  For an unfiltered replication, that also means 'no longer accessible to the user'.  For a filtered replication, though, it just means 'no longer in the requested channels'.  

From a functional perspective, it feels correct that a mutation stream filtered on a given channel set should be providing notification when documents get removed from that channel set.  I'm not sure SG should be making assumptions about whether the client cares that the doc is accessible via another channel.

We could consider enhancing SG's changes to include both pieces of information ('removed from replication', and also 'user no longer has access') if that better satisfies the functional requirement, but it would be a non-trivial change with some performance implications (channel cache entries don't currently include the full set of channels for the doc).   I think we'd need some deeper analysis of whether including both flags would actually address the use cases being discussed.

**Comment by snej** [comment]
In this situation, what does SG send in the feed? Is there some way to differentiate between "the doc is now inaccessible" and "the doc was removed from this channel but is still accessible"?

**Comment by adamcfraser** [comment]
@snej Are you asking about what SG does today, or what it would do w/ the enhancement described above?

**Comment by JFlath** [comment]
> Is there some way to differentiate between "the doc is now inaccessible" and "the doc was removed from this channel but is still accessible"?

I think the issue here would be line 3 of the table @pasin copied in:

Scenario | Expectation | Option 1 | Option 2 | Current
-- | -- | -- | -- | --
CBL has rev 1. Replication filtered to chan_A. | Document is replicated as we need to replicate the removal from chan_A | ✓ | ✗ | ✓

In this case it's legitimate to replicate that document, as `chan_A` has legitimately changed, so even if SG reported the document as something like `removed:accessible`, CBL should go and get it. This creates an issue where essentially `removed:accessible` could imply two different behaviours. To add that to the table:

>Given the case of a document where rev 1 is in chan_A, rev 2 is in chan_B; and the user has access to both channels:

> 1. Not (bulk) get the documents that are marked as removed if they aren't already present in the database.
>1. Make CBL replicator to be able to filter out the removed revisions based on the channel filtering set to the replicator. For example, replicator will not download removed revision if the removed channel matched a channel in the channel filtering.
>1. Have SG differentiate between`removed:accessible`  and `removed:lost_access` or similar.

Scenario | Expectation | Option 1 | Option 2 | Option 3| Current
-- | -- | -- | -- | -- | --
CBL has no revisions. Replication filtered to chan_A | Document is not replicated as it is not in chan_A | ✓ | ✓ | ✓ (`removed:accessible` - CBL **should not** `_bulk_get`) | ✗
CBL has no revisions. Replication filtered to chan_B | Document is replicated as it is in chan_B | ✓ | ✓ | ✓ | ✓
CBL has rev 1. Replication filtered to chan_A. | Document is replicated as we need to replicate the removal from chan_A | ✓ | ✗ | ✗ (`removed:accessible` - CBL **should** `_bulk_get`) | ✓
CBL has rev 1. Replication filtered to chan_B. | Document is replicated as we need to replicate the addition to chan_B | ✓ | ✓ | ✓ | ✓

**Comment by jayahariv** [comment]
Closing 1.x issue!
