### ISSUE TITLE
Missing refs create new docs on access

### ISSUE THREAD

**Issue by ketodiet** [couchbase/couchbase-lite-ios#2060]
Shouldn't this be calling existingDocumentWithID?

https://github.com/couchbase/couchbase-lite-ios/blob/453683a4866141e49ca496d1232a7b2e845e95bd/Source/API/CBLModel.m#L530

Otherwise when fetching a referenced doc - which may have not be synced yet - will end up creating a new (empty) instance of the doc.

**Comment by pasin** [comment]
This is a design choice whether we would like to see the document to be nil or an empty (non-existing) one. In most case (e.g. getting a document property or updating UI based on property values), returning an empty document should result to the same result. With the current design, you could use `.isNew` property to check wether the document exists in the database or not.

**Comment by ketodiet** [comment]
Hi Pasin,

Maybe I'm missing something but documentWithId will create a persistent document that will be stored in the DB. It's not a volatile 'placeholder'/empty object used for convenience.

This is not so much of an issue for local data as it would probably never happen - but when syncing across devices/ machines it is an issue.

 Let me explain:
- On device X we create doc A with a property of doc B.
- On device Y only doc A has been synced (for whatever reason, e.g. network connectivity)
- Calling A.B on device Y will create an empty document which will stored in the local DB (on Y), with the same Id as the not-yet-synced B doc and ready to be pushed once the device is online. This in itself will most likely create a conflict etc.

This sounds wrong to me. Looking at the code seems to me this is a simple error as the next statement checks to see if the document is nil (i.e. the intention was probably not to create it in the first place?).

Thank you

**Comment by pasin** [comment]
I could see your point about that the empty is saved and results to conflict. 

@snej What do you think about returning nil for the relationship doc if the doc doesn't exist?

**Comment by snej** [comment]
No, it should be documentWithID. The relationship exists even if the document it points to hasn't been synced yet. The object graph will be eventually consistent: when the replicator pulls the target doc, the CBLDocument in memory will be populated with the real contents.

>documentWithId will create a persistent document that will be stored in the DB

No, it's only stored into the DB if you save it. It has the same existence as an untitled document in TextEdit, for example.

**Comment by ketodiet** [comment]
@snej Any save will commit it. Even backgrounding the app will commit it - so there is no avoiding the save. Is there a reason we want to create a doc for a property getter? thanks.

**Comment by snej** [comment]
The doc shouldn't be saved unless you make changes to it. If it does, that's a bug in CBLModel.

**Comment by ketodiet** [comment]
That's pretty likely though, after all that's a doc that was created on access as a result of the user either browsing or editing. In any case, this is a real issue for us and I have changed the behaviour in our codebase to return `nil` by overriding `modelWithDocID:forProperty:ofClass:` -- If you think that this may create some other issues please let me know. Thanks.

**Comment by brendand** [comment]
I for one have always been used to checking for a related object's property to see if it's nil or not and having CBL create one automatically just for checking has caused some definite complications in my code. If it could return nil if it doesn't exist, that would be ideal. And just because the property exists, doesn't mean an object on the other end of the relationship should exist.

You might want to do something like:

if (contact.address) {
   // do something with the contact's address
} else {
   // Tell the user the contact doesn't exist
}

And if you call CBLModel saveAllModels, as I do frequently, then you'd end up getting a contact's empty address object saved.

And looking at it from the inverse relationship, you might want to ask an Address object if it has a Contact associated with it for whatever reason. But just by asking you'll get one, which isn't right.

Just my opinion. Sorry for chiming in here, but this has affected me a bunch of times. Occasionally I've had to work around this by checking the CBLModel's CBLDocument's properties to see if the relationship exists in the dictionary. That way I avoid the automatic creation of the related CBLModel instance.

**Comment by jayahariv** [comment]
Closing 1.x issue!
