### ISSUE TITLE
Authentication fails while configuring replication 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2084]
--------
* Version:   665
* Client OS: iOS

### Steps to reproduce : 
1. Replicate configuration with user1 
2. Configure replication with session authenticator.
3. with urlEndPoint
4. Start the replication 

### Result : 
 401 authorized error is thrown.

### cbl logs : 
 https://gist.github.com/sridevi-15/e2e0a1253525579739c02b3b91863236

It works fine on 447

**Comment by sridevi-15** [comment]
swift code for replication configuration : 
case "replicatorConfiguration_configure":
https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/ReplicatorConfigurationRequestHandler.swift#L46 

swift code to start replication : 
case "replicator_start":

https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/ReplicatorRequestHandler.swift#L25

**Comment by pasin** [comment]
I tested both Swift BasicAuthenticator and SessionAuthenticator manually. Both of them works.

I also copied ValueSerializer and Memory class from the TestServer and tested as below:
```Swift
let memory = Memory()
 let sessionAuth = SessionAuthenticator(sessionID: "f40f1ed5d7cda6122049ca57eed1c4749a5c592d")
let key = ValueSerializer.serialize(value: sessionAuth, memory: memory)
let value: Any? = ValueSerializer.deserialize(value: key as? String, memory: memory)
let sessionAuth2 = value as! Authenticator
NSLog("\(sessionAuth2)")
```
The sessionAuth2 value is printed correctly.

I'm not sure what the issue is now.

**Comment by pasin** [comment]
The cause of the issue is at this [line](https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/ReplicatorConfigurationRequestHandler.swift#L53), and it turns out to be a Swift [bug](https://bugs.swift.org/browse/SR-3871). It worked before in the previous build because the previous build uses Objective-C CBLAuthenticator class via type aliasing. We are now using pure Swift, then it falls into that Swift bug.

As a workaround, change this [line](https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/ReplicatorConfigurationRequestHandler.swift#L53) to the following:
```
let authenticator: Authenticator? = args.get(name: "authenticator") as AnyObject as? Authenticator
// OR
let authenticator = args.get(name: "authenticator") as AnyObject as? Authenticator
```

**Comment by pasin** [comment]
Per chatting with @sridevi-15, the issue was fixed after changing as above.
