### ISSUE TITLE
CBL 1.4.1 Many attachments uploading crashes iOS

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#2130]
When syncing a CBL database that contains a lot of attachments (thousands), CBL is crashing on iOS with a memory issue. There also appears to be a ton of open input streams, which was generating `vnode: table is full` messages in the console log on the device.

This is a screenshot from Xcode showing all the input streams generated (3460 of them).

<img width="1664" alt="cbl-multi-part-uploader-input-streams" src="https://user-images.githubusercontent.com/586075/38219693-0b083c10-3694-11e8-938e-8bdcabf63110.png">

The crux of the problem appears to be that `CBLRestPusher` is creating a `CBLMultipartUploader`, which contains a `CBLMultipartWriter` for every attachment and adding the uploaders to an `_uploaderQueue` before they get processed. This is in the `uploadMultipartRevision:` method.

The `_uploaderQueue` is not throttled, so many thousands of `CBLMultipartUploader` objects can be added to it, filling up memory, then with all these open NSInputStream objects, causing the iOS app to run out of resources most likely and then crash.

Is there a possibility of seeing a fix for this?

The error in the console log in Xcode is simply:

`Message from debugger: Terminated due to memory issue`

I have a sample database which demonstrates this problem that I could send you privately.

--------
* Version:   1.4.1
* Client OS: iOS 11.3
* Server:    CouchDB 2.2.1

**Comment by pasin** [comment]
How many attachments per doc/rev? 

We probably need to implement pause logic for `-uploadMultipartRevision:` method; basically queuing rev (`CBL_Revision`) and processing up to a certain number of revs. I think we could use batcher for queuing and processing the revs.

**Comment by brendand** [comment]
There could be any number of attachments per revision. Up to about 75 - 100 attachments in this test I believe. The database I'm testing has about 4850 attachments total across 397 records.

**Comment by pasamio** [comment]
I've been trying to figure this out myself, I originally reported the issue to @brendand a few days back. I'm not much of a Mac developer so I'm slightly uninformed. I tried to put in a simple semaphore in `-uploadMultipartRevision:` to limit consumption but that didn't work because it looks like it's queuing up the attachments in response to a `_revs_diff` request. Because it's waiting to process the diffs as a response already, it's enqueuing everything and then once it's finished handling the `_revs_diff` response, it starts to drain the queue. It also looks like it goes out to a separate request and then lands back on the main CouchbaseLite thread which is why my semaphore just deadlocked things. Again this isn't an area I've dealt with much so pardon the ignorance/confusion.

**Comment by pasin** [comment]
How about in -uploadMultipartRevision:, instead of queuing uploader objects, queue the `CBL_Revision` rev and upload the rev one by one?

**Comment by brendand** [comment]
@pasin if you have some code to do that, it would be greatly appreciated. The revision is passed in to that method already from higher up in `uploadChanges:fromDiffs:`.

Do you have a good way instead to just block while the `_remoteSession` finishes processing the current `uploader` and doesn't return from `uploadMultipartRevision:` until it's finished uploading?

**Comment by martinrybak** [comment]
I am having the same problem when pushing ~1000 documents with 2 attachments each. App crashes due to excess memory usage.

**Comment by snej** [comment]
IIRC, MultiFileWriter doesn't open all the files ahead of time; instead it saves the paths and opens the files as needed. But I could be mis-remembering; or it's possible that this doesn't work with encrypted attachments since the files can't be sent as-is.

Either way, it shouldn't be hard to add a bit of code there to allow a decrypt function to be spliced in, so the files don't have to be opened all at once.

**Comment by brendand** [comment]
For me it has nothing to do with a document or attachment being encrypted. I was testing with unencrypted documents that had up to 80 or more attachments each.

**Comment by martinrybak** [comment]
Same here. Nothing encrypted.

**Comment by brendand** [comment]
@djpongh What does the icebox label mean? Does it mean you're not going to release a fix for this?

**Comment by pasin** [comment]
@brendand the PR is merged to the master branch. Please check it out. Thanks.
