### ISSUE TITLE
Potential issue that document change events might not be fired if updating docs in batch

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#2133]
@snej pointed out that the [-postDocumentChanged:](https://github.com/couchbase/couchbase-lite-ios/blob/master/Objective-C/CBLDatabase.mm#L769) has the check to not fire the change event if in a transaction. I haven't tested this but pretty much we could have the issue that that document change events might not be fired if updating docs in batch.

**Comment by snej** [comment]
It won't happen if everything happens on the database's queue, because the notifications are all scheduled on that queue, so when they run there won't be a transaction.

But this problem can happen as a race condition if you're using other queues either to change documents or to listen for notifications.

**Comment by pasin** [comment]
It's turned out this has already been fixed in https://github.com/couchbase/couchbase-lite-ios/commit/62427628590c2d3c002a622733c366b2800b72bc.
