### ISSUE TITLE
Verify Purging triggers Database Changed Event

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-ios#2266]
This functionality was recently added to get changed events when documents are expired.

**Comment by jayahariv** [comment]
This test fails, will discuss with @pasin more about this. 

```
- (void) testWhetherDatabaseEventTrigged {
    XCTestExpectation* expectation = [self expectationWithDescription: @"Document expiry test"];
    
    // Create doc
    CBLDocument* doc = [self generateDocumentWithID: nil];
    id token = [self.db addChangeListener:^(CBLDatabaseChange* change) {
        AssertEqual(change.documentIDs.count, 1u);
        NSString* documentID = change.documentIDs.firstObject;
        AssertEqualObjects(documentID, doc.id);
        if ([change.database documentWithID: documentID] == nil) {
            [expectation fulfill];
        }
    }];
    AssertNil([self.db getDocumentExpirationWithID: doc.id]);
    
    // Set expiry
    NSDate* begin = [NSDate dateWithTimeIntervalSinceNow: 1];
    NSError* err;
    Assert([self.db setDocumentExpirationWithID: doc.id expiration: begin error: &err]);
    AssertNil(err);
    
    // Wait for result
    [self waitForExpectationsWithTimeout: 5.0 handler: nil];
    
    // Remove listener
    [self.db removeChangeListenerWithToken: token];
}
```

**Comment by jayahariv** [comment]
discussed with @pasin. will check the unit test in LiteCore, and if thats failing, will raise an issue in LiteCore.

**Comment by jayahariv** [comment]
Initial analysis, LiteCore is sending notification during the purging. Test cases are already present and is working fine.

Seems like the observer also gets called in CouchbaseLite, but seems like the below are is returning due to the c4db_isInTransaction(_c4db) is negative. 
```
CBLDatabase.mm > postDatabaseChanged > c4db_isInTransaction(_c4db) is returning -32. 
```
So due to that it is not going past [here](https://github.com/couchbase/couchbase-lite-ios/blob/f3de6b4eecb7de7d2788dfbdba18ccaabde3294d/Objective-C/CBLDatabase.mm#L721)

**Comment by snej** [comment]
That's odd ... `postDatabaseChanged` is called async on the database's runloop, so why would the db already be in a transaction?

**Comment by jayahariv** [comment]
We debugged and found, callback is fired before the transaction is end. Breakpoints for the `dbObserverCallback` gets fired before the transaction is ended.
<img width="606" alt="screen shot 2018-12-17 at 4 07 38 pm" src="https://user-images.githubusercontent.com/10448770/50123520-ef11ca00-0215-11e9-9eb5-4423e7475692.png">

If we put a sleep inside the `dbObserverCallback`, then it will work fine.
<img width="604" alt="screen shot 2018-12-17 at 4 09 16 pm" src="https://user-images.githubusercontent.com/10448770/50123589-313b0b80-0216-11e9-90f0-691a34baf669.png">

will create a ticket inside the LiteCore.

**Comment by pasin** [comment]
As the call back is called before the transaction ended, there is a race between processing the event (async) and ending the transaction. This seems like the root cause of the intermittently unit test failures on Jenkins when trying to observe whether the doc is still in the database after expired+purge by using DocumentChangeListener.

**Comment by snej** [comment]
Is the call to `c4db_purgeExpiredDocs` happening on a separate thread? Otherwise I don't see how the async `-postDatabaseChanged` could be invoked before the transaction ends, since the queue would still be busy in the purge call.

I think the bug is in `-postDatabaseChanged` -- if the db is in a transaction (on another thread), it shouldn't just ignore the notification; it should wait for the transaction to end and then process it.

**Comment by pasin** [comment]
Yes, c4db_purgeExpiredDocs is happening in a global background queue. I think we could change it to run on `CBLDatabase.dispatchQueue` which is the same queue that we use to post notification.

I'm flagging this as a cross-platform to discuss about -postDatabaseChanged so that all platforms should fix this the same way.
