### ISSUE TITLE
CBLWebSocket CLOSED

### ISSUE THREAD

**Issue by srinadh-k** [couchbase/couchbase-lite-ios#2269]
--------
* Version:   CBLite V2.1.3
* Client OS: iOS
* Server:    Couchbase Server 5.5

CBLWebScoket closed after some time, don't know reason exactly and it happing only in one app whereas i developed other apps it is working fine.

My observation, I restarted my replication 3 times,

1. I started pull replication to get all data from the server.
2. I called my IOT Device Rest APIs and stored locally and stopped previous replication and called push replication to synch my IOT device data to Server.
3. Once push replication completed and then I stopped previous replication and called push-pull replication to sync mobile and server.

Seems it is very serious issue.
https://gist.github.com/srinadh-k/30442635a24805d46dd9ff41af6c8bcd

**Comment by pasin** [comment]
Umm ... look like WebSocket got closed cleanly without stopping the replicator and that caused the continuous replicator to stopped.

**Comment by srinadh-k** [comment]
> Umm ... look like WebSocket got closed cleanly without stopping the replicator and that caused the continuous replicator to stopped.

I just wonder why it is only happening in only one app whereas i developed other app and it is working fine. 
Do you know, is there any settings to configure on Xcode? Whereas I am calling my HTTP Rest API calls in my application, is it any cause? What are the possible causes it might occur? So i will debug it.

**Comment by pasin** [comment]
I don't think you have done anything wrong especially calling the REST API shouldn't affect the replicator. I will need to check with the team about this scenario.

**Comment by srinadh-k** [comment]
ok sure, i will look forward to hearing from you. Where we are planning to go for production and planning to take licensed version from couchbase soon.

**Comment by srinadh-k** [comment]
@pasin  Here you can find my [replication method](https://gist.github.com/srinadh-k/556194dafb53e1fd268bae68b76a7b88) and [complete log](https://drive.google.com/file/d/1C6cZtgFbEazJGuEmFKDVkcLWvCVZj9o9/view)

**Comment by jayahariv** [comment]
Hi @srinadh-k, 

Here is what we analyzed from the replication function you shared. 

1. config.allowReplicatingInBackground = true

When setting the value to true, you will need to create a background task when the app goes into background and restart the replicator manually when the app is foreground. If you want CBL to automatically suspend the replicator when the app is in background and resume when the app is foreground, set the value to false. In most case, you would want to set this to false.

2. self.replicator?.resetCheckpoint()

The replicator will start syncing from the beginning again instead of continuing from the last checkpoint. Please make sure if this is what you want.

3. Regarding this line (https://gist.github.com/srinadh-k/556194dafb53e1fd268bae68b76a7b88#file-replication-funtions-L60), If you want to stop the replicator when it’s idle, set config.continuous to false.

**Comment by srinadh-k** [comment]
@jayahariv I understood now, But when i set config.allowReplicatingInBackground = true and created a background task but iOS giving certain time interval for this and even we can not tell how much time it is allocated for our replication works but if I run background music, replication working as like in the foreground, But again here apple has some guidelines on this.

**Comment by jayahariv** [comment]
@srinadh-k did you tried `UIApplication.shared.backgroundTimeRemaining`? This will give the amount of time the app has to run in the background before it may be forcibly killed by the system

**Comment by srinadh-k** [comment]
I will check it  UIApplication.shared.backgroundTimeRemaining and let you know. But i hope we can close this ticket Because you're right I am stopping replication forcefully.
