### ISSUE TITLE
Convert string to int in ORDER BY expression

### ISSUE THREAD

**Issue by Effe76** [couchbase/couchbase-lite-ios#2286]
Hi everyone,

I have some documents on my server that have a **date** field, this field has to be a **String**
(related to an IBM server we use to persist the data)

For example today's date is **"20181217"**

I need to perform a simple **order by**, I was able to achieve this in the couchbase server Query tab:

```
SELECT *
FROM dbname
ORDER BY TO_NUMBER(date) DESC
```

I tried the same on iOS but I couldn't find a way to parse the Int of the date String

```
let query = QueryBuilder
.select(SelectResult.all())
.from(DataSource.database(myDB))
.orderBy(Ordering.property("date").descending()) // Performs orderby with the string
```
Could you please give me a tip? 
Thank you very much

--------
* Version:   2.1.3 (swift)
* Client OS: iOS 12.0
* Server:    Couchbase EE 5.5

**Comment by snej** [comment]
In this case it doesn't matter, because if the strings are always the same length (8 digits) they'll sort the same as numbers.

Please ask questions on the [Couchbase web forum](https://forums.couchbase.com/c/mobile) or the [Couchbase Mobile mailing list](https://groups.google.com/forum/#!forum/mobile-couchbase). We use Github issues only for bug reports and feature suggestions. Thanks.
