### ISSUE TITLE
Replication-eventing listener is not able to catch the errors thrown for conflicts

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-ios#2287]
* Version:   2.5.0-111
* Client OS: iOS
* Server:    CBS 6.5.0-1813

I working on testing the scenario "Replication Event - error". This what I'm trying to achieve the error event.
   ```
    1. Create docs in CBL and replicate to SG using push one-shot replication
    2. Add update to SG and CBL to create conflict
    3. Add replication event listener for the replication and start push/pull one-shot replication.
    4. Check the error is thrown in replication event changes
```

I can see the error thrown for conflict in app logs, but those errors are not registered on event listener.

This is the test I've written (code is not complete to validate all scenario for this test) - https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl2.5-replication-eventing/testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_replication_eventing.py#L153

**Logs -** 
Logs from python runner - [cbl_python_test.log](https://github.com/couchbase/couchbase-lite-ios/files/2689201/cbl_python_test.log)
Logs for App from Xcode console - [xcode_test.log](https://github.com/couchbase/couchbase-lite-ios/files/2689202/xcode_test.log)

**Comment by pasin** [comment]
Instead of during push and pull one-shot, I think you should break down the test to do push and pull separately. Otherwise you will need to handle the race between push / pull in the test when pull replicator is trying to resolve the conflict.

Please reopen the issue if the push replicator encounters the conflict but the event doesn't have the conflict error.
