### ISSUE TITLE
Swift 5.1 with Carthage

### ISSUE THREAD

**Issue by ph1lb4** [couchbase/couchbase-lite-ios#2526]
The prebuilt binary is not compatible with the current XCode beta and Swift 5.1.
Is there any way to build couchbase yourself without using the prebuilt
`binary "https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Community.json" ~> 2.1.6`

**Comment by jayahariv** [comment]
for building from the source, you can refer [this section](https://github.com/couchbase/couchbase-lite-ios#how-to-build-the-framework-files)

Make sure the command line tool chooses the latest beta Xcode, since the script uses `xcodebuild` command. 

Also for questions like this, you can use the [Couchbase forums](https://forums.couchbase.com/c/mobile/couchbase-lite)

**Comment by ph1lb4** [comment]
Thanks, worked fine. Maybe you can add to your documentation that you need `doxygen` installed for the script to work. Otherwise you will encounter a build error.
