### ISSUE TITLE
2.7.1 support for Swift 5.1.3

### ISSUE THREAD

**Issue by johnngoi** [couchbase/couchbase-lite-ios#2644]
*** Downloading CouchbaseLite-Enterprise.framework binary at "2.7.1"
Incompatible Swift version - framework was built with 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51) and the local version is 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15).

**To Reproduce**
1. `carthage update` == 2.7.1

**Expected behavior**
Carthage update to succeed on Xcode 11.3.1 on Swift 5.1.3

**Comment by jayahariv** [comment]
IIRC, Carthage had the fix available in the master. But new release was not scheduled. 
https://github.com/Carthage/Carthage/issues/2887

Even if you fix the version lock with Carthage, the binary might not work in previous Swift compiler. There was a serious bug got fixed in Swift 5.2, which is causing an issue in Swift 5.1.3. Recommendation is to upgrade it to use the latest Swift. 

https://forums.swift.org/t/cant-use-framework-compiled-with-swift-5-2-in-swift-5-1-3-project/35248/4

**Comment by johnngoi** [comment]
Accepted, we will work on upgrading to Xcode 11.5, Swift 5.2+
