### ISSUE TITLE
CouchbaseLite includes UIWebView, can it be changed to WKWebView?

### ISSUE THREAD

**Issue by zixingxuan** [couchbase/couchbase-lite-ios#3041]
Using pod 'CouchbaseLite', listing on the App Store is rejected, through grep -r UIWebView.

**Comment by jayahariv** [comment]
CouchbaseLite is not using UIWebView, you can confirm same by running on CouchbaseLite binary(below is the XCFramework search, but you can do same on pod binary)
```
nm CouchbaseLiteSwift.xcframework/ios-arm64_armv7/CouchbaseLiteSwift.framework/CouchbaseLiteSwift | grep -i UIWebView 
nm CouchbaseLiteSwift.xcframework/ios-arm64_i386_x86_64-simulator/CouchbaseLiteSwift.framework/CouchbaseLiteSwift | grep -i UIWebView 
nm CouchbaseLiteSwift.xcframework/ios-arm64_x86_64-maccatalyst/CouchbaseLiteSwift.framework/CouchbaseLiteSwift | grep -i UIWebView 
```

When looking at the dSYM file in the textfile, reference to UIKit functions and types can be seen,  "iPhoneSimulator14.5.sdk/System/Library/Frameworks/UserNotifications.framework/.hUIWebView.. UIWebViewNavigationType.. etc..,". This would be due to the reference of UIKit & iOS SDK which is causing the string match of UIWebView. 
[similar discussion](https://github.com/mapbox/mapbox-gl-native/issues/15559#issuecomment-528128516)
