### ISSUE TITLE
1 GB Push replication with attachment fails

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#328]
Edit the value of "kSizeofAttachment" to 1 GB in the script https://github.com/couchbaselabs/iOS-WorkerBee/blob/third_installment/Tests/Test13_PushReplicateWithAttachment.m and execute it. 
Please configure the sync gateway to use in memory walrus database. The test displays the replication is complete but there is no document found on Sync Gateway

**Comment by snej** [comment]
Pasin says he found that pushing a doc with a huge attachment (too big to fit in memory) would fail (or crash?) when running on a real iOS device. From the backtrace it looks as though the attachment gets loaded into RAM and expanded into base64 — that shouldn't be happening, its metadata should have a `"follows"` key instead of `"data"` and the data should be sent as a separate multipart body.

**Comment by pasin** [comment]
I think I have a little bit old code that doesn't have https://github.com/couchbase/couchbase-lite-ios/commit/503f00066a95fb3d5de4f2372f50fc8557dc7aa2 commit. Let me retest it.

**Comment by pasin** [comment]
Still has the same problem. The attachment is always expanded. I tried to follow the codes and found that the following block returns stub attachment dictionary even though the follow attribute is YES but changing that part of code alone doesn't work (leading to a new issue that doc doesn't get store). 

https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLDatabase%2BAttachments.m#L345

**Comment by snej** [comment]
Yes, I think this has been broken for at least a few months. The attachment related code has gone through changes twice lately — once for ForestDB and again to support streaming. I think I broke this in one of those.
