### ISSUE TITLE
Vector search is not available even though I installed enterprise version with pod

### ISSUE THREAD

**Issue by eakarsu** [couchbase/couchbase-lite-ios#3316]
import CouchbaseLiteSwift

I included this line in my app

I installed enterprise version like this

target 'test' do
  platform :macos, '10.15'
  use_frameworks!
  pod 'CouchbaseLite-Swift-Enterprise'
end 

But I am getting this error;

Cannot find 'VectorIndexConfiguration' in scope 

I am getting this error when I run couchbase lite enterprise in Mac os with swift language 

Is there anything I am doing wrong?

**Comment by velicuvlad** [comment]
I suspect that the issue arrises from the fact that the pod version is incorrect. 

For Vector Search, due to being a pre-release, you will have to specify the exact version either by number or git&tag.

`pod 'CouchbaseLite-Swift-Enterprise', '3.2.0-beta.2'`.
https://docs.couchbase.com/couchbase-lite/3.2/swift/gs-install.html

**Comment by eakarsu** [comment]
I did

I missed vectorextension plugin setup
All is working great
Thank you


Erol Akarsu
