### ISSUE TITLE
Excess attachment folder issue

### ISSUE THREAD

**Issue by timshiueab** [couchbase/couchbase-lite-ios#440]
Hi All,

I'm a newbie in using Couchbase Lite and I found that it is the best No-SQL database for mobile with easy to use API to manipulate documents and synchronise data with server.
Our project team will make use of the attachment functions to attach some files to documents and sync. them to other devices.

However, we found that a new folder, named "(A Document being saved …..", will be created for each setAttachment function call that they are empty folders and will be accumulated even we call compactDB function.

I would like to ask if there is any automatic housekeeping mechanism in CBL that will clear those folders?

Thanks a lot.

**Comment by lisacmer** [comment]
I'd like to add, that if a number of folders on iOS gets to 1000, you'll get yourself into the situation with all kinds of unfortunate consequences. OS won't let you create any other directory with NSItemReplacementDirectory, which may lead to replication failing with 502 error, or any file with NSDataWritingAtomic, which in our case, since we are using CocoaLumberjack FileWriter, lead to tremendous slowdown of our app.
Unfortunately 500 launches of our app (since we have 2 databases) did not get a decade to reproduce.
Note, that https://github.com/couchbase/couchbase-lite-ios/commit/77f01018fb6f5fc717a925b691b30f55aa5094e6 somewhat fixes the problem (since if app crashes the directory doesn't get removed anyway), however it's your responsibility to close database, or the whole CBLManager, for example in applicationWillTerminate call.
