### ISSUE TITLE
CBLModel: remove -initWithDocument: from the public API

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#521]
-initWithDocument: is dangerous: it can be called with a nil document by accident, which leaves the instance in a confused state where it will later fail assertions, e.g. when you set properties on it. The documentation for -initWithDocument: tries to spell out how it's safe to use it, but doesn't really; it's just too confusing.

Subclassers do need a place they can initialize ivars in a new instance. I can add a new public method that's called during initialization, that they can override to do that.

**Comment by nl** [comment]
After making those changes, I get an assertion fire whenever I try to set properties on a (new) document in awakeFromInitializer. https://gist.github.com/nl/67fc4cf3eee4511a1a92

**Comment by pasin** [comment]
Reopen the issue. This is a bug. The internal document will get created when the database is set, which is after the awakeFromInitializer is called.

**Comment by pasin** [comment]
@nl, I did fix the issue. Could you check it out?

**Comment by tleyden** [comment]
> After trying both one and two init method implementation, I think I prefer adding the database param to the initWithDocument. It feels better and cleaner.

Do the api docs need to be updated?

**Comment by snej** [comment]
> Do the api docs need to be updated?

Yeah; the release-note text I posted earlier describes what changed. The header-docs have been updated, but since we don't have versioned docs on our portal we can't update those until 1.1 is released.

**Comment by Jamiltz** [comment]
Tried using the new changes with swift.
Ran into compiler errors because objective-c convenience constructors (class methods) are bridged to Swift as convenience initializers (see http://stackoverflow.com/questions/24295476/swift-can-not-use-nsimage-imagenamed?answertab=votes#tab-top).
So `+ (instancetype) initWithDocument:` is bridged to `init(document: Document)` as a swift convenience init.
When adding a custom initializer in swift models, the compiler enforces to call a designated initializer.
![screen shot 2015-03-01 at 22 01 51](https://cloud.githubusercontent.com/assets/2589337/6433143/b97d3e9e-c05e-11e4-9e31-aab695ac6acc.png)
It seems that we need to expose a designated init in the public API for compatibility with Swift initialization rules.

**Comment by snej** [comment]
With the recent API change, you shouldn't have an initializer in a CBLModel subclass, and you shouldn't instantiate models by calling initializers. Instead, you should override `-awakeFromInitializer` to perform initialization tasks.

**Comment by SteffeyDev** [comment]
In all of my models I had an initializer override method that could accept custom parameters, and I would only call it when I created the document so that it would initialize with the correct values that once but not when I went to access the document again.  I did not use the newDocumentInDatabase method because I wanted to use my own IDs, so it seamed easiest to get the document from the database with

<code>var doc = database!["custumDocumentID"]</code> 

and then initialize it with 

<code>var newModel = Model(forDocument: doc, custumOption: "stuff")</code>

My override method would then initialize with the custumOption params.

I am trying to make some changes of my own, but just ran into your change.  What is the best way to handle this case with the new setup?

**Comment by snej** [comment]
The problem with creating a Model object via an initializer is that there can be only one Model instance per document, so if you tried to initialize a new instance with a document that already had a Model instance, it would have to fail. That's part of the reason why you now have to instantiate models via +modelForDocument.

In your case it sounds like you should create a class method to create a new model.

**Comment by Sergey-Lomov** [comment]
Please, update example at http://developer.couchbase.com/documentation/mobile/current/develop/guides/couchbase-lite/native-api/model/index.html it item "Custom initializer methods"
