### ISSUE TITLE
View not indexing older revisions

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-ios#578]
This issue was originally reported for CBL Android. I observed same issue with CBL iOS

For details, please refer https://github.com/couchbase/couchbase-lite-android/issues/494

**Comment by snej** [comment]
Yup, I reproduce it too. The problem is that the revision that was just added is a deletion, and the SQL query used by the view indexer skips deletions since they normally don't get indexed. But in this case the deletion makes an earlier revision become the winning one.

It looks like the quick fix is to remove `AND deleted=0` from that query. Unfortunately that will slow down indexing somewhat, because the main loop will scan deletions even though 99% of them aren't relevant. I can think of better fixes but they involve larger changes (including to the db schema.)
