### ISSUE TITLE
Redirection of source document not working?

### ISSUE THREAD

**Issue by marbetschar** [couchbase/couchbase-lite-ios#626]
I've trying to establish what is described over here:
http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/view/index.html#verboten

I've got several person documents belonging to several group documents. What I'm trying now is to get all group documents which are in a relation to any person.

The models look like:

    @objc(Person)
    class Person: CBLModel{
    @NSManaged var groups: NSArray
	class func groupsItemClass() -> AnyClass{
		return Group.self
	}
    }

    @objc(Group)
    class Group: CBLBeanABSync{
	@NSManaged var value: NSString?
    }

And the view's code:

    self.views["used"] = self.database.viewNamed("used")
    self.views["used"]??.setMapBlock({ (doc, emit) -> Void in
			if let type = doc["type"] as? String{
				if let groupIDs = doc["groups"] as? [String]{
					for groupID in groupIDs{
						emit(doc["_id"],["_id": groupID]) //setting _id as value is redirecting documentID to group object, access sourceDocumentID for emitting object
					}
				}
			}
    }, version: "11")

After executing the query i output the following in the console:

    println("Used groups: \(groups.count)")
    println("\(groups.rowAtIndex(0).sourceDocumentID)")
    println("\(groups.rowAtIndex(0).documentID)")

With the following result:

    Used groups: 5
    4026729B-52DD-4613-A911-2C21DE3D7DC4
    4026729B-52DD-4613-A911-2C21DE3D7DC4

Why are both ID's equal? As far as I've understood the documentation the sourceDocumentID should point to the person and the documentID to the group?

Please note: There is no need for grouping the results since I need every group <-> person relation for syncing purposes.

**Comment by snej** [comment]
It took me a while to figure out the problem! I haven't used this "linked docs" feature in a long time. It turns out the documentation is wrong, or at least is forgetting to say that this only has an effect if you set the `prefetch` property of the query, which causes the document contents to be returned as well as the key/value.

(["Linked docs" comes from CouchDB](http://wiki.apache.org/couchdb/Introduction_to_CouchDB_views#Linked_documents); it's used with the `include_docs` parameter to cause a different document's body to be inlined into the response. In CBL it's of questionable usefulness.)

You can work around this by getting the linked doc ID out of `row.value["_id"]` and asking the CBLDatabase for the document.

**Comment by snej** [comment]
Fixed it on the master branch, but you may want to stay on stable ground and just use the workaround for now.

**Comment by marbetschar** [comment]
You've made my day!! That did the trick!

btw: Why are you saying that this feature is of questionable usefulness in CBL?
Is there a better way to achieve what I'm trying to do?

**Comment by snej** [comment]
Well, effectively all it does is change what the `documentID` and `document` properties of the query row will return. Which you could do otherwise by saying `((NSDictionary*)row.value)[@"otherDocID"])` instead of `row.documentID`, or something like that.

In CouchDB it's more useful because one frequently uses the `include_docs` query option to get back a query result and the contents of the associated documents in one HTTP call. A workaround like the above would result in a lot of extra HTTP calls to get the other documents. In Couchbase Lite the database is in-process so there's much less overhead in making multiple calls.
