### ISSUE TITLE
Replicator not go offline in airplane mode + bluetooth on

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#627]
When turn the airplane mode with bluetooth on, SCNetworkReachability reports reachable with isDirect flag on. As a result, the replicator goes/stays online but eventually the replicator will get connection timeout as it cannot connect to the server.

Below is definition of the IsDirect flag. Look like the Reachability tried to send a package to the remote host (raw ip address via bluetooth)?

```
kSCNetworkReachabilityFlagsIsDirect
Network traffic to the specified node name or address will not go through a gateway, but is routed directly to one of the interfaces in the system.
```

**Comment by snej** [comment]
You mentioned this came up in P2P replication. What is the hostname of the remote server? If it's something discovered over Bonjour like `10.0.1.30`, then SCNetworkReachability is correct, because that address _is_ potentially reachable using IP-over-Bluetooth. (Actually I think the IP-over-BT addresses may be in the self-assigned area at `192.*`...)

**Comment by pasin** [comment]
Yes, the ip-address is in 10.x.x.x range. I think the SCNetworkReachability reported correct flag. I was confused when I tested the replication with the SyncGateway and I expected the replicator to go offline. 
Should we have a replicator option like includesPeerToPeer so we can take 'reachable via direct network' as an offline if 'includesPeerToPeer' option is set to false?

**Comment by snej** [comment]
I think a property like that is a good solution — make it a key in the `options` dictionary since I don't think it'll be commonly enough needed to justify adding it to the API.

I'm just not sure about the name. It's more specific than peer-to-peer … it's about being able to connect over BlueTooth, which only applies to other Apple devices as far as I know. So if you're making a P2P connection to a local Linux server or to an Android device, you would want this option set to false.

Maybe `includesBluetooth`?

(Also, I think you can detect the exact situation described here by using other APIs in the SystemConfiguration framework to check what network interfaces are up. If only Bluetooth is on, you know you're in this situation.)

**Comment by pasin** [comment]
A couple things:
- SCNetworkConfiguration is only available for OSX. An alternative method to get a list of the active network interfaces is using getifaddrs() method.

**Comment by pasin** [comment]
As we will need to have a dependency to Core Bluetooth and this issue is not really a bug or has high priority / severity, I think we could park the issue and watch to see if there are any other people having problems with this or not. Closing the issue for now.
