### ISSUE TITLE
CBLIncrementalStore - Can't fetch on relationship

### ISSUE THREAD

**Issue by gedward** [couchbase/couchbase-lite-ios#628]
Trying to use couchbaselite with CBLIncrementalStore on v1.0.3.1. Attempting to perform a fetch with a predicate that involves a relationship does not work. Able to reproduce using the cblite-coredata-sample-ios project. Here is my fork to reproduce issue: https://github.com/gedward/cblite-coredata-sample-ios

Notice line 233 in RecipeListTableViewController.m: ```NSPredicate *predicate = [NSPredicate predicateWithFormat:@"type.name CONTAINS[c] %@", @"s"];'''

This fetch request returns 0 objects, even though many of the types should conform to that predicate.

**Comment by pasin** [comment]
I believe the issue was fixed in the master branch (9a958d8b8cb4add786c622c3e573c768c9759ce6 and bb8f632c9cee221598232afc059757080233f8e7). Also please make sure to setup an inverse relationship to your to-many relations. Currently CBLIncremenatalStore only supports and was optimized to-many relationship with inverse relations. 

To build the library from the master branch : https://github.com/couchbase/couchbase-lite-ios/wiki/Building-Couchbase-Lite.
