### ISSUE TITLE
Enumerate sequence in descending order in CBForest not working

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#641]
To check the issue:

1. adding the following method to the Database_test in CBForest=iOS Tests:

 ```Objective-C
 - (void) test0X_EnumerateSequenceDescending {
    auto opts = DocEnumerator::Options::kDefault;
    opts.descending = true;

    [self createNumberedDocs];
    NSLog(@"Enumerate over all sequence, descending:");
    int i = 100;
    for (DocEnumerator e(*db, 1, UINT64_MAX, opts); e.next(); --i) {
        AssertEq(e->sequence(), (sequence)i);
    }
    AssertEq(i, 0);
}
```

2. Comment out these 2 lines as forestdb.fdb_iterator_sequence_init() method doesn't allow start_seq > end_seq:
https://github.com/couchbaselabs/cbforest/blob/master/CBForest/DocEnumerator.cc#L102-L103

Found Issue:
In cbforest/DocEnumerator.css, the fdb_iterator_seek_to_max() method is called to init the current position of the iterator but the fdb_iterator_seek_to_max() method requires the iterator to have 'key'. 
See the following code references:
https://github.com/couchbaselabs/cbforest/blob/master/CBForest/DocEnumerator.cc#L111-L116
https://github.com/couchbase/forestdb/blob/master/src/iterator.cc#L1438-L1440

**Comment by snej** [comment]
In your step 1 you have the sequence numbers backwards — should be `..., UINT64_MAX, 1, ...` since the starting sequence is the larger one. So step 2 (modifying ForestDB) isn't needed.

But you're right that fdb_iterator_seek_to_max is broken. I've [filed a Jira issue](https://issues.couchbase.com/browse/MB-14220).

Unfortunately there's no good workaround. Iterating forwards and saving the sequences in an array, then reversing it, could take a long time and use a lot of memory, since the number of sequences equals the number of docs in the database.

**Comment by snej** [comment]
I've pinged the FDB team via a comment in their Jira ticket.

**Comment by snej** [comment]
Sundar replied "I was thinking of getting to it sometime later this month."

**Comment by snej** [comment]
I've worked around this as part of some other enumerator work I was doing. CBLDatabase now always requests the docs from the storage object in ascending order, and reverses them afterwards.
This is on a branch now but I'll merge it soon.

**Comment by snej** [comment]
Merged the fix into dev.
