### ISSUE TITLE
Create OS X build product

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-ios#655]

**Comment by snej** [comment]
Should just be an addition to the Jenkins build script. It needs to build the `CBL Mac` and `CBL Listener Mac` targets. Note that the build products have the _same names_ as the iOS ones, so they need to be kept in separate folders clearly labeled as being for Mac OS.

**Comment by pasin** [comment]
@ashvindersingh, could you also add test the OSX build in your XCODE server as well?

**Comment by pasin** [comment]
Per talking with @ashvindersingh, Ashvender will talk to the build team to setup the jenkin build for OSX.

**Comment by michaelkwok** [comment]
So we are looking to add mac-osx build on top of the existing iOS for couchbase-lite-ios.  I like to confirm a few things.
1. which xcodeproj does it use?
2. any additional dependency?
3. any new build instructions?

**Comment by snej** [comment]
Same Xcode project. See my comment above on what targets to build.

**Comment by michaelkwok** [comment]
I will add those 2 targets for MAC.  I also need to update the build script to separate the mac vs ios builds.

**Comment by pasin** [comment]
@michaelkwok, thanks a lot for your help.

**Comment by michaelkwok** [comment]
Here are a few changes right off the bat.
1. Currently, ios package is comprised of cbl ios, cbl listener ios, liteserv, etc.
    For macosx package, it be cbl mac, cbl listener mac, liteserve, etc.
2. I think it would make more sense to change the package name from couchbase-lite-ios-xxx.zip to couchbase-lite-macosx-xxx.zip since the final product is actually a macosx.  That's something I can do so let me know if you see any drawback.
3. Archive both mac and ios to latestbuilds for internal consumption.
4. Stop putting builds on S3.

**Comment by michaelkwok** [comment]
In #4, I am referring to internal builds.  Release builds still go to S3.

**Comment by snej** [comment]
> I think it would make more sense to change the package name from couchbase-lite-ios-xxx.zip to couchbase-lite-macosx-xxx.zip

Are you creating a _new_ package? If so, yeah, that's a good name.

**Comment by ashvindersingh** [comment]
I have added the Mac Unit tests to Xcode server. The tests will run once daily.

**Comment by michaelkwok** [comment]
@snej, I have created the new macosx as a separate package.  The macosx build generates this library Release-CBLJSViewCompiler-ios-universal/libCBLJSViewCompiler.a, same as the ios build.  Does macosx need to include this library?  The reason I ask is because the name ios package includes this library. But the name Release-CBLJSViewCompiler-ios-universal almost suggest it's not for macosx.

**Comment by snej** [comment]
Nope, just ignore that library in the Mac build.

**Comment by michaelkwok** [comment]
The job build_cblite_ios_master is now building both ios and macosx.  All results are now kept in our internal latestbuilds.

http://latestbuilds.hq.couchbase.com/couchbase-lite-ios

**Comment by snej** [comment]
:+1: For the record, Pasin and I found some issues with the content of the archive and Michael is fixing them now.

**Comment by michaelkwok** [comment]
Jens/Pasin, can you make sure I didn't strip too much from macosx and also verify ios builds are the same as before?  Nothing changed on ios but I just want to make sure I didn't overlook something.

http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/macosx/0.0.0/0.0.0-378/
http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/ios/0.0.0/0.0.0-378/

**Comment by pasin** [comment]
I checked the OSX framework structure with Jens and it seems to be correct now.

A couple things apart that:
1. There is no documentation zip files included in the macosx folder. Technically, the content of the ios and osx documentation is the same.
2. Can you also remove JavaScriptCore.framework from ios's Extras folder? The file is no longer needed as we stop supporting iOS6 and removing it will make the zip file smaller as well.

**Comment by michaelkwok** [comment]
I have removed JavaScriptCore.framework from ios "Extras".  Thanks!

**Comment by pasin** [comment]
I think this task is done. Close the issue now. Thanks a lot @michaelkwok .
