### ISSUE TITLE
Temporary folder not getting removed?

### ISSUE THREAD

**Issue by jschofie** [couchbase/couchbase-lite-ios#664]
Hey,
I wasn't sure if this was an issue or something I'm doing but I was curious to see how attachments get saved so I created a small unit test and when I looked into the container/sandbox I noticed a folder named something like ... (A Document Being Saved By <Name>)

Also, it doesn't look like it gets removed. I've run the test a number of times and a new folder gets created.

I'm not sure if this is related to setting the attachment but this "seems" to be the case.

Sample Code:
```swift
   func testAddAttachment() {
        var error: NSError?
        
        let person = Person(document: database!.documentWithID("75"))
        person.setAttachmentNamed("edit.png", withContentType: "image/png", content: UIImagePNGRepresentation(UIImage(named: "Edit_icn")))
        person.setAttachmentNamed("calendar.png", withContentType: "image/png", content: UIImagePNGRepresentation(UIImage(named: "Calendar_icn")))
        person.save(&error)
    }
```

**Comment by pasin** [comment]
The .blobtmp folder should get moved into the main attachment folder and renamed to .blob after the document is saved. What version of CBL are you observing this behavior?

**Comment by jschofie** [comment]
I'm using couchbase-lite-ios (1.0.3.1).

**Comment by snej** [comment]
@pasin, the report is about the "A Document Being Saved By..." directory not getting removed, not about the attachment file itself.

@jschofie: I think this got reported once before. Couchbase Lite doesn't create that directory itself; it asks the OS for the location of the `NSItemReplacementDirectory`. That call implicitly creates the directory if it doesn't exist. Since we don't directly create the directory, we shouldn't delete it either. (Source code is in `-[CBL_BlobStore tempDir]`.)

I believe this directory gets reused, though, so it shouldn't cause problems.

**Comment by snej** [comment]
Found the original — this is a dup of #440, which we decided wasn't worth fixing since it creates at most one excess (empty) directory per launch of the app. So yes, it's a resource leak, but an extremely slow one that would take decades to create any noticeable effect.

**Comment by jschofie** [comment]
Hi @snej,
I'm seeing more than one directory get created. Not sure if this is an Apple regression or not but probably something that should be investigated?

![screen shot 2015-04-16 at 12 21 34 pm](https://cloud.githubusercontent.com/assets/11754591/7185818/5e936eec-e433-11e4-852b-4cf0f9ad70e7.png)

**Comment by jschofie** [comment]
I should note, I ran that unit test 3 times and got a new folder each time.
