### ISSUE TITLE
Multipart streams cannot be reopened when retrying to send the request

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#665]
When the CBLMultipartUploader retries to send a new request after the previous one was failed according to the retry logic, the app crashes due to an assertion `_bufferLength > 0` failure in CBLMultiStreamWriter's writeToOutput method. 

The root cause of the crash is that the body streams inside the CBLMultiStreamWriter have already been opened and cannot be re-opened - The streams are needed to be re-created.

**Comment by snej** [comment]
FYI, there was a bug in this patch that we didn't catch, which I've now fixed with commit a8fb03d:

If a CBLMultipartWriter created by CBLRestPusher needed to retry the
request (on auth challenge or redirect), it would get a new body stream,
but the new stream would have a different random multipart boundary
string. Unfortunately the old boundary was still encoded in the
Content-Type header. The resulting HTTP body would be unparseable :(

Fixed by making sure to create the new body with the same boundary.
