### ISSUE TITLE
iOS 8.2+ seems slower than 8.1 or lesser

### ISSUE THREAD

**Issue by agonyou** [couchbase/couchbase-lite-ios#684]
Customer has an issue when the app syncs on a channel before getting to the home screen. 
From customer input: 
Our app currently functions by doing a channel-based sync up front (during login/registration) before guiding the user to the actual home screen. This used to be fairly quick, but since 8.2 the network seems to get throttled for the last 30% of the documents. The total load time ballooned to over an hour in some cases.

**Comment by agonyou** [comment]
An update from the customer:

"We have done another round of testing and the signing process is significantly slower between iOS 8.1.2 and 8.2 plus. Actually the process goes from 1-1.5 minutes to north of 20 minutes on iOS 8.2+. 

One interesting thing that Chris pointed out to me is: when the connection slows, it seems to sync documents in exact multiples of 200. 

It also seems that the first 1%-1.5% of the documents always syncs very quickly but the process slows down significantly after that regardless of the total number of docs.

Again this is only happening on iOS 8.2+"

**Comment by snej** [comment]
What's the "signing process"? Is that a typo for "syncing"?

What version of Couchbase Lite?

Please ask the customer to profile the app in Instruments using the Time Profiler, and save the profile and send it to me. 

(Is there any reason the customer can't post here themselves? That would be easier than going through you.)

**Comment by agonyou** [comment]
I believe it is syncing. I'll forward them the issue and let them know they can post.

Austin Gonyou
Couchbase   Always Scalable, Always on NoSQL
Solution Engineer, Northeast US
719-659-5806
@agonyou

On May 5, 2015, at 12:55 AM, Jens Alfke <notifications@github.com<mailto:notifications@github.com>> wrote:


What's the "signing process"? Is that a typo for "syncing"?

What version of Couchbase Lite?

Please ask the customer to profile the app in Instruments using the Time Profiler, and save the profile and send it to me.

(Is there any reason the customer can't post here themselves? That would be easier than going through you.)

**Comment by sapieneptus** [comment]
Hey @snej - me again. It is the syncing process that is slow in iOS 8.2+. Here is as much info as I have been able to gather so far:

Turning on logging `Sync` reveals that the app is able to insert some percentage of the initial documents very quickly, but then starts taking a long time to insert. It batches up 200 for insert, and then takes on average more than 7 seconds to insert the batch. 

Turning on logging `SyncVerbose` reveals that during these long inserts, we get a bunch of statements like so:
```
CBL_Puller[https://gateway.mycomfort.xyz/db_3_19_14_2] inserting module::ge_billerica_generator_and_grounds_monthly_inspection_8 ["7-bbed985d65ac92c176581630b5280d76", "6-e9a6adb9a14af59ca223eae1e516c1da", "5-2ae7d772c571def0405cceb0a16ef31c", "4-fb4feb764eca8bb30349e6bf45d66ec8", "3-fa34a74eb7b06f4dafeac9bc79cc5f63", "2-1cc9bdc4143204bb651e30b21d077b4b", "1-eb6a66370bee5934fd181f0d5801007a"]
```
(which is strange because we have compaction running nightly on our CBServer - shouldn't those old revs be discarded?).

Then there are a bunch of statements like so:

```
2015-05-05 09:57:07.582 Crowd Comfort[7624:2290950] SyncVerbose: CBLBulkDownloader[/db_3_19_14_2/_bulk_get]: Finished document
2015-05-05 09:57:07.582 Crowd Comfort[7624:2290950] SyncVerbose: CBLMultipartDocumentReader[_id="(null)"]: Finished loading (0 attachments)
2015-05-05 09:57:07.582 Crowd Comfort[7624:2290950] SyncVerbose: CBLBulkDownloader[/db_3_19_14_2/_bulk_get]: Starting new document; ID="(null)"
2015-05-05 09:57:07.583 Crowd Comfort[7624:2290950] SyncVerbose: CBLBulkDownloader[/db_3_19_14_2/_bulk_get]: Finished document
2015-05-05 09:57:07.583 Crowd Comfort[7624:2290950] SyncVerbose: CBLMultipartDocumentReader[_id="(null)"]: Finished loading (0 attachments)
2015-05-05 09:57:07.583 Crowd Comfort[7624:2290950] SyncVerbose: CBLBulkDownloader[/db_3_19_14_2/_bulk_get]: Starting new document; 
<etc...>
```

CBL 1.0.3, tested on SG 1.0.3 and briefly on latest master build. 
We also have `customProperties = @{@"websocket" : @NO}` for the pull replication, as we are unable to get anything with websockets enabled. Not sure if related. 

Let me know what other info I can provide.

**Comment by snej** [comment]
>Let me know what other info I can provide.

As I said above, please profile the app in Instruments using the Time Profiler, and save the profile and send it to me. (Or put it on Dropbox or something and send me a link; it'll probably be big.)

Also, please send me the entire log from a single sync run, with SyncVerbose enabled.

>we have compaction running nightly on our CBServer - shouldn't those old revs be discarded?

The revisions are discarded, but the history isn't. The revision history is sent along with the revision.

**Comment by sapieneptus** [comment]
Ok, I'll send over a link to the Time Profiler. 

BTW, I notice iOS 8.2 included a change in SQLite. I also notice there have been a lot of complaints about the new SQLite update on the web. Have you guys noticed anything with this? Do you have a recommendation for build target version (in case this makes a difference in which version of SQLite is used) ?

**Comment by pasin** [comment]
iOS 8.2 changed SQLite version from 3.7 to 3.8, and there is one fix that @snej did to fix the insertion speed that might be related to the issue here (https://github.com/couchbase/couchbase-lite-ios/commit/f20387ebfb98fefeb60041056c15dad50a0f57f4). The fix was included in 1.0.4 release. @sapieneptus , you may do a quick test switching to use 1.0.4 and see if the slowness is gone.

**Comment by sapieneptus** [comment]
That would be fried gold. I'll give it a try. Thanks @pasin

**Comment by sapieneptus** [comment]
It is miles faster, but still not quite as fast as when we test with 8.1 or lower. We are syncing ~24000 docs, and it seems to take about ~3 minutes. Is this a normal benchmark?

**Comment by ashvindersingh** [comment]
Hi @sapieneptus , I was not able to reproduce the issue. 
With my test, I have 24K documents, each document is 100 bytes. Tested on iPhone5c.  
The total time it took to complete the pull replications = 130 seconds, on iOS8.1 (average of 3 runs of test case).
The total time it took on iOS 8.3 was 129 seconds (average of 3 runs). 

Can you please share some more details on the test setup? To reproduce we would need more info: 
- Data shape 
- Document size
- If document has attachments, attachments size
- Are you testing on simulator or device. Which device?
- Or you can share your test sync gateway. 

Thanks

**Comment by pasin** [comment]
@sapieneptus, 
For a little more info, @ashvindersingh was trying to reproduce the issue with 1.0.4 binary. Along with the information above that will help us reproduce the issue here, it would be really helpful if you could provide the time profiler results when running the app with CBL 1.0.4 on both iOS 8.1 and 8.2/8.3 so that we could look where the additional delay goes to. Please let us know.

**Comment by sapieneptus** [comment]
Hey @pasin  & @ashvindersingh, 

Upon further testing, the sync time seems to be in line with your results. Feel free to mark this issue as closed, I'll be in touch with profiler results/doc examples if we discover anything to the contrary. Thanks so much for both of your help!

**Comment by pasin** [comment]
Glad to hear that. Please let us know if the issue comes back or you see any other issues.
