### ISSUE TITLE
Disallow leading "_" in attachment name (for compatibility)

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#73]
CouchDB doesn't allow attachment names to start with an underscore. (There's a unit test for this, in attachment_names.js.) CBL should probably disallow this too, for compatibility — any such document would get errors replicating to CouchDB anyway.

**Comment by pasin** [comment]
I have started working on this issue, but now I have a question about what to do with the existing attachments if they already have  _ prefixed. @snej or @zgramana , do you have a good way to handle this? or probably not compatible with CouchDB on this is fine.

**Comment by snej** [comment]
Ugh, you're right. Sounds like it's not worth making this change, then. What do you think, Zack?

**Comment by zgramana** [comment]
Alternate options:

* During push replication, we could let the user enable a check for (a) CDB as the endpoint, (b) doc has attachments, (c) when CDB then replace the initial char with something else.

* Otherwise, perhaps just log a warning when a, b, and c are true.

But agree, probably too much work.
