### ISSUE TITLE
PhoneGap build for 1.1

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-ios#736]

**Comment by jamiltz** [comment]
With 1.1, the hostname for PhoneGap apps will be `http://couchbase.lite./` which is only accessible in the simulator (not ideal during development).
See this [thread](https://forums.couchbase.com/t/cordova-ios-cblite-failed-api-requests/4008/4) for more context, do we need to update [CBLLite.m](https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin/blob/master/src/ios/CBLite.m) to use a different hostname?

I made a [change to this starter proj](https://github.com/jamiltz/CouchbaseLite-PhoneGap-Example/commit/a9a83c277b4fc95b8b18fd306d3a8220238c31ec) which uses port 59000 but I'm not sure if that's the right fix.

**Comment by pasin** [comment]
@jamiltz , is the hostname different from v1.0.4?

I understand that CBL iOS registers an NSURLProtocol handler to respond to the urls with lite.couchbase. hostname. So the requests will get processed without going through the network interface (=> better performance). I believe there would be a security reason behind this as well.

**Comment by pasin** [comment]
I have never developed a phonegap app before. Could you explain more about the benefit of exposing the real host & port? One option would be adding a dev or debug mode to the plugin to use real host & port?

**Comment by jamiltz** [comment]
Oh that was 1.0.4 sorry.
Instead of recompiling the source code through XCode with the `phonegap build ios` command every time a file is changed, it's easier to develop the app running in the browser. I've seen a couple intances where users expected the listener to be accessible from Chrome/Safari. It looks like having a debug flag is a good option. Maybe a blog post or paragraph on the mobile portal to show how to edit  CBLLite.m to expose the host & port manually would fix that. Or should we change the plugin itself to have this debug flag?

**Comment by snej** [comment]
This is no different from earlier versions. 

In production you almost always do not want to expose a TCP port because it opens the app up to snooping/attack from outside. I agree that it’s useful during development; it’d be nice if we could add a configuration switch to enable a TCP port. (I don’t know how PhoneGap apps are configured. Is it possible to add environment variables or command-line args when launching an app?)

**Comment by snej** [comment]
Developers definitely shouldn't have to edit Obj-C source files to enable this! Especially because (I'm told) most of them aren't going through Xcode to build/run their app.

Anyway, this is an issue that should be filed on the PhoneGap plugin, not Couchbase Lite itself.

**Comment by snej** [comment]
Oops, sorry, I didn't see this was a pre-existing issue. @jamiltz you should still file a new issue on the PhoneGap plugin.

**Comment by pasin** [comment]
Update:
1. I built PhoneGap Plugin v1.1 with the latest 1.1 binary of both iOS and Android, and the zip file was successfully generated. Internal URL to the [zip file] (http://cbfs.hq.couchbase.com:8484/builds/Couchbase-Lite-PhoneGap-Plugin_1.1.0-69.zip).
2. I sanity checked the iOS plugin with ToDoLite PhoneGap, and it seems to work fine.
3. I asked @hideki to verify the android plugin.

**Comment by hideki** [comment]
Test results for PhoneGap plugin for Android:
- PhoneGap plugin for Android contains correct jar files. 
- And it works fine with ToDoLite PhoneGap sample.
- Latest version of phonegap (5.0.0-0.28.1) requires 2 instruction changes and 1 configuration change for ToDoLite Sample. This is done by Nick (Developer Advocate)

**Comment by pasin** [comment]
A new PhoneGap 1.1 build is [here](http://factory.couchbase.com/view/build/view/mobile_dev/view/phone_gap/job/package_phonegap_plugin/70/).

**Comment by pasin** [comment]
PhoneGap 1.1 [build](http://factory.couchbase.com/view/build/view/mobile_dev/view/phone_gap/job/package_phonegap_plugin/71/) with an updated android binary.

**Comment by pasin** [comment]
PhoneGap 1.1 has been published to the [cordova registry](http://plugins.cordova.io/#/package/com.couchbase.lite.phonegap). Publish to npm is pending.

**Comment by pasin** [comment]
NPM: https://www.npmjs.com/package/couchbase-lite-phonegap-plugin
