### ISSUE TITLE
CBLIncrementalStore does not send notifications for created objects

### ISSUE THREAD

**Issue by jschmid** [couchbase/couchbase-lite-ios#742]
If you build and run the [Core Data sample](https://github.com/couchbaselabs/cblite-coredata-sample-ios) on two devices at the same time, you can try and edit a recipe and see that the properties are updated in the table view. However, if you create a new recipe, the other device will not see that a new recipe has been created. 

I dug into the code and found that the `CBLIncrementalStore` is able to send the `NSManagedObjectContextObjectsDidChangeNotification` notification for deleted and updated documents but does not make a special case for create documents.

You can see that the method [`processCouchbaseLiteChanges`](https://github.com/couchbase/couchbase-lite-ios/blob/fee911eaa98a17b4add93a03a182768ec8a3adf5/Source/API/Extras/CBLIncrementalStore.m#L1930) does mark the new documents as *updated*.

In turn, the `NSFetchedResultsController` is not able to tell the table view that a new row has been created. 

Maybe in the `processCouchbaseLiteChanges` method, you should add a `addedObjectIDs` to create the correct notification. However, I don't know how to check that a document is new. Check that the document's revision's parentRevisionID is nil ?

**Comment by jschmid** [comment]
I have spoken too soon... the notification is indeed sent. I don't get why the `NSFetchedResultsController` is not notified then.

**Comment by pasin** [comment]
Hello @jschmid. Thanks for reporting the issue. What version of CBL are you using?

**Comment by jschmid** [comment]
The last available from the couchbase website.

Sorry I don't have my computer at hand to get the exact version number.

**Comment by pasin** [comment]
I think you are using v1.0.4. I believe this issue was fixed in https://github.com/couchbase/couchbase-lite-ios/commit/cab0902406504373b4669ccd31e0e0e89492e06b, but the fix has been included in 1.0.4. 

Could you try 1.1.0 dev preview or the master branch?

CBL iOS 1.1.0 Dev Preview: http://packages.couchbase.com/builds/mobile/ios/1.1.0/1.1.0-18/couchbase-lite-ios-community_1.1.0-18.zip

I'm closing the ticket for now. Please feel free to reopen if v1.1.0 or master branch still has the issue.

**Comment by jschmid** [comment]
I'm back online. 

Just a quick update to say that I tried with 1.1.0 and it works fine now. Thanks.
