### ISSUE TITLE
Recursive encodeAsJSON: in CBLJSONEncoding class

### ISSUE THREAD

**Issue by rafaortiz** [couchbase/couchbase-lite-ios#774]
Hi,

I'm trying to made a recursive encodeAsJSON: with a main object conforming with CBLJSONEncoding protocol, where he contains an array populated by objects conforming by CBLJSONEncoding protocol too.

But, when I'm trying to save the document, i'm getting the error 400 JSON Invalid. I made some tests, and see the save function only recognise the first level of array containing CBLJSONEncoding objects.

Here is the example:

ObjLevel1 (CBLModel subclass)

```objectivec
- (instancetype) initDefault {
    self = [super initWithNewDocumentInDatabase: DEFAULT_DB];
    if (self) {
        NSInteger total = arc4random_uniform(10);
        NSMutableArray *array = [@[] mutableCopy];
        
        for (int i = 0 ; i < total; i++) {
            ObjLevel2 *cc = [[ObjLevel2 alloc] init];
            [array addObject:cc];
        }
        
        self.objects = [NSArray arrayWithArray:array];
    }
    return self;
}

- (id) encodeAsJSON {
    return @{@"objects" : self.objects};
}
```

ObjLevel2 (CBLJSONEncoding)

```objectivec
- (id) init {
    if (self = [super init]) {
        NSInteger total = arc4random_uniform(10);
        NSMutableArray *array = [@[] mutableCopy];
        
        for (int i = 0 ; i < total; i++) {
            CustomObject *cc = [[CustomObject alloc] init];
            [array addObject:cc];
        }
        
        self.objects = [NSArray arrayWithArray:array];
    }
    return self;
}

- (id) encodeAsJSON {
    return @{@"objects2" : self.objects};
}
```

CustomObject (CBLJSONEncoding)

```objectivec
- (id) init {
    if (self = [super init]) {
        self.customProperty1 = @"test";
        self.customProperty2 = @"test";
    }
    return self;
}

- (id) encodeAsJSON {
    return @{@"property1" : self.customProperty1, @"property2" : self.customProperty2};
}
```

Can anyone help me?

**Comment by snej** [comment]
A CBLModel subclass should not implement CBLJSONEncoding. It's not necessary, because CBLModel has its own mechanism for converting the properties to JSON.

A CBLJSONEncoding implementation is responsible for returning only JSON-compatible objects from its -encodeAsJSON: method. In other words, ObjLevel2's implementation can't return an array of CustomObject instances, it has to internally convert the CustomObjects into JSON-compatible objects first. (We could improve this in the future, but that's how it stands for now.)
