### ISSUE TITLE
Deprecate -[CBLQueryEnumerator reset]? (ASSERTION FAILED: Enumerator is not at start)

### ISSUE THREAD

**Issue by sapieneptus** [couchbase/couchbase-lite-ios#775]
Hi, 

A call to `[rows reset]` consistently yields:

```
*** ASSERTION FAILED: Enumerator is not at start
2015-06-17 17:04:48.014 Crowd Comfort[17553:491665] *** Assertion failure in -[CBLQueryEnumerator reset](), /Users/christopherfuentes/couchbase-lite-ios/Source/API/CBLQueryEnumerator.m:178
```

Not entirely sure what this means... shouldn't the enumerator not be at the start when I call reset?

**Comment by pasin** [comment]
Just looked at the code and found that if the enumerator doesn't use the iterator (CBLQuery -runAsync: doesn't use the iterator), the assertion will fail.

**Comment by sapieneptus** [comment]
Would this be easy to patch myself? Or some workaround to reset the enumerator?

**Comment by pasin** [comment]
As a workaround, can you use CBLQuery -run instead? You can wrap the call with CBLManager -doAsync: to make it async (This will run on the same thread as your database).

**Comment by pasin** [comment]
Sorry for the confusion. The assertion will happen only when the enumerator is using the iterator (opposite to what I said earlier). For a workaround, can you use CBLEnumerator's -rowAtIndex instead?

**Comment by pasin** [comment]
@sapieneptus , are you using -run or -runAsync?

**Comment by sapieneptus** [comment]
We are using `run`, and it's dispatched on our database's dispatch queue, but I think the call to `reset` might be on a different queue. The strange thing is it consistently works for some calls and then crashes in different contexts.

**Comment by pasin** [comment]
When using -run method, CBLQueryEnumerator will use CBLQueryIteratorBlock for iterating. The internal implementation of CBLQueryIteratorBlock could be iterating over an NSEnumerator object or something else (e.g. DocEnumerator for ForestDB Storage engine). Therefore, as of now there are no easy ways to reset the CBLQueryIteratorBlock. 

I think here are a few workaround options:
1. Using -runAsync: instead of run. The -runAsync method returns a CBLQueryEnumerator object which iterates over an array of rows.

2. Instead of using -nextRow, use -rowAtIndex: which will skip using the CBLQueryIteratorBlock object for iterating.

3. Make CBLQueryEnumerator always iterating over an array.

**Comment by pasin** [comment]
>The strange thing is it consistently works for some calls and then crashes in different contexts.
Probably, calling -reset before calling -nextRow. Calling -nextRow will trigger a usage of the iterator object.

**Comment by pasin** [comment]
** Update to the previous comment.

Or call some other methods e.g. allObjects, count, or rowAtIndex: that loads an internal rows array (results to skip using CBLQueryIteratorBlock) before calling -reset.

**Comment by snej** [comment]
The -reset method made sense in the 1.0 implementation where the query gets the entire result set as an array and then the enumerator just doles out elements of the array. It's easy to reset that by just moving the next-item index back to zero.

In 1.1 the query implementation actually returns a true iterator. This is more efficient because it doesn't require all the rows to be kept in memory at once, and it allows the client's enumeration to start sooner before the entire query completes. But it means that you can't go back and start over.

CBLQueryEnumerator in 1.1 has two modes, one where it just passes through the elements of the iterator, and another where it stores them in an array. In the latter mode you can do -reset.

Anyway the TL;DR is that if the first thing you do with the enumerator is to access its `allRows` or `allObjects` property, it will store all the rows into an array and after that you can enumerate them and use -reset.

**Comment by snej** [comment]
We should probably deprecate the -reset method.

**Comment by sapieneptus** [comment]
@snej That makes sense, but if I'm not doing one of those calls as the first read, how would I later reset the iterator if `reset` is deprecated?

**Comment by snej** [comment]
If you wanted to iterate more than once, you'd just get the `allRows` property, i.e. an NSArray, and then run a `for` loop over that (or get an NSEnumerator from it via `objectEnumerator`) as often as you want.

**Comment by sapieneptus** [comment]
@snej Per your previous comment, wouldn't that load everything into memory? Couldn't `[query reset]` generate a new iterator or something?

It's not really a big problem for us AFAIK if we have to keep them in in mem for now, but we do try to be careful about potential RAM bubbles.

**Comment by snej** [comment]
-reset just moves the iterator back to the beginning so you can get the same rows again. It doesn't re-run the query. What you're suggesting would re-run the query, possibly producing different results. (If that's what you want, just call -run on the CBLQuery again.)
