### ISSUE TITLE
deferred attachment download

### ISSUE THREAD

**Issue by jchris** [couchbase/couchbase-lite-ios#79]
You should be able to write a callback that is invoked when pull replicating, that decides which attachments you want. 

And later when you try to load an attachment locally that you didn't download, it should transparently load it from the cloud and store it locally until it expires.

**Comment by snej** [comment]
At the API level, I think what's needed is:

1. A per-replication configuration that determines whether or not the puller should download a specific attachment at the same time it's downloading the revision containing it. This could be:
  * a block that's passed the revision as an NSDictionary and can return something like the names of the attachments to skip;
  * or a parameter like a maximum size to download or a set of MIME types to skip
2. A way to tell if an Attachment object has a locally-available body (probably just testing for `contents == nil`)
3. A method to request downloading an Attachment's body
4. A way to track progress/error/completion status of the download
5. A way to receive content incrementally as it's downloaded (probably by reading from the `contentStream`)

An interesting side effect of this is that a delayed download of an attachment needs to know which Replication to send the request to. That could be tricky; does that info need to be stored alongside the revision? (And it probably needs to know more than just the URL, since there could be multiple pulls from the same URL with different credentials.) Or does the application pass the Replication object in when it makes the request to download the attachment? I'm leaning toward the latter, to avoid having to change the local db schema and add overhead.

**Comment by brettharrisonzya** [comment]
I have made a first pass at this feature for the C# client.
https://github.com/couchbase/couchbase-lite-net/pull/471

**Comment by snej** [comment]
This is in progress — implementation is on the branch `feature/lazy_attachments`. I have some [draft documentation](https://github.com/couchbase/couchbase-lite-ios/wiki/Deferred-Attachment-Downloading) on the wiki.

**Comment by pasin** [comment]
Should there be a way to purge the attachments after downloading as well so it will be working like a cache? Maybe too complicated?

**Comment by snej** [comment]
Good point. I just added a note about that in the Limitations section of the wiki page. It would probably be very easy to purge an attachment (just delete the blob), except that if there are other attachments with the exact same data they'd be deleted too. (Not sure if that would be an issue that comes up in real life, though.)

**Comment by snej** [comment]
To be able to resume an interrupted download (without starting over) we'll need SG to support Range: headers; filed couchbase/sync_gateway#1046.

**Comment by snej** [comment]
I've filed issues covering the remaining limitations/enhancements, so I'm going to close this since the basic feature is implemented.

**Comment by NitzDKoder** [comment]
@hideki pls confirm if this is available this in android?
