### ISSUE TITLE
400 bad_request for view query with stale is false parameter

### ISSUE THREAD

**Issue by HanzhiDou** [couchbase/couchbase-lite-ios#803]
After upgraded Couchbase-Lite-PhoneGap-Plugin on my hybrid iOS cordova app (ios7, ios8) to latest 1.1.0 version, if view query with parameter stale as false, it will always return 400 bad_request.

It works well without stale parameter in the view query request, and stale as false works OK in previous version 1.0.4.

Hanzhi

**Comment by snej** [comment]
`false` isn't a supported value for `stale` — [as in CouchDB](http://docs.couchdb.org/en/latest/api/ddoc/views.html) the possible values are `ok` or `update_after`. If you don't want stale queries, just leave out this parameter entirely; 'false' is effectively the default value. The only reason you didn't get an error in 1.0.4 is that it ignored the `stale=` parameter entirely :-)

Couchbase Server changed the default behavior of queries to use stale data, so they also added a `stale=false` option to force the original behavior.

I agree that this is confusing, especially since a lot of people using CBL are going to be more familiar with Couchbase Server than with CouchDB. And it's trivial to add support for a `false` value.
