### ISSUE TITLE
Expose totalRows from CBLView to developers

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#808]
I would like to see the totalRows property of CBLView moved from CBLView+Internal.h to CBLView.h. That way I'll be able to get easy access to the number of rows in the view.

I display a list of Form objects and the count of the number of associated Records next to the form name. It would be much quicker to simply get the number of rows from the view than it would be to get the value from the reduce block since there could be any number of Records in a Form, possibly hundreds, or tens of thousands.

Here's an example of how I display this information in my app. The sample shows only a few rows for each form, but as mentioned, it could be tens of thousands for each form. There can be any number of Form objects listed. I have one CBLView per form.

<img width="480" alt="screen shot 2015-07-14 at 3 35 36 pm" src="https://cloud.githubusercontent.com/assets/586075/8685756/1b74bea8-2a3e-11e5-9aa9-31b7fd513043.png">

**Comment by snej** [comment]
Quoting myself from the mailing-list thread that led to this:

>That would make sense, especially since that info is already provided in the REST API (as the `total_rows` property in the JSON response to a view query.)

>The question is, should it return the _current_ total rows in the index (as it does today), or should it update the view index first (to reflect the current state of the database)? I lean toward the latter.

**Comment by brendand** [comment]
As long as it doesn't slow down getting the totalRows value doing the latter. Because displaying a list of objects and the record counts as I'm doing above should be as quick as possible and not have to wait to update the indexes before being able to display the results.

**Comment by snej** [comment]
If the index is already up-to-date, it takes almost no time.

If the index isn't up-to-date, it will take time — all the recently-updated docs have to be run through the map function and the emitted rows inserted into the index. (This is the same work that's done before a query if the index is out of date.) But the alternative would be returning stale results: for example if you started with a new database, defined the view, added 100 docs, and then asked for `view.totalRows`, you'd get 0 (because there aren't any rows in the index yet.)

**Comment by brendand** [comment]
Awesome! Thanks so much!
