### ISSUE TITLE
Crash when CBLQuery's fullTextQuery property contains a single double quote

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#840]
With a ForestDB datastore, I get the following error when the fullTextQuery property of the CBLQuery object is simply a double-quote " character:

`libc++abi.dylib: terminating with uncaught exception of type char const*`

It happens when the first  character is a ". If the " is in any other position it doesn't crash.

With a single double-quote character in the fullTextQuery of an SQLite datastore, I get the following error:

```
[45819:3101911] Error calling sqlite3_step (1: malformed MATCH expression: ["]) rs
[45819:3101911] *** Assertion failure in -[CBL_FMDatabase releaseReadLock], ~/Projects/couchbase-lite-ios/vendor/fmdb/src/FMDatabase.m:231
Too many calls to releaseReadLock
```

I can work around it by making sure there's an even number of double-quotes in the fullTextQuery property, but it seems like something that should be handled at a lower level.

**Comment by snej** [comment]
Wow, nice catch — both of the storage engines had a (different) nasty low-level query bug and some (different) missing error handling. I've fixed it now.

That query string will now return an error 400 from `-[CBLQuery run:]` in SQLite, but with ForestDB there will be no error, just an empty result set. That's because ForestDB's FTS query string parsing is much simpler: it just ignores quotes like other punctuation, so a query with just a quote is the same as an empty query.

**Comment by snej** [comment]
(I just realized that "nice catch" is a joke, since one of the bugs was due to a missing `catch` block. Ha ha.)

**Comment by brendand** [comment]
Hehe... Excellent! Thanks for fixing it so quickly!
