### ISSUE TITLE
Setting type property in initializer no longer works in v1.1

### ISSUE THREAD

**Issue by marbetschar** [couchbase/couchbase-lite-ios#845]
I used to initialize the type property of an iOS Model in it's initializer. Something like the following:

    required convenience init(){
        self.init(forDocument: StoreConnection.sharedInstance().database[NSUUID().UUIDString])
        self.type = "Person"
    }

Since I've updated to v1.1 I can't call the init(forDocument:) initializer directly, so I have to call the self.init() first - which then lends to an endless loop:

    required convenience init(){
        self.init()
        self.init(forDocument: StoreConnection.sharedInstance().database[NSUUID().UUIDString])
        self.type = "Person"
    }

What's wrong?

The goal is to use the CBLModel Class directly for creating new typed documents easily as follows:

    let person = Person() //creates a new person document

And the following would still map to an existing document:

    let person = Person(forDocument: doc) //maps to an existing document

**Comment by marbetschar** [comment]
I also tried to just use init(forNewDocumentInDatabase:) - but for some reason the type attribute does not get set autmatically.

I assume because the modelFactory's documentTypeForClass returns nil?

**Comment by snej** [comment]
This is described in the [1.1 release notes](https://github.com/couchbase/couchbase-lite-ios/wiki/v1.1-API-Changes#cblmodel):

* CBLModel now has no public initializer methods, and you should not implement any yourself in subclasses.
  * Instead of calling `-initWithNewDocumentInDatabase:`, call `+modelForNewDocumentInDatabase:`.
  * In a subclass, to set up transient state of an instance, override `-awakeFromInitializer`.

These changes were necessary to be able to enforce the invariant that there is at most one CBLModel instance for each CBLDocument.

**Comment by marbetschar** [comment]
Hi Jens!

Thanks for getting back!!

Ok, I can see the reason why these changes happened. But I'm totally lost in how to use the CBLModels best now? Are there any examples of typical subclass use cases (preferably in Swift)?

Unfortunately I wasn't able to find any example since yesterday :(

**Comment by snej** [comment]
Our sample app [ToDoLite](https://github.com/couchbaselabs/ToDoLite-iOS) uses CBLModel, including subclasses. It's written in Objective-C but the same concepts should be portable to Swift.
