### ISSUE TITLE
release/1.1.1 branch fails unit test -[DatabaseInternalTests test24_UpgradeDB]

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#866]
When I test the release/1.1.1 branch, the unit tests don't pass. I don't have the most typical setup (OS X 10.11 beta 6, Xcode 7 beta 5) but the errors don't look like they're related to new-OS changes.

The failure I see is in -[DatabaseInternalTests test24_UpgradeDB]; the upgrade itself returns status 491 (kCBLStatusBadAttachment). That status is set at CBLDatabase+Attachments.m:335:

```objc
        } else if (attachment->revpos >= generation) {
            *outStatus = kCBLStatusBadAttachment;
            return nil;
        }
```

The `>=` test there is wrong; it should be `>`. On the master branch this was fixed by commit d2fc8dfd8798 ("Fixed 2 small attachment-installation issues exposed by the new replicator") but we didn't cherry-pick this into 1.1.1 because it was part of the new-replicator branch. Somehow the other changes related to attachments exposed this bug.

I'm a little worried that we were able to release 1.1.1 without the unit tests passing … unless somehow this only fails on my machine?

**Comment by snej** [comment]
I cherry-picked d2fc8dfd879862eadecdbb10c3f11440ed3d1523 into release/1.1.1 on my machine and it fixes the failure. All of the unit tests pass now.

**Comment by pasin** [comment]
There are a series of cherry-picking. The major one was on Jul 29, and all unit tests were passed. 

On Jul 30, there is one more cherry-picking (https://github.com/couchbase/couchbase-lite-ios/commit/16b459df98f6a8068237cd6a9c76e04c031d6e83) that fixed an issue about attachment revpos  , and the this fix exposes the bug that was fixed by the missing commit (https://github.com/couchbase/couchbase-lite-ios/commit/d2fc8dfd879862eadecdbb10c3f11440ed3d1523). I think I forgot to run the full unit test after cherry-picking this fix.

There are more 3 commits after that and, all of them are related to missing Symbol and Jenkin build issues. For these 3 commits, I only checked if the binary could be built or not.

**Comment by pasin** [comment]
I cherry-picked the missing commit and the other 3 commits that I checked with @zgramana today. All unit tests passes. I didn't cherry-pick any commits that are parts of the new replicator implementation, and the missing commit is a part of the new replicator commits. 

@snej do you see anything else that we should pick from https://github.com/couchbase/couchbase-lite-ios/pull/783 to 1.1.1 release?

**Comment by pasin** [comment]
Closing the issue now.
