### ISSUE TITLE
query.postFilter with limit gives limit+1 results.

### ISSUE THREAD

**Issue by ajithrnayak** [couchbase/couchbase-lite-ios#893]
I observed that applying "limit + postFilter" gives me **limit+1** results.

Following returns me 51 results (without limit, 354 results).

`query.postFilter = [NSPredicate predicateWithFormat:@"key[3] == %@",@"created"];`
 `query.limit = 50;`
`[query run:nil]`

From community group's [post][1] 
And, I'm using version 1.1.1(enterprise) downloaded from continuous build's dashboard.

[1]:https://groups.google.com/d/msg/mobile-couchbase/kRMipQg8WRc/LxvIV4deLAAJ

**Comment by snej** [comment]
Hm, -[View_tests test06_ViewCustomFilter] already tests postFilter + limit, and that passes.

…ah, but that's because the limit didn't have any effect: it's set to 2, but the postFilter would only have matched 2 documents anyway. Lowering the limit to 1 exposes the bug.

According to the test case, the earlier fix for postFilter+limit was #574
