### ISSUE TITLE
Add support for NSDecimalNumber JSON serialization

### ISSUE THREAD

**Issue by lisacmer** [couchbase/couchbase-lite-ios#910]
In our project we use currency values, so we have to deal with decimal numbers. Unfortunately current  serialization engine supports only NSNumber which leads to rounding errors and values like 0.69999999. It would be really nice to have NSDecimalNumber serializer as well.

**Comment by snej** [comment]
JSON doesn't support the kind of metadata that would make this possible. It doesn't have multiple numeric types, just numbers expressed in decimal. So when parsing a number we choose NSNumber (wrapping a double) because it's more general purpose.

CBLModel does support properties of type NSDecimalNumber. IIRC, it encodes them as strings to avoid any loss of precision, then parses the string value back to an NSDecimalNumber.

If you need to store an NSDecimalNumber in a document without using CBLModel, you can do the same thing: store it in the object tree as an NSString instead.
