### ISSUE TITLE
No auto-compact (db.forest getting very large)

### ISSUE THREAD

**Issue by thiver** [couchbase/couchbase-lite-ios#922]
App configured with SQLite:

cblite files gets to 10MB
(if the file size gets excessive, database compact ensures it becomes small again)

App configured with ForestDB:

db.forest gets to 200MB+
calling database compact function results in db.forest.1, db.forest.2 copies that don't get removed automatically

Note: because the app only syncs one way (server to app with own json api), the max revision depth tree is set to 1.

**Comment by snej** [comment]
Interesting. How much data does your database contain, roughly? (Total size of JSON docs + attachments.)

ForestDB should compact automatically in the background. The database format is append-only, like CouchDB, so the file gets larger as docs are updated. When it contains 50% obsolete data it will compact by writing to a new file and replacing the old file with the new one. Sounds like this isn't happening.

**Comment by thiver** [comment]
Approx. 6MB, there are no attachments; it seems indeed that the database nevers compacts.

I did a sync with the online api, called the compact function manually and replaced the 200MB db.forest file with the much smaller (7MB) db.forest.1 file. Starting from that file, the file seems to grow much slower (in stages of a couple of MB's on each content update).

**Comment by thiver** [comment]
The sync layer exists of a set of operations that download the source json files, each spinning of a background database on completion with [doc update:...] to update/create the documents.

**Comment by snej** [comment]
What might be happening with the compaction is that the app quits before the background auto-compact completes, so the attempt to compact is abandoned. What happens if you leave the app running for a while after the initial download?

I'll look into why the explicit compact call leaves stuff behind.

> the app only syncs one way (server to app with own json api)

So you're not using the Couchbase Lite replicator? Your code may not be inserting the documents efficiently, if the db grows to 200MB during the download. Make sure you're updating each document only once, and batching multiple inserts/updates together in a transaction.

> each spinning of a background database on completion with [doc update:...]

What does that mean exactly? Do you create a new CBLDatabase instance each time?

**Comment by snej** [comment]
Ah, I just found that when we initialize ForestDB we're not enabling one of the flags that controls auto-compact, so it doesn't turn on :( I'll fix that.

The reason the multiple files are being left behind after manual compaction is that you've got multiple database handles open (from multiple CBLDatabase instances), and those are keeping the original file alive. I'm asking the ForestDB folks how we can get those cleaned up more quickly. But it's also better for you to avoid creating too many database instances on the same file.

**Comment by snej** [comment]
I got auto-compaction enabled a week ago, but it turned out that it broke my ForestDB encryption plugin, because auto-compact renames database files and encryption was mapping files to keys by their filenames.

So over the weekend I re-implemented encryption directly inside ForestDB and submitted it. It's almost out of code review; once it's in, I can push the auto-compact changes.
