### ISSUE TITLE
Canned database

### ISSUE THREAD

**Issue by paulgee31** [couchbase/couchbase-lite-ios#948]
I'm looking to install a prebuilt database with my app on iOS.

Prior to version 1.1 I used to copy a prebuilt cblite file from the resource bundle. Now it seems I need:
cblite 
cblite-shm
cblite-wal 

Is this correct? Do I just copy these to the library/Application Support/CouchbaseLite directory? And then open an existing database?

**Comment by snej** [comment]
We prefer that people ask questions on the Google group or web forum (see the [Guidelines for Contributing](https://github.com/couchbase/couchbase-lite-ios/blob/master/CONTRIBUTING.md#1-i-have-a-question-).

The `-shm` and `-wal` files are SQLite temp files. They're supposed to be cleaned up when the database is closed, but that doesn't always happen. I don't think you need to copy them. (@pasin, is this correct? I know you did some work on this.)

**Comment by pasin** [comment]
If the database is closed properly (via database -close or manager -close method) the -wal file should be merged to the database file and its size will be 0 bytes. I don't remember if the -shm file will be left out or removed. If the -wal file has 0 bytes, only database file is needed. Otherwise, all 3 files will be needed.

Anyway, in 1.1.1, we fixed the issue that the background database doesn't get closed when closing the database so now calling database's -close method should close the database properly.
