### ISSUE TITLE
CBLIS doesn't handle accesses from multiple dispatch queues

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#958]
When using multiple CoreData contexts (each context can have different dispatch queue), CBLIS could be accessed by different dispatch queue other than the root context's dispatch queue. CBLIS needs a way to handle that. One easy way is to always use root context's dispatch queue to operate.

**Comment by cflorion** [comment]
Hmmm interesting.
I'm trying to understand.

Let's take the common example of a multiple CoreData contexts setup with one mainContext (for the UI, on the main queue) and a parentContext (on a background queue, for importing data).

- When the user touches the "create stuff" button on the screen, a Stuff ManagedObject is created in the mainContext (with a temporary ObjectID at this point). We save the mainContext, the objectID is now permanent, we continue with a save on the rootContext. The rootContext is wired to the persistentStore, so when a NSManagedObject is inserted, the CBLIncrementalStore created a CBLDocument and stores it to disk.

- When data comes from a replication. The data is inserted in the CBLDatabase, the rootContext is informed of the changes by the IncrementalStore. At this point the mainContext is unaware of the changed since in this kind of stack, the changes go from the child to the parent, but not from the parent to the child. So the CBL created a NSNotification in order to inform the mainContext. And now everything is up to date.

I may have misunderstood but in the example I'm giving, only the rootContext talks directly to the CBLDatabase. The CBLIS is only talking to the mainContext when sending the notification (on the main queue). In my opinion only the root context's dispatch queue should be used.

But, again, I might have misunderstood.

**Comment by pasin** [comment]
Yeah, that's what I first understood too. 

However, while trying to fix save operation performance with parent (private queue) and child (main queue) context model, I have noticed that the main context (via NSFetchRemoteController) requests to the CBLIS to resolve the entity properties and relationships - more specifically, the following two methods.

```
- (NSIncrementalStoreNode*) newValuesForObjectWithID: (NSManagedObjectID*)objectID
                                         withContext: (NSManagedObjectContext*)context
                                               error: (NSError**)outError;

- (id) newValueForRelationship: (NSRelationshipDescription*)relationship
               forObjectWithID: (NSManagedObjectID*)objectID
                   withContext: (NSManagedObjectContext*)context
                         error: (NSError**)outError;
```

If you are on [feature/issue_938_perf](https://github.com/couchbase/couchbase-lite-ios/tree/feature/issue_938_perf) branch, you can turn on the logging (set LOGGING 1 on top of the CBLIS source code) to see which thread/context requests to CBLIS.
